import type { CastCodec, Codecs } from '~/codecs.ts';
import { refineCodecs } from '~/codecs.ts';
import { sql } from '~/sql/sql.ts';
import type { PartialWithUndefined } from '~/utils.ts';

export type SingleStoreType =
	// Numeric
	| 'tinyint'
	| 'smallint'
	| 'mediumint'
	| 'int'
	| 'bigint'
	| 'bigint:number'
	| 'bigint:string'
	| 'serial'
	| 'decimal'
	| 'decimal:number'
	| 'decimal:bigint'
	| 'float'
	| 'double'
	| 'real'
	// Boolean
	| 'boolean'
	// Text
	| 'char'
	| 'varchar'
	| 'text'
	| 'enum'
	// Binary
	| 'binary'
	| 'varbinary'
	// Datetime
	| 'date'
	| 'date:string'
	| 'datetime'
	| 'datetime:string'
	| 'time'
	| 'timestamp'
	| 'timestamp:string'
	| 'year'
	// Structured
	| 'json'
	| 'vector_i8'
	| 'vector_i16'
	| 'vector_i32'
	| 'vector_i64'
	| 'vector_f32'
	| 'vector_f64';

const SINGLESTORE_ALIAS_TO_TYPE_MAP = {
	dec: 'decimal',
	numeric: 'decimal',
	fixed: 'decimal',
	'double precision': 'double',
	bool: 'boolean',
	'character varying': 'varchar',
	character: 'char',
	tinytext: 'text',
	mediumtext: 'text',
	longtext: 'text',
	tinyblob: 'varbinary',
	blob: 'varbinary',
	mediumblob: 'varbinary',
	longblob: 'varbinary',
	vector: 'vector_f32',
} as const satisfies Record<string, SingleStoreType>;

export type SingleStoreAliasType = keyof typeof SINGLESTORE_ALIAS_TO_TYPE_MAP;

export type SingleStoreColumnType =
	| SingleStoreType
	| SingleStoreAliasType;

export function resolveSingleStoreTypeAlias(type: string) {
	return (SINGLESTORE_ALIAS_TO_TYPE_MAP as Record<string, SingleStoreType | undefined>)[type] ?? type;
}

export type SingleStoreCodecs = Codecs<SingleStoreType>;

export const castToText: CastCodec = (name) => sql`cast(${name} as char)`;
export const castToHexBlob: CastCodec = (name) => sql`hex(${name} :> blob)`;

// Prevent `float` precision loss
export const castToDouble: CastCodec = (name) => sql`(${name} :> double) * 1.0`;
export const floatFromDouble = (value: number): number => {
	const f = Math.fround(value);
	if (!Number.isFinite(f)) return f;

	for (let precision = 1; precision <= 9; precision++) {
		const candidate = Number(f.toPrecision(precision));
		if (Math.fround(candidate) === f) return candidate;
	}

	return f;
};

export type VectorElementType = 'I8' | 'I16' | 'I32' | 'I64' | 'F32' | 'F64';
const VECTOR_ELEMENT_ARRAYS = {
	I8: Int8Array,
	I16: Int16Array,
	I32: Int32Array,
	I64: BigInt64Array,
	F32: Float32Array,
	F64: Float64Array,
} as const satisfies Record<VectorElementType, unknown>;

export const vectorNormalizer = <
	TElement extends VectorElementType,
	TResult extends bigint[] | number[] = TElement extends 'I64' ? bigint[] : number[],
>(elementType: TElement) =>
(
	value: string | Buffer | Uint8Array | unknown[],
): TResult => {
	if (Array.isArray(value)) return value as any;

	if (typeof value === 'string') {
		if (value.startsWith('[')) {
			const items = value.slice(1, -1).split(',');
			return (elementType === 'I64' ? items.map(BigInt) : items.map(Number)) as TResult;
		}

		value = Buffer.from(value, 'hex');
	}

	const bytes = new Uint8Array(value as Buffer);
	const Ctor = VECTOR_ELEMENT_ARRAYS[elementType];
	// eslint-disable-next-line unicorn/prefer-spread
	return Array.from<any>(new Ctor(bytes.buffer, 0, bytes.length / Ctor.BYTES_PER_ELEMENT)) as TResult;
};

export const genericSingleStoreCodecs = {
	boolean: {
		normalizeInJson: Boolean,
	},
	binary: {
		castInJson: castToText,
	},
	varbinary: {
		castInJson: castToText,
	},
	time: {
		castInJson: castToText,
	},
	date: {
		normalizeInJson: (value: string) => new Date(value),
	},
	datetime: {
		castInJson: castToText,
		normalizeInJson: (value: string) => new Date(value.replace(' ', 'T') + 'Z'),
	},
	'datetime:string': {
		castInJson: castToText,
	},
	timestamp: {
		castInJson: castToText,
		normalizeInJson: (value: string) => new Date(value + '+0000'),
	},
	'timestamp:string': {
		castInJson: castToText,
	},
	year: {
		normalizeInJson: Number,
	},
	float: {
		castInJson: castToDouble,
		normalizeInJson: floatFromDouble,
	},
	decimal: {
		castInJson: castToText,
	},
	'decimal:number': {
		castInJson: castToText,
		normalizeInJson: Number,
	},
	'decimal:bigint': {
		castInJson: castToText,
		normalizeInJson: BigInt,
	},
	serial: {
		castInJson: castToText,
		normalizeInJson: Number,
	},
	bigint: {
		castInJson: castToText,
		normalizeInJson: BigInt,
	},
	'bigint:number': {
		castInJson: castToText,
		normalizeInJson: Number,
	},
	'bigint:string': {
		castInJson: castToText,
	},
	enum: {
		castInJson: castToText,
	},
	vector_i8: {
		castInJson: castToHexBlob,
		normalizeInJson: vectorNormalizer('I8'),
	},
	vector_i16: {
		castInJson: castToHexBlob,
		normalizeInJson: vectorNormalizer('I16'),
	},
	vector_i32: {
		castInJson: castToHexBlob,
		normalizeInJson: vectorNormalizer('I32'),
	},
	vector_i64: {
		castInJson: castToHexBlob,
		normalizeInJson: vectorNormalizer('I64'),
	},
	vector_f32: {
		castInJson: castToHexBlob,
		normalizeInJson: vectorNormalizer('F32'),
	},
	vector_f64: {
		castInJson: castToHexBlob,
		normalizeInJson: vectorNormalizer('F64'),
	},
} as const satisfies SingleStoreCodecs;

export const refineGenericSingleStoreCodecs = (
	extension?: PartialWithUndefined<SingleStoreCodecs>,
): SingleStoreCodecs => refineCodecs<SingleStoreType>(genericSingleStoreCodecs, extension);

export const unionsTypeTable = {
	tinyint: {
		tinyint: 'tinyint',
		smallint: 'smallint',
		mediumint: 'mediumint',
		int: 'int',
		bigint: 'bigint:number',
		'bigint:number': 'bigint:number',
		'bigint:string': 'bigint:number',
		serial: 'decimal:number',
		decimal: 'decimal:number',
		'decimal:number': 'decimal:number',
		'decimal:bigint': 'decimal:number',
		float: 'float',
		double: 'double',
		real: 'double',
		boolean: 'tinyint',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'varchar',
		'date:string': 'varchar',
		datetime: 'varchar',
		'datetime:string': 'varchar',
		time: 'varchar',
		timestamp: 'varchar',
		'timestamp:string': 'varchar',
		year: 'int',
		json: 'text',
	},
	smallint: {
		tinyint: 'smallint',
		smallint: 'smallint',
		mediumint: 'mediumint',
		int: 'int',
		bigint: 'bigint:number',
		'bigint:number': 'bigint:number',
		'bigint:string': 'bigint:number',
		serial: 'decimal:number',
		decimal: 'decimal:number',
		'decimal:number': 'decimal:number',
		'decimal:bigint': 'decimal:number',
		float: 'float',
		double: 'double',
		real: 'double',
		boolean: 'smallint',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'varchar',
		'date:string': 'varchar',
		datetime: 'varchar',
		'datetime:string': 'varchar',
		time: 'varchar',
		timestamp: 'varchar',
		'timestamp:string': 'varchar',
		year: 'int',
		json: 'text',
	},
	mediumint: {
		tinyint: 'mediumint',
		smallint: 'mediumint',
		mediumint: 'mediumint',
		int: 'int',
		bigint: 'bigint:number',
		'bigint:number': 'bigint:number',
		'bigint:string': 'bigint:number',
		serial: 'decimal:number',
		decimal: 'decimal:number',
		'decimal:number': 'decimal:number',
		'decimal:bigint': 'decimal:number',
		float: 'float',
		double: 'double',
		real: 'double',
		boolean: 'mediumint',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'varchar',
		'date:string': 'varchar',
		datetime: 'varchar',
		'datetime:string': 'varchar',
		time: 'varchar',
		timestamp: 'varchar',
		'timestamp:string': 'varchar',
		year: 'int',
		json: 'text',
	},
	int: {
		tinyint: 'int',
		smallint: 'int',
		mediumint: 'int',
		int: 'int',
		bigint: 'bigint:number',
		'bigint:number': 'bigint:number',
		'bigint:string': 'bigint:number',
		serial: 'decimal:number',
		decimal: 'decimal:number',
		'decimal:number': 'decimal:number',
		'decimal:bigint': 'decimal:number',
		float: 'double',
		double: 'double',
		real: 'double',
		boolean: 'int',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'varchar',
		'date:string': 'varchar',
		datetime: 'varchar',
		'datetime:string': 'varchar',
		time: 'varchar',
		timestamp: 'varchar',
		'timestamp:string': 'varchar',
		year: 'int',
		json: 'text',
	},
	bigint: {
		tinyint: 'bigint',
		smallint: 'bigint',
		mediumint: 'bigint',
		int: 'bigint',
		bigint: 'bigint',
		'bigint:number': 'bigint',
		'bigint:string': 'bigint',
		serial: 'decimal:bigint',
		decimal: 'decimal:bigint',
		'decimal:number': 'decimal:bigint',
		'decimal:bigint': 'decimal:bigint',
		float: 'double',
		double: 'double',
		real: 'double',
		boolean: 'bigint',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'varchar',
		'date:string': 'varchar',
		datetime: 'varchar',
		'datetime:string': 'varchar',
		time: 'varchar',
		timestamp: 'varchar',
		'timestamp:string': 'varchar',
		year: 'bigint',
		json: 'text',
	},
	'bigint:number': {
		tinyint: 'bigint:number',
		smallint: 'bigint:number',
		mediumint: 'bigint:number',
		int: 'bigint:number',
		bigint: 'bigint:number',
		'bigint:number': 'bigint:number',
		'bigint:string': 'bigint:number',
		serial: 'decimal:number',
		decimal: 'decimal:number',
		'decimal:number': 'decimal:number',
		'decimal:bigint': 'decimal:number',
		float: 'double',
		double: 'double',
		real: 'double',
		boolean: 'bigint:number',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'varchar',
		'date:string': 'varchar',
		datetime: 'varchar',
		'datetime:string': 'varchar',
		time: 'varchar',
		timestamp: 'varchar',
		'timestamp:string': 'varchar',
		year: 'bigint:number',
		json: 'text',
	},
	'bigint:string': {
		tinyint: 'bigint:string',
		smallint: 'bigint:string',
		mediumint: 'bigint:string',
		int: 'bigint:string',
		bigint: 'bigint:string',
		'bigint:number': 'bigint:string',
		'bigint:string': 'bigint:string',
		serial: 'decimal',
		decimal: 'decimal',
		'decimal:number': 'decimal',
		'decimal:bigint': 'decimal',
		float: 'double',
		double: 'double',
		real: 'double',
		boolean: 'bigint:string',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'varchar',
		'date:string': 'varchar',
		datetime: 'varchar',
		'datetime:string': 'varchar',
		time: 'varchar',
		timestamp: 'varchar',
		'timestamp:string': 'varchar',
		year: 'bigint:string',
		json: 'text',
	},
	serial: {
		tinyint: 'decimal:number',
		smallint: 'decimal:number',
		mediumint: 'decimal:number',
		int: 'decimal:number',
		bigint: 'decimal:number',
		'bigint:number': 'decimal:number',
		'bigint:string': 'decimal:number',
		serial: 'bigint:number',
		decimal: 'decimal:number',
		'decimal:number': 'decimal:number',
		'decimal:bigint': 'decimal:number',
		float: 'double',
		double: 'double',
		real: 'double',
		boolean: 'decimal:number',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'varchar',
		'date:string': 'varchar',
		datetime: 'varchar',
		'datetime:string': 'varchar',
		time: 'varchar',
		timestamp: 'varchar',
		'timestamp:string': 'varchar',
		year: 'bigint:number',
		json: 'text',
	},
	decimal: {
		tinyint: 'decimal',
		smallint: 'decimal',
		mediumint: 'decimal',
		int: 'decimal',
		bigint: 'decimal',
		'bigint:number': 'decimal',
		'bigint:string': 'decimal',
		serial: 'decimal',
		decimal: 'decimal',
		'decimal:number': 'decimal',
		'decimal:bigint': 'decimal',
		float: 'double',
		double: 'double',
		real: 'double',
		boolean: 'decimal',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'varchar',
		'date:string': 'varchar',
		datetime: 'varchar',
		'datetime:string': 'varchar',
		time: 'varchar',
		timestamp: 'varchar',
		'timestamp:string': 'varchar',
		year: 'decimal',
		json: 'text',
	},
	'decimal:number': {
		tinyint: 'decimal:number',
		smallint: 'decimal:number',
		mediumint: 'decimal:number',
		int: 'decimal:number',
		bigint: 'decimal:number',
		'bigint:number': 'decimal:number',
		'bigint:string': 'decimal:number',
		serial: 'decimal:number',
		decimal: 'decimal:number',
		'decimal:number': 'decimal:number',
		'decimal:bigint': 'decimal:number',
		float: 'double',
		double: 'double',
		real: 'double',
		boolean: 'decimal:number',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'varchar',
		'date:string': 'varchar',
		datetime: 'varchar',
		'datetime:string': 'varchar',
		time: 'varchar',
		timestamp: 'varchar',
		'timestamp:string': 'varchar',
		year: 'decimal:number',
		json: 'text',
	},
	'decimal:bigint': {
		tinyint: 'decimal:bigint',
		smallint: 'decimal:bigint',
		mediumint: 'decimal:bigint',
		int: 'decimal:bigint',
		bigint: 'decimal:bigint',
		'bigint:number': 'decimal:bigint',
		'bigint:string': 'decimal:bigint',
		serial: 'decimal:bigint',
		decimal: 'decimal:bigint',
		'decimal:number': 'decimal:bigint',
		'decimal:bigint': 'decimal:bigint',
		float: 'double',
		double: 'double',
		real: 'double',
		boolean: 'decimal:bigint',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'varchar',
		'date:string': 'varchar',
		datetime: 'varchar',
		'datetime:string': 'varchar',
		time: 'varchar',
		timestamp: 'varchar',
		'timestamp:string': 'varchar',
		year: 'decimal:bigint',
		json: 'text',
	},
	float: {
		tinyint: 'float',
		smallint: 'float',
		mediumint: 'float',
		int: 'double',
		bigint: 'double',
		'bigint:number': 'double',
		'bigint:string': 'double',
		serial: 'double',
		decimal: 'double',
		'decimal:number': 'double',
		'decimal:bigint': 'double',
		float: 'float',
		double: 'double',
		real: 'double',
		boolean: 'float',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'varchar',
		'date:string': 'varchar',
		datetime: 'varchar',
		'datetime:string': 'varchar',
		time: 'varchar',
		timestamp: 'varchar',
		'timestamp:string': 'varchar',
		year: 'float',
		json: 'text',
	},
	double: {
		tinyint: 'double',
		smallint: 'double',
		mediumint: 'double',
		int: 'double',
		bigint: 'double',
		'bigint:number': 'double',
		'bigint:string': 'double',
		serial: 'double',
		decimal: 'double',
		'decimal:number': 'double',
		'decimal:bigint': 'double',
		float: 'double',
		double: 'double',
		real: 'double',
		boolean: 'double',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'varchar',
		'date:string': 'varchar',
		datetime: 'varchar',
		'datetime:string': 'varchar',
		time: 'varchar',
		timestamp: 'varchar',
		'timestamp:string': 'varchar',
		year: 'double',
		json: 'text',
	},
	real: {
		tinyint: 'double',
		smallint: 'double',
		mediumint: 'double',
		int: 'double',
		bigint: 'double',
		'bigint:number': 'double',
		'bigint:string': 'double',
		serial: 'double',
		decimal: 'double',
		'decimal:number': 'double',
		'decimal:bigint': 'double',
		float: 'double',
		double: 'double',
		real: 'double',
		boolean: 'double',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'varchar',
		'date:string': 'varchar',
		datetime: 'varchar',
		'datetime:string': 'varchar',
		time: 'varchar',
		timestamp: 'varchar',
		'timestamp:string': 'varchar',
		year: 'double',
		json: 'text',
	},
	boolean: {
		tinyint: 'tinyint',
		smallint: 'smallint',
		mediumint: 'mediumint',
		int: 'int',
		bigint: 'bigint:number',
		'bigint:number': 'bigint:number',
		'bigint:string': 'bigint:number',
		serial: 'decimal:number',
		decimal: 'decimal:number',
		'decimal:number': 'decimal:number',
		'decimal:bigint': 'decimal:number',
		float: 'float',
		double: 'double',
		real: 'double',
		boolean: 'boolean',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'varchar',
		'date:string': 'varchar',
		datetime: 'varchar',
		'datetime:string': 'varchar',
		time: 'varchar',
		timestamp: 'varchar',
		'timestamp:string': 'varchar',
		year: 'int',
		json: 'text',
	},
	char: {
		tinyint: 'char',
		smallint: 'char',
		mediumint: 'char',
		int: 'char',
		bigint: 'char',
		'bigint:number': 'char',
		'bigint:string': 'char',
		serial: 'char',
		decimal: 'char',
		'decimal:number': 'char',
		'decimal:bigint': 'char',
		float: 'char',
		double: 'char',
		real: 'char',
		boolean: 'char',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'char',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'char',
		'date:string': 'char',
		datetime: 'char',
		'datetime:string': 'char',
		time: 'char',
		timestamp: 'char',
		'timestamp:string': 'char',
		year: 'char',
		json: 'text',
	},
	varchar: {
		tinyint: 'varchar',
		smallint: 'varchar',
		mediumint: 'varchar',
		int: 'varchar',
		bigint: 'varchar',
		'bigint:number': 'varchar',
		'bigint:string': 'varchar',
		serial: 'varchar',
		decimal: 'varchar',
		'decimal:number': 'varchar',
		'decimal:bigint': 'varchar',
		float: 'varchar',
		double: 'varchar',
		real: 'varchar',
		boolean: 'varchar',
		char: 'varchar',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'varbinary',
		varbinary: 'varbinary',
		date: 'varchar',
		'date:string': 'varchar',
		datetime: 'varchar',
		'datetime:string': 'varchar',
		time: 'varchar',
		timestamp: 'varchar',
		'timestamp:string': 'varchar',
		year: 'varchar',
		json: 'text',
	},
	text: {
		tinyint: 'text',
		smallint: 'text',
		mediumint: 'text',
		int: 'text',
		bigint: 'text',
		'bigint:number': 'text',
		'bigint:string': 'text',
		serial: 'text',
		decimal: 'text',
		'decimal:number': 'text',
		'decimal:bigint': 'text',
		float: 'text',
		double: 'text',
		real: 'text',
		boolean: 'text',
		char: 'text',
		varchar: 'text',
		text: 'text',
		enum: 'text',
		binary: 'varbinary',
		varbinary: 'varbinary',
		date: 'text',
		'date:string': 'text',
		datetime: 'text',
		'datetime:string': 'text',
		time: 'text',
		timestamp: 'text',
		'timestamp:string': 'text',
		year: 'text',
		json: 'text',
	},
	enum: {
		tinyint: 'varchar',
		smallint: 'varchar',
		mediumint: 'varchar',
		int: 'varchar',
		bigint: 'varchar',
		'bigint:number': 'varchar',
		'bigint:string': 'varchar',
		serial: 'varchar',
		decimal: 'varchar',
		'decimal:number': 'varchar',
		'decimal:bigint': 'varchar',
		float: 'varchar',
		double: 'varchar',
		real: 'varchar',
		boolean: 'varchar',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'varchar',
		'date:string': 'varchar',
		datetime: 'varchar',
		'datetime:string': 'varchar',
		time: 'varchar',
		timestamp: 'varchar',
		'timestamp:string': 'varchar',
		year: 'varchar',
		json: 'text',
	},
	binary: {
		tinyint: 'binary',
		smallint: 'binary',
		mediumint: 'binary',
		int: 'binary',
		bigint: 'binary',
		'bigint:number': 'binary',
		'bigint:string': 'binary',
		serial: 'binary',
		decimal: 'binary',
		'decimal:number': 'binary',
		'decimal:bigint': 'binary',
		float: 'binary',
		double: 'binary',
		real: 'binary',
		boolean: 'binary',
		char: 'binary',
		varchar: 'varbinary',
		text: 'varbinary',
		enum: 'binary',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'binary',
		'date:string': 'binary',
		datetime: 'binary',
		'datetime:string': 'binary',
		time: 'binary',
		timestamp: 'binary',
		'timestamp:string': 'binary',
		year: 'binary',
		json: 'varbinary',
	},
	varbinary: {
		tinyint: 'varbinary',
		smallint: 'varbinary',
		mediumint: 'varbinary',
		int: 'varbinary',
		bigint: 'varbinary',
		'bigint:number': 'varbinary',
		'bigint:string': 'varbinary',
		serial: 'varbinary',
		decimal: 'varbinary',
		'decimal:number': 'varbinary',
		'decimal:bigint': 'varbinary',
		float: 'varbinary',
		double: 'varbinary',
		real: 'varbinary',
		boolean: 'varbinary',
		char: 'varbinary',
		varchar: 'varbinary',
		text: 'varbinary',
		enum: 'varbinary',
		binary: 'varbinary',
		varbinary: 'varbinary',
		date: 'varbinary',
		'date:string': 'varbinary',
		datetime: 'varbinary',
		'datetime:string': 'varbinary',
		time: 'varbinary',
		timestamp: 'varbinary',
		'timestamp:string': 'varbinary',
		year: 'varbinary',
		json: 'varbinary',
	},
	date: {
		tinyint: 'varchar',
		smallint: 'varchar',
		mediumint: 'varchar',
		int: 'varchar',
		bigint: 'varchar',
		'bigint:number': 'varchar',
		'bigint:string': 'varchar',
		serial: 'varchar',
		decimal: 'varchar',
		'decimal:number': 'varchar',
		'decimal:bigint': 'varchar',
		float: 'varchar',
		double: 'varchar',
		real: 'varchar',
		boolean: 'varchar',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'date',
		'date:string': 'date',
		datetime: 'datetime',
		'datetime:string': 'datetime',
		time: 'datetime',
		timestamp: 'datetime',
		'timestamp:string': 'datetime',
		year: 'varchar',
		json: 'text',
	},
	'date:string': {
		tinyint: 'varchar',
		smallint: 'varchar',
		mediumint: 'varchar',
		int: 'varchar',
		bigint: 'varchar',
		'bigint:number': 'varchar',
		'bigint:string': 'varchar',
		serial: 'varchar',
		decimal: 'varchar',
		'decimal:number': 'varchar',
		'decimal:bigint': 'varchar',
		float: 'varchar',
		double: 'varchar',
		real: 'varchar',
		boolean: 'varchar',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'date:string',
		'date:string': 'date:string',
		datetime: 'datetime:string',
		'datetime:string': 'datetime:string',
		time: 'datetime:string',
		timestamp: 'datetime:string',
		'timestamp:string': 'datetime:string',
		year: 'varchar',
		json: 'text',
	},
	datetime: {
		tinyint: 'varchar',
		smallint: 'varchar',
		mediumint: 'varchar',
		int: 'varchar',
		bigint: 'varchar',
		'bigint:number': 'varchar',
		'bigint:string': 'varchar',
		serial: 'varchar',
		decimal: 'varchar',
		'decimal:number': 'varchar',
		'decimal:bigint': 'varchar',
		float: 'varchar',
		double: 'varchar',
		real: 'varchar',
		boolean: 'varchar',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'datetime',
		'date:string': 'datetime',
		datetime: 'datetime',
		'datetime:string': 'datetime',
		time: 'datetime',
		timestamp: 'datetime',
		'timestamp:string': 'datetime',
		year: 'varchar',
		json: 'text',
	},
	'datetime:string': {
		tinyint: 'varchar',
		smallint: 'varchar',
		mediumint: 'varchar',
		int: 'varchar',
		bigint: 'varchar',
		'bigint:number': 'varchar',
		'bigint:string': 'varchar',
		serial: 'varchar',
		decimal: 'varchar',
		'decimal:number': 'varchar',
		'decimal:bigint': 'varchar',
		float: 'varchar',
		double: 'varchar',
		real: 'varchar',
		boolean: 'varchar',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'datetime:string',
		'date:string': 'datetime:string',
		datetime: 'datetime:string',
		'datetime:string': 'datetime:string',
		time: 'datetime:string',
		timestamp: 'datetime:string',
		'timestamp:string': 'datetime:string',
		year: 'varchar',
		json: 'text',
	},
	time: {
		tinyint: 'varchar',
		smallint: 'varchar',
		mediumint: 'varchar',
		int: 'varchar',
		bigint: 'varchar',
		'bigint:number': 'varchar',
		'bigint:string': 'varchar',
		serial: 'varchar',
		decimal: 'varchar',
		'decimal:number': 'varchar',
		'decimal:bigint': 'varchar',
		float: 'varchar',
		double: 'varchar',
		real: 'varchar',
		boolean: 'varchar',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'datetime:string',
		'date:string': 'datetime:string',
		datetime: 'datetime:string',
		'datetime:string': 'datetime:string',
		time: 'time',
		timestamp: 'datetime:string',
		'timestamp:string': 'datetime:string',
		year: 'varchar',
		json: 'text',
	},
	timestamp: {
		tinyint: 'varchar',
		smallint: 'varchar',
		mediumint: 'varchar',
		int: 'varchar',
		bigint: 'varchar',
		'bigint:number': 'varchar',
		'bigint:string': 'varchar',
		serial: 'varchar',
		decimal: 'varchar',
		'decimal:number': 'varchar',
		'decimal:bigint': 'varchar',
		float: 'varchar',
		double: 'varchar',
		real: 'varchar',
		boolean: 'varchar',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'datetime',
		'date:string': 'datetime',
		datetime: 'datetime',
		'datetime:string': 'datetime',
		time: 'datetime',
		timestamp: 'timestamp',
		'timestamp:string': 'timestamp',
		year: 'varchar',
		json: 'text',
	},
	'timestamp:string': {
		tinyint: 'varchar',
		smallint: 'varchar',
		mediumint: 'varchar',
		int: 'varchar',
		bigint: 'varchar',
		'bigint:number': 'varchar',
		'bigint:string': 'varchar',
		serial: 'varchar',
		decimal: 'varchar',
		'decimal:number': 'varchar',
		'decimal:bigint': 'varchar',
		float: 'varchar',
		double: 'varchar',
		real: 'varchar',
		boolean: 'varchar',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'datetime:string',
		'date:string': 'datetime:string',
		datetime: 'datetime:string',
		'datetime:string': 'datetime:string',
		time: 'datetime:string',
		timestamp: 'timestamp:string',
		'timestamp:string': 'timestamp:string',
		year: 'varchar',
		json: 'text',
	},
	year: {
		tinyint: 'int',
		smallint: 'int',
		mediumint: 'int',
		int: 'int',
		bigint: 'bigint:number',
		'bigint:number': 'bigint:number',
		'bigint:string': 'bigint:number',
		serial: 'bigint:number',
		decimal: 'decimal:number',
		'decimal:number': 'decimal:number',
		'decimal:bigint': 'decimal:number',
		float: 'float',
		double: 'double',
		real: 'double',
		boolean: 'int',
		char: 'char',
		varchar: 'varchar',
		text: 'text',
		enum: 'varchar',
		binary: 'binary',
		varbinary: 'varbinary',
		date: 'varchar',
		'date:string': 'varchar',
		datetime: 'varchar',
		'datetime:string': 'varchar',
		time: 'varchar',
		timestamp: 'varchar',
		'timestamp:string': 'varchar',
		year: 'year',
		json: 'text',
	},
	json: {
		tinyint: 'text',
		smallint: 'text',
		mediumint: 'text',
		int: 'text',
		bigint: 'text',
		'bigint:number': 'text',
		'bigint:string': 'text',
		serial: 'text',
		decimal: 'text',
		'decimal:number': 'text',
		'decimal:bigint': 'text',
		float: 'text',
		double: 'text',
		real: 'text',
		boolean: 'text',
		char: 'text',
		varchar: 'text',
		text: 'text',
		enum: 'text',
		binary: 'varbinary',
		varbinary: 'varbinary',
		date: 'text',
		'date:string': 'text',
		datetime: 'text',
		'datetime:string': 'text',
		time: 'text',
		timestamp: 'text',
		'timestamp:string': 'text',
		year: 'text',
		json: 'json',
	},
	vector_i8: { vector_i8: 'vector_i8' },
	vector_i16: { vector_i16: 'vector_i16' },
	vector_i32: { vector_i32: 'vector_i32' },
	vector_i64: { vector_i64: 'vector_i64' },
	vector_f32: { vector_f32: 'vector_f32' },
	vector_f64: { vector_f64: 'vector_f64' },
} as const satisfies Partial<Record<SingleStoreType, Partial<Record<SingleStoreType, SingleStoreType>>>>;

export function resolveUnionType(left: SingleStoreType, right: SingleStoreType): SingleStoreType | undefined {
	return (unionsTypeTable as Record<string, Record<string, SingleStoreType> | undefined>)[left]?.[right];
}
