import { 
	singlestoreTable, 
	bigint, 
	int,
	tinyint,
	smallint,
	mediumint,
	real,
	decimal,
	double,
	float,
	serial,
	binary,
	varbinary,
	char,
	varchar,
	text,
	boolean,
	date,
	datetime,
	time,
	year,
	timestamp,
	json,
	singlestoreEnum,
	vector
} from 'drizzle-orm/singlestore-core';

// SingleStore enum example
export const popularityEnum = singlestoreEnum('popularity', ['unknown', 'known', 'popular']);

export const allDataTypes = singlestoreTable('all_data_types', {
	integer: int('integer'),
	tinyint: tinyint('tinyint'),
	smallint: smallint('smallint'),
	mediumint: mediumint('mediumint'),
	bigint: bigint('bigint', { mode: 'bigint' }),
	bigintNumber: bigint('bigint_number', { mode: 'number' }),
	real: real('real'),
	decimal: decimal('decimal'),
	double: double('double'),
	float: float('float'),
	serial: serial('serial').autoincrement(),
	binary: binary('binary', { length: 255 }),
	varbinary: varbinary('varbinary', { length: 256 }),
	char: char('char', { length: 255 }),
	varchar: varchar('varchar', { length: 256 }),
	text: text('text'),
	boolean: boolean('boolean'),
	dateString: date('date_string', { mode: 'string' }),
	date: date('date', { mode: 'date' }),
	datetime: datetime('datetime', { mode: 'date' }),
	datetimeString: datetime('datetimeString', { mode: 'string' }),
	time: time('time'),
	year: year('year'),
	timestampDate: timestamp('timestamp_date', { mode: 'date' }),
	timestampString: timestamp('timestamp_string', { mode: 'string' }),
	json: json('json'),
	popularity: popularityEnum.default('unknown'),
	// SingleStore-specific: Vector columns for AI/ML
	embedding: vector('embedding', { dimensions: 1536 }),
	smallEmbedding: vector('small_embedding', { dimensions: 512 }),
});
