import {
	bigint,
	binary,
	boolean,
	char,
	date,
	datetime,
	decimal,
	double,
	float,
	int,
	json,
	longtext,
	mediumint,
	mediumtext,
	real,
	serial,
	singlestoreEnum,
	singlestoreTable,
	smallint,
	text,
	time,
	timestamp,
	tinyint,
	tinytext,
	varbinary,
	varchar,
	vector,
	year,
} from 'drizzle-orm/singlestore-core';

export const allDataTypes = singlestoreTable('all_data_types', {
	int: int('int'),
	tinyint: tinyint('tinyint'),
	smallint: smallint('smallint'),
	mediumint: mediumint('mediumint'),
	biginteger: bigint('bigint', { mode: 'bigint' }),
	bigintNumber: bigint('bigint_number', { mode: 'number' }),
	real: real('real'),
	decimal: decimal('decimal'),
	double: double('double'),
	float: float('float'),
	serial: serial('serial'),
	binary: binary('binary', { length: 255 }),
	varbinary: varbinary('varbinary', { length: 256 }),
	char: char('char', { length: 255 }),
	varchar: varchar('varchar', { length: 256 }),
	tinytext: tinytext('tinytext'),
	mediumtext: mediumtext('mediumtext'),
	longtext: longtext('longtext'),
	text: text('text'),
	boolean: boolean('boolean'),
	dateString: date('date_string', { mode: 'string' }),
	date: date('date', { mode: 'date' }),
	datetime: datetime('datetime', { mode: 'date' }),
	datetimeString: datetime('datetimeString', { mode: 'string' }),
	time: time('time'),
	year: year('year'),
	timestampDate: timestamp('timestamp_date', { mode: 'date' }),
	timestampString: timestamp('timestamp_string', { mode: 'string' }),
	json: json('json'),
	mysqlEnum: singlestoreEnum('popularity', ['unknown', 'known', 'popular']),
	vectorF32: vector('vector_f32', { dimensions: 12, elementType: 'F32' }),
	vectorF64: vector('vector_f64', { dimensions: 12, elementType: 'F64' }),
	vectorI8: vector('vector_i8', { dimensions: 12, elementType: 'I8' }),
	vectorI16: vector('vector_i16', { dimensions: 12, elementType: 'I16' }),
	vectorI32: vector('vector_i32', { dimensions: 12, elementType: 'I32' }),
	vectorI64: vector('vector_i64', { dimensions: 12, elementType: 'I64' }),
});
