root: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:unicorn/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
plugins:
  - import
  - unused-imports
  - no-instanceof
  - drizzle-internal
overrides:
  - files:
      - '**/tests/**/*.ts'
      - '**/type-tests/**/*.ts'
    rules:
      import/extensions: 'off'
      no-instanceof: 'off'
  - files: 'eslint-plugin-drizzle/**/*'
    rules:
      import/extensions: 'off'
rules:
  '@typescript-eslint/consistent-type-imports':
    - error
    - disallowTypeAnnotations: false
      fixStyle: separate-type-imports
  '@typescript-eslint/no-import-type-side-effects': 'error'
  import/no-cycle: error
  import/no-self-import: error
  import/no-empty-named-blocks: error
  unused-imports/no-unused-imports: error
  import/no-useless-path-segments: error
  import/newline-after-import: error
  import/no-duplicates: error
  import/extensions:
    - error
    - always
    - ignorePackages: true
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/no-non-null-assertion': 'off'
  '@typescript-eslint/no-namespace': 'off'
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
  '@typescript-eslint/ban-types':
    - error
    - extendDefaults: true
      types:
        '{}' : false
  '@typescript-eslint/no-this-alias': 'off'
  '@typescript-eslint/no-var-requires': 'off'
  'unicorn/prefer-node-protocol': 'off'
  'unicorn/prefer-top-level-await': 'off'
  'unicorn/prevent-abbreviations': 'off'
  'unicorn/prefer-switch': 'off'
  'unicorn/catch-error-name': 'off'
  'unicorn/no-null': 'off'
  'unicorn/numeric-separators-style': 'off'
  'unicorn/explicit-length-check': 'off'
  'unicorn/filename-case': 'off'
  'unicorn/prefer-module': 'off'
  'unicorn/no-array-reduce': 'off'
  'unicorn/no-nested-ternary': 'off'
  'unicorn/no-useless-undefined':
    - error
    - checkArguments: false
  'unicorn/no-this-assignment': 'off'
  'unicorn/empty-brace-spaces': 'off'
  'unicorn/no-thenable': 'off'
  'unicorn/consistent-function-scoping': 'off'
  'unicorn/prefer-type-error': 'off'
  'unicorn/relative-url-style': 'off'
  'eqeqeq': 'error'
  'no-instanceof/no-instanceof': 'error'
  'drizzle-internal/require-entity-kind': 'error'
  'unicorn/prefer-string-replace-all': 'off'
  'unicorn/no-process-exit': 'off'
  '@typescript-eslint/ban-ts-comment': 'off'
  '@typescript-eslint/no-empty-interface': 'off'
  '@typescript-eslint/no-unsafe-declaration-merging': 'off'
  'no-inner-declarations': 'off'
