[files]
extend-exclude = [
    ".git/",
    "drizzle-kit/src/utils/words.ts",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "'BOTTM',",
]

[default.extend-words]
"splitted" = "splitted"

[default.extend-identifiers]
# Typos
"Github" = "GitHub"
