import {
	bigint,
	binary,
	boolean,
	char,
	date,
	datetime,
	decimal,
	double,
	float,
	int,
	json,
	mediumint,
	mysqlEnum,
	mysqlTable,
	real,
	serial,
	smallint,
	text,
	time,
	timestamp,
	tinyint,
	varbinary,
	varchar,
	year,
} from 'drizzle-orm/mysql-core';

export const allDataTypes = mysqlTable('all_data_types', {
	int: int('integer'),
	intUnsigned: int('integer_unsigned', { unsigned: true }),
	tinyint: tinyint('tinyint'),
	tinyintUnsigned: tinyint('tinyint_unsigned', { unsigned: true }),
	smallint: smallint('smallint'),
	smallintUnsigned: smallint('smallint_unsigned', { unsigned: true }),
	mediumint: mediumint('mediumint'),
	mediumintUnsigned: mediumint('mediumint_unsigned', { unsigned: true }),
	biginteger: bigint('bigint', { mode: 'bigint' }),
	bigintegerUnsigned: bigint('bigint_unsigned', { mode: 'bigint', unsigned: true }),
	bigintNumber: bigint('bigint_number', { mode: 'number' }),
	bigintNumberUnsigned: bigint('bigint_number_unsigned', { mode: 'number', unsigned: true }),
	real: real('real'),
	decimal: decimal('decimal'),
	decimalUnsigned: decimal('decimal_unsigned', { unsigned: true }),
	double: double('double'),
	doubleUnsigned: double('double_unsigned', { unsigned: true }),
	float: float('float'),
	floatUnsigned: float('float_unsigned', { unsigned: true }),
	serial: serial('serial'),
	binary: binary('binary', { length: 255 }),
	varbinary: varbinary('varbinary', { length: 256 }),
	char: char('char', { length: 255 }),
	varchar: varchar('varchar', { length: 256 }),
	text: text('text'),
	boolean: boolean('boolean'),
	dateString: date('date_string', { mode: 'string' }),
	date: date('date', { mode: 'date' }),
	datetime: datetime('datetime', { mode: 'date' }),
	datetimeString: datetime('datetimeString', { mode: 'string' }),
	time: time('time'),
	year: year('year'),
	timestampDate: timestamp('timestamp_date', { mode: 'date' }),
	timestampString: timestamp('timestamp_string', { mode: 'string' }),
	json: json('json'),
	mysqlEnum: mysqlEnum('popularity', ['unknown', 'known', 'popular']),
});
