import { makePgArray, parsePgArray } from '~/pg-core/array.ts';
import {
	arrayCompatNormalize,
	arrayCompatNormalizeInput,
	castToText,
	castToTextArr,
	makeBoxArray,
	makeGeometryArray,
	parseGeometryArrayAndNormalize,
	parseGeometryTuple,
	parseGeometryXY,
	parseLineABC,
	parseLineTuple,
	parsePgArrayAndNormalize,
	parsePgVector,
	parsePointTuple,
	parsePointXY,
	refineGenericPgCodecs,
	textToDate,
	textToDateWithTz,
} from '~/pg-core/codecs.ts';

export const xataHttpCodecs = refineGenericPgCodecs({
	bigint: {
		normalize: BigInt,
		normalizeArray: arrayCompatNormalize(BigInt),
		normalizeParamArray: (v) => makePgArray(v),
	},
	bigserial: {
		normalize: BigInt,
		normalizeArray: arrayCompatNormalize(BigInt),
		normalizeParamArray: (v) => makePgArray(v),
	},
	bit: {
		normalizeArray: (v) => parsePgArray(v),
		normalizeParamArray: (v) => makePgArray(v),
	},
	json: {
		castParam: (name) => `${name}::json`,
		normalizeParamArray: arrayCompatNormalizeInput((v) => JSON.stringify(v), true),
	},
	jsonb: {
		castParam: (name) => `${name}::jsonb`,
		normalizeParamArray: arrayCompatNormalizeInput((v) => JSON.stringify(v), true),
	},
	interval: {
		castArray: castToTextArr,
		normalizeParamArray: (v) => makePgArray(v),
	},
	point: {
		cast: castToText,
		castArray: castToTextArr,
		normalize: parsePointXY,
		normalizeArray: arrayCompatNormalize(parsePointXY),
		normalizeParamArray: (v) => makePgArray(v),
	},
	'point:tuple': {
		cast: castToText,
		castArray: castToTextArr,
		normalize: parsePointTuple,
		normalizeArray: arrayCompatNormalize(parsePointTuple),
		normalizeParamArray: (v) => makePgArray(v),
	},
	line: {
		cast: castToText,
		castArray: castToTextArr,
		normalize: parseLineABC,
		normalizeArray: arrayCompatNormalize(parseLineABC),
		normalizeParamArray: (v) => makePgArray(v),
	},
	'line:tuple': {
		cast: castToText,
		castArray: castToTextArr,
		normalize: parseLineTuple,
		normalizeArray: arrayCompatNormalize(parseLineTuple),
		normalizeParamArray: (v) => makePgArray(v),
	},
	macaddr8: {
		castArrayInJson: castToTextArr,
		castArray: castToTextArr,
		normalizeParamArray: (v) => makePgArray(v),
	},
	bool: { normalizeParamArray: (v) => makePgArray(v) },
	box: { normalizeParamArray: makeBoxArray },
	box2d: { normalizeParamArray: (v) => makePgArray(v) },
	box3d: { normalizeParamArray: (v) => makePgArray(v) },
	char: { normalizeParamArray: (v) => makePgArray(v) },
	cidr: { normalizeParamArray: (v) => makePgArray(v) },
	circle: { normalizeParamArray: (v) => makePgArray(v) },
	datemultirange: { normalizeParamArray: (v) => makePgArray(v) },
	daterange: { normalizeParamArray: (v) => makePgArray(v) },
	float8: { normalizeParamArray: (v) => makePgArray(v) },
	'geography(point)': { normalizeParamArray: makeGeometryArray },
	'geography(point):tuple': { normalizeParamArray: makeGeometryArray },
	inet: { normalizeParamArray: (v) => makePgArray(v) },
	int4multirange: { normalizeParamArray: (v) => makePgArray(v) },
	int4range: { normalizeParamArray: (v) => makePgArray(v) },
	int8multirange: { normalizeParamArray: (v) => makePgArray(v) },
	int8range: { normalizeParamArray: (v) => makePgArray(v) },
	lseg: { normalizeParamArray: (v) => makePgArray(v) },
	macaddr: { normalizeParamArray: (v) => makePgArray(v) },
	money: { normalizeParamArray: (v) => makePgArray(v) },
	nummultirange: { normalizeParamArray: (v) => makePgArray(v) },
	numrange: { normalizeParamArray: (v) => makePgArray(v) },
	oid: { normalizeParamArray: (v) => makePgArray(v) },
	path: { normalizeParamArray: (v) => makePgArray(v) },
	polygon: { normalizeParamArray: (v) => makePgArray(v) },
	raster: { normalizeParamArray: (v) => makePgArray(v) },
	regclass: { normalizeParamArray: (v) => makePgArray(v) },
	regconfig: { normalizeParamArray: (v) => makePgArray(v) },
	regdictionary: { normalizeParamArray: (v) => makePgArray(v) },
	regnamespace: { normalizeParamArray: (v) => makePgArray(v) },
	regoper: { normalizeParamArray: (v) => makePgArray(v) },
	regoperator: { normalizeParamArray: (v) => makePgArray(v) },
	regproc: { normalizeParamArray: (v) => makePgArray(v) },
	regprocedure: { normalizeParamArray: (v) => makePgArray(v) },
	regrole: { normalizeParamArray: (v) => makePgArray(v) },
	regtype: { normalizeParamArray: (v) => makePgArray(v) },
	serial: { normalizeParamArray: (v) => makePgArray(v) },
	smallint: { normalizeParamArray: (v) => makePgArray(v) },
	smallserial: { normalizeParamArray: (v) => makePgArray(v) },
	text: { normalizeParamArray: (v) => makePgArray(v) },
	time: { normalizeParamArray: (v) => makePgArray(v) },
	timetz: { normalizeParamArray: (v) => makePgArray(v) },
	tsmultirange: { normalizeParamArray: (v) => makePgArray(v) },
	tsquery: { normalizeParamArray: (v) => makePgArray(v) },
	tsrange: { normalizeParamArray: (v) => makePgArray(v) },
	tstzmultirange: { normalizeParamArray: (v) => makePgArray(v) },
	tstzrange: { normalizeParamArray: (v) => makePgArray(v) },
	tsvector: { normalizeParamArray: (v) => makePgArray(v) },
	varbit: { normalizeParamArray: (v) => makePgArray(v) },
	varchar: { normalizeParamArray: (v) => makePgArray(v) },
	xml: { normalizeParamArray: (v) => makePgArray(v) },
	bytea: { normalizeParamArray: (v) => makePgArray(v) },
	enum: {
		castArray: castToTextArr,
		normalizeParamArray: (v) => makePgArray(v),
	},
	'geometry(point)': {
		normalize: parseGeometryXY,
		normalizeArray: parseGeometryArrayAndNormalize(parseGeometryXY),
		normalizeParamArray: makeGeometryArray,
	},
	'geometry(point):tuple': {
		normalize: parseGeometryTuple,
		normalizeArray: parseGeometryArrayAndNormalize(parseGeometryTuple),
		normalizeParamArray: makeGeometryArray,
	},
	numeric: {
		castArray: castToTextArr,
		normalizeParamArray: (v) => makePgArray(v),
	},
	'numeric:number': {
		castArray: castToTextArr,
		normalize: Number,
		normalizeArray: arrayCompatNormalize(Number),
		normalizeParamArray: (v) => makePgArray(v),
	},
	'numeric:bigint': {
		castArray: castToTextArr,
		normalize: BigInt,
		normalizeArray: arrayCompatNormalize(BigInt),
		normalizeParamArray: (v) => makePgArray(v),
	},
	'bigint:number': {
		normalize: Number,
		normalizeArray: arrayCompatNormalize(Number),
		normalizeParamArray: (v) => makePgArray(v),
	},
	'bigint:string': { normalizeParamArray: (v) => makePgArray(v) },
	'bigserial:number': {
		normalize: Number,
		normalizeArray: arrayCompatNormalize(Number),
		normalizeParamArray: (v) => makePgArray(v),
	},
	float4: { normalizeParamArray: (v) => makePgArray(v) },
	int: { normalizeParamArray: (v) => makePgArray(v) },
	uuid: { normalizeParamArray: (v) => makePgArray(v) },
	date: {
		castArray: castToTextArr,
		normalize: textToDate,
		normalizeArray: arrayCompatNormalize(textToDate),
		normalizeParamArray: (v) => makePgArray(v),
	},
	'date:string': {
		castArray: castToTextArr,
		normalizeParamArray: (v) => makePgArray(v),
	},
	timestamp: {
		castArray: castToTextArr,
		normalize: textToDateWithTz,
		normalizeArray: arrayCompatNormalize(textToDateWithTz),
		normalizeParamArray: (v) => makePgArray(v),
	},
	timestamptz: {
		castArray: castToTextArr,
		normalize: textToDate,
		normalizeArray: arrayCompatNormalize(textToDate),
		normalizeParamArray: (v) => makePgArray(v),
	},
	'timestamp:string': {
		castArray: castToTextArr,
		normalizeParamArray: (v) => makePgArray(v),
	},
	'timestamptz:string': {
		castArray: castToTextArr,
		normalizeParamArray: (v) => makePgArray(v),
	},
	halfvec: {
		normalize: parsePgVector,
		normalizeArray: parsePgArrayAndNormalize(parsePgVector),
		normalizeParamArray: (v) => makePgArray(v),
	},
	sparsevec: {
		normalizeArray: (v) => parsePgArray(v),
		normalizeParamArray: (v) => makePgArray(v),
	},
	vector: {
		normalize: parsePgVector,
		normalizeArray: parsePgArrayAndNormalize(parsePgVector),
		normalizeParamArray: (v) => makePgArray(v),
	},
});
