import { DrizzleError } from '~/errors.ts';
import { type MigratorInitFailResponse, readMigrationFiles } from '~/migrator.ts';
import { getMigrationsToRun } from '~/migrator.utils.ts';
import type { AnyRelations, EmptyRelations } from '~/relations.ts';
import { sql } from '~/sql/sql.ts';
import { upgradeIfNeeded } from '~/up-migrations/pg.ts';
import type { XataHttpDatabase } from './driver.ts';

export interface MigrationConfig {
	migrationsFolder: string;
	migrationsTable?: string;
	/** @internal */
	init?: boolean;
}

/**
 * This function reads migrationFolder and execute each unapplied migration and mark it as executed in database
 *
 * NOTE: The Xata HTTP driver does not support transactions. This means that if any part of a migration fails,
 * no rollback will be executed. Currently, you will need to handle unsuccessful migration yourself.
 * @param db - drizzle db instance
 * @param config - path to migration folder generated by drizzle-kit
 */ export async function migrate<
	TSchema extends Record<string, unknown>,
	TRelations extends AnyRelations = EmptyRelations,
>(
	db: XataHttpDatabase<TSchema, TRelations>,
	config: MigrationConfig,
): Promise<void | MigratorInitFailResponse> {
	const migrations = readMigrationFiles(config);
	const migrationsTable = config.migrationsTable ?? '__drizzle_migrations';

	// Detect DB version and upgrade table schema if needed
	const { newDb } = await upgradeIfNeeded('public', migrationsTable, db, migrations, 'execute');

	if (newDb) {
		const migrationTableCreate = sql`
		CREATE TABLE IF NOT EXISTS ${sql.identifier(migrationsTable)} (
			id SERIAL PRIMARY KEY,
			hash text NOT NULL,
			created_at bigint,
			name text,
			applied_at timestamp with time zone DEFAULT now()
		)
	`;
		await db.session.execute(migrationTableCreate);
	}

	const dbMigrations = await db.session.all<{
		id: number;
		hash: string;
		created_at: string;
		name: string | null;
	}>(
		sql`select id, hash, created_at, name from ${sql.identifier(migrationsTable)}`,
	);

	if (typeof config === 'object' && config.init) {
		if (dbMigrations.length) {
			return { exitCode: 'databaseMigrations' as const };
		}

		if (migrations.length > 1) {
			return { exitCode: 'localMigrations' as const };
		}

		const [migration] = migrations;

		if (!migration) return;

		await db.session.execute(
			sql`insert into ${
				sql.identifier(migrationsTable)
			} ("hash", "created_at", "name") values(${migration.hash}, ${migration.folderMillis}, ${migration.name})`,
		);

		return;
	}

	const migrationsToRun = getMigrationsToRun({ localMigrations: migrations, dbMigrations });
	for await (const migration of migrationsToRun) {
		for (const stmt of migration.sql) {
			await db.session.execute(sql.raw(stmt));
		}

		await db.session.execute(
			sql`insert into ${
				sql.identifier(migrationsTable)
			} ("hash", "created_at", "name") values(${migration.hash}, ${migration.folderMillis}, ${migration.name})`,
		);
	}
}

export async function rollback<TSchema extends Record<string, unknown>, TRelations extends AnyRelations>(
	db: XataHttpDatabase<TSchema, TRelations>,
	config: MigrationConfig,
	steps: number = 1,
) {
	const migrations = readMigrationFiles(config);
	const migrationsTable = config.migrationsTable ?? '__drizzle_migrations';

	const dbMigrations = await db.session.all<{ id: number; hash: string; name: string | null }>(
		sql`select id, hash, name from ${sql.identifier(migrationsTable)} order by id desc limit ${sql.raw(String(steps))}`,
	);

	if (dbMigrations.length === 0) return;

	for (const dbMigration of dbMigrations) {
		const meta = migrations.find((m) => m.hash === dbMigration.hash && (!dbMigration.name || m.name === dbMigration.name));
		if (!meta) {
			throw new DrizzleError({ message: `Cannot rollback migration with hash ${dbMigration.hash}: migration file not found` });
		}
		if (!meta.downSql || meta.downSql.length === 0) {
			throw new DrizzleError({ message: `Cannot rollback migration ${dbMigration.hash}: no down SQL available.` });
		}
		for (const stmt of [...meta.downSql].reverse()) {
			await db.session.execute(sql.raw(stmt));
		}
		await db.session.execute(sql`delete from ${sql.identifier(migrationsTable)} where id = ${dbMigration.id}`);
	}
}
