import { bigint, int, mssqlTable, varchar } from '~/mssql-core/index.ts';

mssqlTable('test', {
	col0: int('col1').primaryKey().identity(),
	col1: int('col1').primaryKey().identity(),
	col2: int('col1').primaryKey().identity(),
	col3: int('col1').primaryKey().identity(),
	col4: int('col1').primaryKey().identity(),
	col5: int('col1').primaryKey().identity(),
	col6: int('col1').primaryKey().identity(),
	col8: int('col1').primaryKey().identity(),
	col9: int('col1').primaryKey().identity(),
	col10: int('col1').primaryKey().identity(),
	col11: int('col1').primaryKey().identity(),
	col12: int('col1').primaryKey().identity(),
	col13: int('col1').primaryKey().identity(),
	col14: int('col1').primaryKey().identity(),
	col15: int('col1').primaryKey().identity(),
	col16: int('col1').primaryKey().identity(),
	col18: int('col1').primaryKey().identity(),
	col19: int('col1').primaryKey().identity(),
	col20: int('col1').primaryKey().identity(),
	col21: int('col1').primaryKey().identity(),
	col22: int('col1').primaryKey().identity(),
	col23: int('col1').primaryKey().identity(),
	col24: int('col1').primaryKey().identity(),
	col25: int('col1').primaryKey().identity(),
	col26: int('col1').primaryKey().identity(),
	col28: int('col1').primaryKey().identity(),
	col29: int('col1').primaryKey().identity(),
	col30: int('col1').primaryKey().identity(),
	col31: int('col1').primaryKey().identity(),
	col32: int('col1').primaryKey().identity(),
	col33: int('col1').primaryKey().identity(),
	col34: int('col1').primaryKey().identity(),
	col35: int('col1').primaryKey().identity(),
	col36: int('col1').primaryKey().identity(),
	col38: int('col1').primaryKey().identity(),
	col39: int('col1').primaryKey().identity(),
	col40: int('col1').primaryKey().identity(),
	col41: int('col1').primaryKey().identity(),
	col42: int('col1').primaryKey().identity(),
	col43: int('col1').primaryKey().identity(),
	col44: int('col1').primaryKey().identity(),
	col45: int('col1').primaryKey().identity(),
	col46: int('col1').primaryKey().identity(),
	col48: int('col1').primaryKey().identity(),
	col49: int('col1').primaryKey().identity(),
	col50: int('col1').primaryKey().identity(),
	col51: int('col1').primaryKey().identity(),
	col52: int('col1').primaryKey().identity(),
	col53: int('col1').primaryKey().identity(),
	col54: int('col1').primaryKey().identity(),
	col55: int('col1').primaryKey().identity(),
	col56: int('col1').primaryKey().identity(),
	col58: int('col1').primaryKey().identity(),
	col59: int('col1').primaryKey().identity(),
	col60: int('col1').primaryKey().identity(),
	col61: int('col1').primaryKey().identity(),
	col62: int('col1').primaryKey().identity(),
	col63: int('col1').primaryKey().identity(),
	col64: int('col1').primaryKey().identity(),
	col65: int('col1').primaryKey().identity(),
	col66: int('col1').primaryKey().identity(),
	col68: int('col1').primaryKey().identity(),
	col69: int('col1').primaryKey().identity(),
	col70: int('col1').primaryKey().identity(),
	col71: int('col1').primaryKey().identity(),
	col72: int('col1').primaryKey().identity(),
	col73: int('col1').primaryKey().identity(),
	col74: int('col1').primaryKey().identity(),
	col75: int('col1').primaryKey().identity(),
	col76: int('col1').primaryKey().identity(),
	col78: int('col1').primaryKey().identity(),
	col79: int('col1').primaryKey().identity(),
	col80: int('col1').primaryKey().identity(),
	col81: int('col1').primaryKey().identity(),
	col82: int('col1').primaryKey().identity(),
	col83: int('col1').primaryKey().identity(),
	col84: int('col1').primaryKey().identity(),
	col85: int('col1').primaryKey().identity(),
	col86: int('col1').primaryKey().identity(),
	col88: int('col1').primaryKey().identity(),
	col89: int('col1').primaryKey().identity(),
	col90: int('col1').primaryKey().identity(),
	col91: int('col1').primaryKey().identity(),
	col92: int('col1').primaryKey().identity(),
	col93: int('col1').primaryKey().identity(),
	col94: int('col1').primaryKey().identity(),
	col95: int('col1').primaryKey().identity(),
	col96: int('col1').primaryKey().identity(),
	col98: int('col1').primaryKey().identity(),
	col99: int('col1').primaryKey().identity(),
	col100: int('col1').primaryKey().identity(),
	col101: int('col1').primaryKey().identity(),
	col102: int('col1').primaryKey().identity(),
	col103: int('col1').primaryKey().identity(),
	col104: int('col1').primaryKey().identity(),
	col105: int('col1').primaryKey().identity(),
	col106: int('col1').primaryKey().identity(),
	col108: int('col1').primaryKey().identity(),
	col109: int('col1').primaryKey().identity(),
	col110: int('col11').primaryKey().identity(),
	col111: int('col11').primaryKey().identity(),
	col112: int('col11').primaryKey().identity(),
	col113: int('col11').primaryKey().identity(),
	col114: int('col11').primaryKey().identity(),
	col115: int('col11').primaryKey().identity(),
	col116: int('col11').primaryKey().identity(),
	col118: int('col11').primaryKey().identity(),
	col119: int('col11').primaryKey().identity(),
	col120: int('col11').primaryKey().identity(),
	col121: int('col11').primaryKey().identity(),
	col122: int('col11').primaryKey().identity(),
	col123: int('col11').primaryKey().identity(),
	col124: int('col11').primaryKey().identity(),
	col125: int('col11').primaryKey().identity(),
	col126: int('col11').primaryKey().identity(),
	col128: int('col11').primaryKey().identity(),
	col129: int('col11').primaryKey().identity(),
	col130: int('col11').primaryKey().identity(),
	col131: int('col11').primaryKey().identity(),
	col132: int('col11').primaryKey().identity(),
	col133: int('col11').primaryKey().identity(),
	col134: int('col11').primaryKey().identity(),
	col135: int('col11').primaryKey().identity(),
	col136: int('col11').primaryKey().identity(),
	col138: int('col11').primaryKey().identity(),
	col139: int('col11').primaryKey().identity(),
	col140: int('col11').primaryKey().identity(),
	col141: int('col11').primaryKey().identity(),
	col142: int('col11').primaryKey().identity(),
	col143: int('col11').primaryKey().identity(),
	col144: int('col11').primaryKey().identity(),
	col145: int('col11').primaryKey().identity(),
	col146: int('col11').primaryKey().identity(),
	col148: int('col11').primaryKey().identity(),
	col149: int('col11').primaryKey().identity(),
	col150: int('col11').primaryKey().identity(),
	col151: int('col11').primaryKey().identity(),
	col152: int('col11').primaryKey().identity(),
	col153: int('col11').primaryKey().identity(),
	col154: int('col11').primaryKey().identity(),
	col155: int('col11').primaryKey().identity(),
	col156: int('col11').primaryKey().identity(),
	col158: int('col11').primaryKey().identity(),
	col159: int('col11').primaryKey().identity(),
	col160: int('col11').primaryKey().identity(),
	col161: int('col11').primaryKey().identity(),
	col162: int('col11').primaryKey().identity(),
	col163: int('col11').primaryKey().identity(),
	col164: int('col11').primaryKey().identity(),
	col165: int('col11').primaryKey().identity(),
	col166: int('col11').primaryKey().identity(),
	col168: int('col11').primaryKey().identity(),
	col169: int('col11').primaryKey().identity(),
	col170: int('col11').primaryKey().identity(),
	col171: int('col11').primaryKey().identity(),
	col172: int('col11').primaryKey().identity(),
	col173: int('col11').primaryKey().identity(),
	col174: int('col11').primaryKey().identity(),
	col175: int('col11').primaryKey().identity(),
	col176: int('col11').primaryKey().identity(),
	col178: int('col11').primaryKey().identity(),
	col179: int('col11').primaryKey().identity(),
	col180: int('col11').primaryKey().identity(),
	col181: int('col11').primaryKey().identity(),
	col182: int('col11').primaryKey().identity(),
	col183: int('col11').primaryKey().identity(),
	col184: int('col11').primaryKey().identity(),
	col185: int('col11').primaryKey().identity(),
	col186: int('col11').primaryKey().identity(),
	col188: int('col11').primaryKey().identity(),
	col189: int('col11').primaryKey().identity(),
	col190: int('col11').primaryKey().identity(),
	col191: int('col11').primaryKey().identity(),
	col192: int('col11').primaryKey().identity(),
	col193: int('col11').primaryKey().identity(),
	col194: int('col11').primaryKey().identity(),
	col195: int('col11').primaryKey().identity(),
	col196: int('col11').primaryKey().identity(),
	col198: int('col11').primaryKey().identity(),
	col199: int('col11').primaryKey().identity(),
	col200: int('col2').primaryKey().identity(),
	col201: int('col2').primaryKey().identity(),
	col202: int('col2').primaryKey().identity(),
	col203: int('col2').primaryKey().identity(),
	col204: int('col2').primaryKey().identity(),
	col205: int('col2').primaryKey().identity(),
	col206: int('col2').primaryKey().identity(),
	col208: int('col2').primaryKey().identity(),
	col209: int('col2').primaryKey().identity(),
	col210: int('col21').primaryKey().identity(),
	col211: int('col21').primaryKey().identity(),
	col212: int('col21').primaryKey().identity(),
	col213: int('col21').primaryKey().identity(),
	col214: int('col21').primaryKey().identity(),
	col215: int('col21').primaryKey().identity(),
	col216: int('col21').primaryKey().identity(),
	col218: int('col21').primaryKey().identity(),
	col219: int('col21').primaryKey().identity(),
	col220: int('col21').primaryKey().identity(),
	col221: int('col21').primaryKey().identity(),
	col222: int('col21').primaryKey().identity(),
	col223: int('col21').primaryKey().identity(),
	col224: int('col21').primaryKey().identity(),
	col225: int('col21').primaryKey().identity(),
	col226: int('col21').primaryKey().identity(),
	col228: int('col21').primaryKey().identity(),
	col229: int('col21').primaryKey().identity(),
	col230: int('col21').primaryKey().identity(),
	col231: int('col21').primaryKey().identity(),
	col232: int('col21').primaryKey().identity(),
	col233: int('col21').primaryKey().identity(),
	col234: int('col21').primaryKey().identity(),
	col235: int('col21').primaryKey().identity(),
	col236: int('col21').primaryKey().identity(),
	col238: int('col21').primaryKey().identity(),
	col239: int('col21').primaryKey().identity(),
	col240: int('col21').primaryKey().identity(),
	col241: int('col21').primaryKey().identity(),
	col242: int('col21').primaryKey().identity(),
	col243: int('col21').primaryKey().identity(),
	col244: int('col21').primaryKey().identity(),
	col245: int('col21').primaryKey().identity(),
	col246: int('col21').primaryKey().identity(),
	col248: int('col21').primaryKey().identity(),
	col249: int('col21').primaryKey().identity(),
	col250: int('col21').primaryKey().identity(),
	col251: int('col21').primaryKey().identity(),
	col252: int('col21').primaryKey().identity(),
	col253: int('col21').primaryKey().identity(),
	col254: int('col21').primaryKey().identity(),
	col255: int('col21').primaryKey().identity(),
	col256: int('col21').primaryKey().identity(),
	col258: int('col21').primaryKey().identity(),
	col259: int('col21').primaryKey().identity(),
	col260: int('col21').primaryKey().identity(),
	col261: int('col21').primaryKey().identity(),
	col262: int('col21').primaryKey().identity(),
	col263: int('col21').primaryKey().identity(),
	col264: int('col21').primaryKey().identity(),
	col265: int('col21').primaryKey().identity(),
	col266: int('col21').primaryKey().identity(),
	col268: int('col21').primaryKey().identity(),
	col269: int('col21').primaryKey().identity(),
	col270: int('col21').primaryKey().identity(),
	col271: int('col21').primaryKey().identity(),
	col272: int('col21').primaryKey().identity(),
	col273: int('col21').primaryKey().identity(),
	col274: int('col21').primaryKey().identity(),
	col275: int('col21').primaryKey().identity(),
	col276: int('col21').primaryKey().identity(),
	col278: int('col21').primaryKey().identity(),
	col279: int('col21').primaryKey().identity(),
	col280: int('col21').primaryKey().identity(),
	col281: int('col21').primaryKey().identity(),
	col282: int('col21').primaryKey().identity(),
	col283: int('col21').primaryKey().identity(),
	col284: int('col21').primaryKey().identity(),
	col285: int('col21').primaryKey().identity(),
	col286: int('col21').primaryKey().identity(),
	col288: int('col21').primaryKey().identity(),
	col289: int('col21').primaryKey().identity(),
	col290: int('col21').primaryKey().identity(),
	col291: int('col21').primaryKey().identity(),
	col292: int('col21').primaryKey().identity(),
	col293: int('col21').primaryKey().identity(),
	col294: int('col21').primaryKey().identity(),
	col295: int('col21').primaryKey().identity(),
	col296: int('col21').primaryKey().identity(),
	col298: int('col21').primaryKey().identity(),
	col299: int('col21').primaryKey().identity(),
	col300: int('col3').primaryKey().identity(),
	col301: int('col3').primaryKey().identity(),
	col302: int('col3').primaryKey().identity(),
	col303: int('col3').primaryKey().identity(),
	col304: int('col3').primaryKey().identity(),
	col305: int('col3').primaryKey().identity(),
	col306: int('col3').primaryKey().identity(),
	col308: int('col3').primaryKey().identity(),
	col309: int('col3').primaryKey().identity(),
	col310: int('col31').primaryKey().identity(),
	col311: int('col31').primaryKey().identity(),
	col312: int('col31').primaryKey().identity(),
	col313: int('col31').primaryKey().identity(),
	col314: int('col31').primaryKey().identity(),
	col315: int('col31').primaryKey().identity(),
	col316: int('col31').primaryKey().identity(),
	col318: int('col31').primaryKey().identity(),
	col319: int('col31').primaryKey().identity(),
	col320: int('col31').primaryKey().identity(),
	col321: int('col31').primaryKey().identity(),
	col322: int('col31').primaryKey().identity(),
	col323: int('col31').primaryKey().identity(),
	col324: int('col31').primaryKey().identity(),
	col325: int('col31').primaryKey().identity(),
	col326: int('col31').primaryKey().identity(),
	col328: int('col31').primaryKey().identity(),
	col329: int('col31').primaryKey().identity(),
	col330: int('col31').primaryKey().identity(),
	col331: int('col31').primaryKey().identity(),
	col332: int('col31').primaryKey().identity(),
	col333: int('col31').primaryKey().identity(),
	col334: int('col31').primaryKey().identity(),
	col335: int('col31').primaryKey().identity(),
	col336: int('col31').primaryKey().identity(),
	col338: int('col31').primaryKey().identity(),
	col339: int('col31').primaryKey().identity(),
	col340: int('col31').primaryKey().identity(),
	col341: int('col31').primaryKey().identity(),
	col342: int('col31').primaryKey().identity(),
	col343: int('col31').primaryKey().identity(),
	col344: int('col31').primaryKey().identity(),
	col345: int('col31').primaryKey().identity(),
	col346: int('col31').primaryKey().identity(),
	col348: int('col31').primaryKey().identity(),
	col349: int('col31').primaryKey().identity(),
	col350: int('col31').primaryKey().identity(),
	col351: int('col31').primaryKey().identity(),
	col352: int('col31').primaryKey().identity(),
	col353: int('col31').primaryKey().identity(),
	col354: int('col31').primaryKey().identity(),
	col355: int('col31').primaryKey().identity(),
	col356: int('col31').primaryKey().identity(),
	col358: int('col31').primaryKey().identity(),
	col359: int('col31').primaryKey().identity(),
	col360: int('col31').primaryKey().identity(),
	col361: int('col31').primaryKey().identity(),
	col362: int('col31').primaryKey().identity(),
	col363: int('col31').primaryKey().identity(),
	col364: int('col31').primaryKey().identity(),
	col365: int('col31').primaryKey().identity(),
	col366: int('col31').primaryKey().identity(),
	col368: int('col31').primaryKey().identity(),
	col369: int('col31').primaryKey().identity(),
	col370: int('col31').primaryKey().identity(),
	col371: int('col31').primaryKey().identity(),
	col372: int('col31').primaryKey().identity(),
	col373: int('col31').primaryKey().identity(),
	col374: int('col31').primaryKey().identity(),
	col375: int('col31').primaryKey().identity(),
	col376: int('col31').primaryKey().identity(),
	col378: int('col31').primaryKey().identity(),
	col379: int('col31').primaryKey().identity(),
	col380: int('col31').primaryKey().identity(),
	col381: int('col31').primaryKey().identity(),
	col382: int('col31').primaryKey().identity(),
	col383: int('col31').primaryKey().identity(),
	col384: int('col31').primaryKey().identity(),
	col385: int('col31').primaryKey().identity(),
	col386: int('col31').primaryKey().identity(),
	col388: int('col31').primaryKey().identity(),
	col389: int('col31').primaryKey().identity(),
	col390: int('col31').primaryKey().identity(),
	col391: int('col31').primaryKey().identity(),
	col392: int('col31').primaryKey().identity(),
	col393: int('col31').primaryKey().identity(),
	col394: int('col31').primaryKey().identity(),
	col395: int('col31').primaryKey().identity(),
	col396: int('col31').primaryKey().identity(),
	col398: int('col31').primaryKey().identity(),
	col399: int('col31').primaryKey().identity(),
	col400: int('col4').primaryKey().identity(),
	col401: int('col4').primaryKey().identity(),
	col402: int('col4').primaryKey().identity(),
	col403: int('col4').primaryKey().identity(),
	col404: int('col4').primaryKey().identity(),
	col405: int('col4').primaryKey().identity(),
	col406: int('col4').primaryKey().identity(),
	col408: int('col4').primaryKey().identity(),
	col409: int('col4').primaryKey().identity(),
	col410: int('col41').primaryKey().identity(),
	col411: int('col41').primaryKey().identity(),
	col412: int('col41').primaryKey().identity(),
	col413: int('col41').primaryKey().identity(),
	col414: int('col41').primaryKey().identity(),
	col415: int('col41').primaryKey().identity(),
	col416: int('col41').primaryKey().identity(),
	col418: int('col41').primaryKey().identity(),
	col419: int('col41').primaryKey().identity(),
	col420: int('col41').primaryKey().identity(),
	col421: int('col41').primaryKey().identity(),
	col422: int('col41').primaryKey().identity(),
	col423: int('col41').primaryKey().identity(),
	col424: int('col41').primaryKey().identity(),
	col425: int('col41').primaryKey().identity(),
	col426: int('col41').primaryKey().identity(),
	col428: int('col41').primaryKey().identity(),
	col429: int('col41').primaryKey().identity(),
	col430: int('col41').primaryKey().identity(),
	col431: int('col41').primaryKey().identity(),
	col432: int('col41').primaryKey().identity(),
	col433: int('col41').primaryKey().identity(),
	col434: int('col41').primaryKey().identity(),
	col435: int('col41').primaryKey().identity(),
	col436: int('col41').primaryKey().identity(),
	col438: int('col41').primaryKey().identity(),
	col439: int('col41').primaryKey().identity(),
	col440: int('col41').primaryKey().identity(),
	col441: int('col41').primaryKey().identity(),
	col442: int('col41').primaryKey().identity(),
	col443: int('col41').primaryKey().identity(),
	col444: int('col41').primaryKey().identity(),
	col445: int('col41').primaryKey().identity(),
	col446: int('col41').primaryKey().identity(),
	col448: int('col41').primaryKey().identity(),
	col449: int('col41').primaryKey().identity(),
	col450: int('col41').primaryKey().identity(),
	col451: int('col41').primaryKey().identity(),
	col452: int('col41').primaryKey().identity(),
	col453: int('col41').primaryKey().identity(),
	col454: int('col41').primaryKey().identity(),
	col455: int('col41').primaryKey().identity(),
	col456: int('col41').primaryKey().identity(),
	col458: int('col41').primaryKey().identity(),
	col459: int('col41').primaryKey().identity(),
	col460: int('col41').primaryKey().identity(),
	col461: int('col41').primaryKey().identity(),
	col462: int('col41').primaryKey().identity(),
	col463: int('col41').primaryKey().identity(),
	col464: int('col41').primaryKey().identity(),
	col465: int('col41').primaryKey().identity(),
	col466: int('col41').primaryKey().identity(),
	col468: int('col41').primaryKey().identity(),
	col469: int('col41').primaryKey().identity(),
	col470: int('col41').primaryKey().identity(),
	col471: int('col41').primaryKey().identity(),
	col472: int('col41').primaryKey().identity(),
	col473: int('col41').primaryKey().identity(),
	col474: int('col41').primaryKey().identity(),
	col475: int('col41').primaryKey().identity(),
	col476: int('col41').primaryKey().identity(),
	col478: int('col41').primaryKey().identity(),
	col479: int('col41').primaryKey().identity(),
	col480: int('col41').primaryKey().identity(),
	col481: int('col41').primaryKey().identity(),
	col482: int('col41').primaryKey().identity(),
	col483: int('col41').primaryKey().identity(),
	col484: int('col41').primaryKey().identity(),
	col485: int('col41').primaryKey().identity(),
	col486: int('col41').primaryKey().identity(),
	col488: int('col41').primaryKey().identity(),
	col489: int('col41').primaryKey().identity(),
	col490: int('col41').primaryKey().identity(),
	col491: int('col41').primaryKey().identity(),
	col492: int('col41').primaryKey().identity(),
	col493: int('col41').primaryKey().identity(),
	col494: int('col41').primaryKey().identity(),
	col495: int('col41').primaryKey().identity(),
	col496: int('col41').primaryKey().identity(),
	col498: int('col41').primaryKey().identity(),
	col499: int('col41').primaryKey().identity(),
	col500: int('col5').primaryKey().identity(),
	col501: int('col5').primaryKey().identity(),
	col502: int('col5').primaryKey().identity(),
	col503: int('col5').primaryKey().identity(),
	col504: int('col5').primaryKey().identity(),
	col505: int('col5').primaryKey().identity(),
	col506: int('col5').primaryKey().identity(),
	col508: int('col5').primaryKey().identity(),
	col509: int('col5').primaryKey().identity(),
	col510: int('col51').primaryKey().identity(),
	col511: int('col51').primaryKey().identity(),
	col512: int('col51').primaryKey().identity(),
	col513: int('col51').primaryKey().identity(),
	col514: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col515: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col516: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col518: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col519: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col520: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col521: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col522: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col523: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col524: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col525: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col526: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col528: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col529: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col530: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col531: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col532: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col533: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col534: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col535: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col536: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col538: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col539: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col540: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col541: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col542: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col543: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col544: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col545: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col546: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col548: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col549: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col550: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col551: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col552: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col553: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col554: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col555: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col556: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col558: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col559: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col560: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col561: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col562: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col563: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col564: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col565: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col566: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col568: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col569: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col570: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col571: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col572: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col573: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col574: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col575: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col576: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col578: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col579: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col580: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col581: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col582: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col583: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col584: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col585: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col586: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col588: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col589: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col590: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col591: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col592: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col593: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col594: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col595: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col596: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col598: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col599: bigint('col51', { mode: 'number' }).primaryKey().identity(),
	col600: bigint('col6', { mode: 'number' }).primaryKey().identity(),
	col601: int('col6').primaryKey().identity(),
	col602: int('col6').primaryKey().identity(),
	col603: int('col6').primaryKey().identity(),
	col604: int('col6').primaryKey().identity(),
	col605: int('col6').primaryKey().identity(),
	col606: int('col6').primaryKey().identity(),
	col608: int('col6').primaryKey().identity(),
	col609: int('col6').primaryKey().identity(),
	col610: int('col61').primaryKey().identity(),
	col611: int('col61').primaryKey().identity(),
	col612: int('col61').primaryKey().identity(),
	col613: int('col61').primaryKey().identity(),
	col614: int('col61').primaryKey().identity(),
	col615: int('col61').primaryKey().identity(),
	col616: int('col61').primaryKey().identity(),
	col618: int('col61').primaryKey().identity(),
	col619: int('col61').primaryKey().identity(),
	col620: int('col61').primaryKey().identity(),
	col621: int('col61').primaryKey().identity(),
	col622: int('col61').primaryKey().identity(),
	col623: int('col61').primaryKey().identity(),
	col624: int('col61').primaryKey().identity(),
	col625: int('col61').primaryKey().identity(),
	col626: int('col61').primaryKey().identity(),
	col628: int('col61').primaryKey().identity(),
	col629: int('col61').primaryKey().identity(),
	col630: int('col61').primaryKey().identity(),
	col631: int('col61').primaryKey().identity(),
	col632: int('col61').primaryKey().identity(),
	col633: int('col61').primaryKey().identity(),
	col634: int('col61').primaryKey().identity(),
	col635: int('col61').primaryKey().identity(),
	col636: int('col61').primaryKey().identity(),
	col638: int('col61').primaryKey().identity(),
	col639: int('col61').primaryKey().identity(),
	col640: int('col61').primaryKey().identity(),
	col641: int('col61').primaryKey().identity(),
	col642: int('col61').primaryKey().identity(),
	col643: int('col61').primaryKey().identity(),
	col644: int('col61').primaryKey().identity(),
	col645: int('col61').primaryKey().identity(),
	col646: int('col61').primaryKey().identity(),
	col648: int('col61').primaryKey().identity(),
	col649: int('col61').primaryKey().identity(),
	col650: int('col61').primaryKey().identity(),
	col651: int('col61').primaryKey().identity(),
	col652: int('col61').primaryKey().identity(),
	col653: int('col61').primaryKey().identity(),
	col654: int('col61').primaryKey().identity(),
	col655: int('col61').primaryKey().identity(),
	col656: int('col61').primaryKey().identity(),
	col658: int('col61').primaryKey().identity(),
	col659: int('col61').primaryKey().identity(),
	col660: int('col61').primaryKey().identity(),
	col661: int('col61').primaryKey().identity(),
	col662: int('col61').primaryKey().identity(),
	col663: int('col61').primaryKey().identity(),
	col664: int('col61').primaryKey().identity(),
	col665: int('col61').primaryKey().identity(),
	col666: int('col61').primaryKey().identity(),
	col668: int('col61').primaryKey().identity(),
	col669: int('col61').primaryKey().identity(),
	col670: int('col61').primaryKey().identity(),
	col671: int('col61').primaryKey().identity(),
	col672: int('col61').primaryKey().identity(),
	col673: int('col61').primaryKey().identity(),
	col674: int('col61').primaryKey().identity(),
	col675: int('col61').primaryKey().identity(),
	col676: int('col61').primaryKey().identity(),
	col678: int('col61').primaryKey().identity(),
	col679: int('col61').primaryKey().identity(),
	col680: int('col61').primaryKey().identity(),
	col681: int('col61').primaryKey().identity(),
	col682: int('col61').primaryKey().identity(),
	col683: int('col61').primaryKey().identity(),
	col684: int('col61').primaryKey().identity(),
	col685: int('col61').primaryKey().identity(),
	col686: int('col61').primaryKey().identity(),
	col688: int('col61').primaryKey().identity(),
	col689: int('col61').primaryKey().identity(),
	col690: int('col61').primaryKey().identity(),
	col691: int('col61').primaryKey().identity(),
	col692: int('col61').primaryKey().identity(),
	col693: int('col61').primaryKey().identity(),
	col694: int('col61').primaryKey().identity(),
	col695: int('col61').primaryKey().identity(),
	col696: int('col61').primaryKey().identity(),
	col698: int('col61').primaryKey().identity(),
	col699: int('col61').primaryKey().identity(),
	col700: int('col7').primaryKey().identity(),
	col701: int('col7').primaryKey().identity(),
	col702: int('col7').primaryKey().identity(),
	col703: int('col7').primaryKey().identity(),
	col704: int('col7').primaryKey().identity(),
	col705: int('col7').primaryKey().identity(),
	col706: int('col7').primaryKey().identity(),
	col708: int('col7').primaryKey().identity(),
	col709: int('col7').primaryKey().identity(),
	col710: int('col71').primaryKey().identity(),
	col711: int('col71').primaryKey().identity(),
	col712: int('col71').primaryKey().identity(),
	col713: int('col71').primaryKey().identity(),
	col714: int('col71').primaryKey().identity(),
	col715: int('col71').primaryKey().identity(),
	col716: int('col71').primaryKey().identity(),
	col718: int('col71').primaryKey().identity(),
	col719: int('col71').primaryKey().identity(),
	col720: int('col71').primaryKey().identity(),
	col721: int('col71').primaryKey().identity(),
	col722: int('col71').primaryKey().identity(),
	col723: int('col71').primaryKey().identity(),
	col724: int('col71').primaryKey().identity(),
	col725: int('col71').primaryKey().identity(),
	col726: int('col71').primaryKey().identity(),
	col728: int('col71').primaryKey().identity(),
	col729: int('col71').primaryKey().identity(),
	col730: int('col71').primaryKey().identity(),
	col731: int('col71').primaryKey().identity(),
	col732: int('col71').primaryKey().identity(),
	col733: int('col71').primaryKey().identity(),
	col734: int('col71').primaryKey().identity(),
	col735: int('col71').primaryKey().identity(),
	col736: int('col71').primaryKey().identity(),
	col738: int('col71').primaryKey().identity(),
	col739: int('col71').primaryKey().identity(),
	col740: int('col71').primaryKey().identity(),
	col741: int('col71').primaryKey().identity(),
	col742: int('col71').primaryKey().identity(),
	col743: int('col71').primaryKey().identity(),
	col744: int('col71').primaryKey().identity(),
	col745: int('col71').primaryKey().identity(),
	col746: int('col71').primaryKey().identity(),
	col748: int('col71').primaryKey().identity(),
	col749: int('col71').primaryKey().identity(),
	col750: int('col71').primaryKey().identity(),
	col751: int('col71').primaryKey().identity(),
	col752: int('col71').primaryKey().identity(),
	col753: int('col71').primaryKey().identity(),
	col754: int('col71').primaryKey().identity(),
	col755: int('col71').primaryKey().identity(),
	col756: int('col71').primaryKey().identity(),
	col758: int('col71').primaryKey().identity(),
	col759: int('col71').primaryKey().identity(),
	col760: int('col71').primaryKey().identity(),
	col761: int('col71').primaryKey().identity(),
	col762: int('col71').primaryKey().identity(),
	col763: int('col71').primaryKey().identity(),
	col764: int('col71').primaryKey().identity(),
	col765: int('col71').primaryKey().identity(),
	col766: int('col71').primaryKey().identity(),
	col768: int('col71').primaryKey().identity(),
	col769: int('col71').primaryKey().identity(),
	col770: int('col71').primaryKey().identity(),
	col771: int('col71').primaryKey().identity(),
	col772: int('col71').primaryKey().identity(),
	col773: int('col71').primaryKey().identity(),
	col774: int('col71').primaryKey().identity(),
	col775: int('col71').primaryKey().identity(),
	col776: int('col71').primaryKey().identity(),
	col778: int('col71').primaryKey().identity(),
	col779: int('col71').primaryKey().identity(),
	col780: int('col71').primaryKey().identity(),
	col781: int('col71').primaryKey().identity(),
	col782: int('col71').primaryKey().identity(),
	col783: int('col71').primaryKey().identity(),
	col784: int('col71').primaryKey().identity(),
	col785: int('col71').primaryKey().identity(),
	col786: int('col71').primaryKey().identity(),
	col788: int('col71').primaryKey().identity(),
	col789: int('col71').primaryKey().identity(),
	col790: int('col71').primaryKey().identity(),
	col791: int('col71').primaryKey().identity(),
	col792: int('col71').primaryKey().identity(),
	col793: int('col71').primaryKey().identity(),
	col794: int('col71').primaryKey().identity(),
	col795: int('col71').primaryKey().identity(),
	col796: int('col71').primaryKey().identity(),
	col798: int('col71').primaryKey().identity(),
	col799: int('col71').primaryKey().identity(),
	col800: int('col8').primaryKey().identity(),
	col801: int('col8').primaryKey().identity(),
	col802: int('col8').primaryKey().identity(),
	col803: int('col8').primaryKey().identity(),
	col804: int('col8').primaryKey().identity(),
	col805: int('col8').primaryKey().identity(),
	col806: int('col8').primaryKey().identity(),
	col808: int('col8').primaryKey().identity(),
	col809: int('col8').primaryKey().identity(),
	col810: int('col81').primaryKey().identity(),
	col811: int('col81').primaryKey().identity(),
	col812: int('col81').primaryKey().identity(),
	col813: int('col81').primaryKey().identity(),
	col814: int('col81').primaryKey().identity(),
	col815: int('col81').primaryKey().identity(),
	col816: int('col81').primaryKey().identity(),
	col818: int('col81').primaryKey().identity(),
	col819: int('col81').primaryKey().identity(),
	col820: int('col81').primaryKey().identity(),
	col821: int('col81').primaryKey().identity(),
	col822: int('col81').primaryKey().identity(),
	col823: int('col81').primaryKey().identity(),
	col824: int('col81').primaryKey().identity(),
	col825: int('col81').primaryKey().identity(),
	col826: int('col81').primaryKey().identity(),
	col828: int('col81').primaryKey().identity(),
	col829: int('col81').primaryKey().identity(),
	col830: int('col81').primaryKey().identity(),
	col831: int('col81').primaryKey().identity(),
	col832: int('col81').primaryKey().identity(),
	col833: int('col81').primaryKey().identity(),
	col834: int('col81').primaryKey().identity(),
	col835: int('col81').primaryKey().identity(),
	col836: int('col81').primaryKey().identity(),
	col838: int('col81').primaryKey().identity(),
	col839: int('col81').primaryKey().identity(),
	col840: int('col81').primaryKey().identity(),
	col841: int('col81').primaryKey().identity(),
	col842: int('col81').primaryKey().identity(),
	col843: int('col81').primaryKey().identity(),
	col844: int('col81').primaryKey().identity(),
	col845: int('col81').primaryKey().identity(),
	col846: int('col81').primaryKey().identity(),
	col848: int('col81').primaryKey().identity(),
	col849: int('col81').primaryKey().identity(),
	col850: int('col81').primaryKey().identity(),
	col851: int('col81').primaryKey().identity(),
	col852: int('col81').primaryKey().identity(),
	col853: int('col81').primaryKey().identity(),
	col854: int('col81').primaryKey().identity(),
	col855: int('col81').primaryKey().identity(),
	col856: int('col81').primaryKey().identity(),
	col858: int('col81').primaryKey().identity(),
	col859: int('col81').primaryKey().identity(),
	col860: int('col81').primaryKey().identity(),
	col861: int('col81').primaryKey().identity(),
	col862: int('col81').primaryKey().identity(),
	col863: int('col81').primaryKey().identity(),
	col864: int('col81').primaryKey().identity(),
	col865: int('col81').primaryKey().identity(),
	col866: int('col81').primaryKey().identity(),
	col868: int('col81').primaryKey().identity(),
	col869: int('col81').primaryKey().identity(),
	col870: int('col81').primaryKey().identity(),
	col871: int('col81').primaryKey().identity(),
	col872: int('col81').primaryKey().identity(),
	col873: int('col81').primaryKey().identity(),
	col874: int('col81').primaryKey().identity(),
	col875: int('col81').primaryKey().identity(),
	col876: int('col81').primaryKey().identity(),
	col878: int('col81').primaryKey().identity(),
	col879: int('col81').primaryKey().identity(),
	col880: int('col81').primaryKey().identity(),
	col881: int('col81').primaryKey().identity(),
	col882: int('col81').primaryKey().identity(),
	col883: int('col81').primaryKey().identity(),
	col884: int('col81').primaryKey().identity(),
	col885: int('col81').primaryKey().identity(),
	col886: int('col81').primaryKey().identity(),
	col888: int('col81').primaryKey().identity(),
	col889: int('col81').primaryKey().identity(),
	col890: int('col81').primaryKey().identity(),
	col891: int('col81').primaryKey().identity(),
	col892: int('col81').primaryKey().identity(),
	col893: int('col81').primaryKey().identity(),
	col894: int('col81').primaryKey().identity(),
	col895: int('col81').primaryKey().identity(),
	col896: int('col81').primaryKey().identity(),
	col898: int('col81').primaryKey().identity(),
	col899: int('col81').primaryKey().identity(),
	col900: int('col9').primaryKey().identity(),
	col901: int('col9').primaryKey().identity(),
	col902: int('col9').primaryKey().identity(),
	col903: int('col9').primaryKey().identity(),
	col904: int('col9').primaryKey().identity(),
	col905: int('col9').primaryKey().identity(),
	col906: int('col9').primaryKey().identity(),
	col908: int('col9').primaryKey().identity(),
	col909: int('col9').primaryKey().identity(),
	col910: int('col91').primaryKey().identity(),
	col911: int('col91').primaryKey().identity(),
	col912: int('col91').primaryKey().identity(),
	col913: int('col91').primaryKey().identity(),
	col914: int('col91').primaryKey().identity(),
	col915: int('col91').primaryKey().identity(),
	col916: int('col91').primaryKey().identity(),
	col918: int('col91').primaryKey().identity(),
	col919: int('col91').primaryKey().identity(),
	col920: int('col91').primaryKey().identity(),
	col921: int('col91').primaryKey().identity(),
	col922: int('col91').primaryKey().identity(),
	col923: int('col91').primaryKey().identity(),
	col924: int('col91').primaryKey().identity(),
	col925: int('col91').primaryKey().identity(),
	col926: int('col91').primaryKey().identity(),
	col928: int('col91').primaryKey().identity(),
	col929: int('col91').primaryKey().identity(),
	col930: int('col91').primaryKey().identity(),
	col931: int('col91').primaryKey().identity(),
	col932: int('col91').primaryKey().identity(),
	col933: int('col91').primaryKey().identity(),
	col934: int('col91').primaryKey().identity(),
	col935: int('col91').primaryKey().identity(),
	col936: int('col91').primaryKey().identity(),
	col938: int('col91').primaryKey().identity(),
	col939: int('col91').primaryKey().identity(),
	col940: int('col91').primaryKey().identity(),
	col941: int('col91').primaryKey().identity(),
	col942: int('col91').primaryKey().identity(),
	col943: int('col91').primaryKey().identity(),
	col944: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col945: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col946: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col948: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col949: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col950: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col951: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col952: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col953: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col954: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col955: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col956: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col958: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col959: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col960: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col961: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col962: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col963: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col964: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col965: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col966: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col968: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col969: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col970: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col971: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col972: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col973: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col974: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col975: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col976: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col978: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col979: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col980: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col981: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col982: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col983: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col984: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col985: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col986: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col988: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col989: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col990: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col991: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col992: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col993: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col994: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col995: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col996: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col998: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col999: varchar('col91', { length: 200 }).primaryKey().default('0'),
});
