CREATE TABLE "users12" (
	"id" int4 PRIMARY KEY GENERATED ALWAYS AS IDENTITY (INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" string NOT NULL,
	"email" string NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users13" (
	"id" int4 PRIMARY KEY GENERATED ALWAYS AS IDENTITY (INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" string NOT NULL,
	"email" string NOT NULL
);
