name: "Bug Report"
description: Report an issue or possible bug
title: "[BUG]:"
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a bug report! Please provide as much information as possible.
        
  - type: checkboxes
    id: verified
    attributes:
      label: Report hasn't been filed before.
      options:
        - label: I have verified that the bug I'm about to report hasn't been filed before.
          required: true

  - type: input
    attributes:
      label: What version of `drizzle-orm` are you using?
      description: You can check the version by opening the `package.json` file in your project.
      placeholder: 0.0.0
    validations:
      required: true

  - type: input
    attributes:
      label: What version of `drizzle-kit` are you using?
      description: You can check the version by opening the `package.json` file in your project.
      placeholder: 0.0.0
    validations:
      required: true

  - type: input
    attributes:
      label: Other packages
      description: If this bug is related to one of the other first-party packages we maintain, please list them here alongside their version.
      placeholder: drizzle-zod@0.0.0, drizzle-valibot@0.0.0
    validations:
      required: false

  - type: textarea
    attributes:
      label: Describe the Bug
      description: |
        To fill this field, please answer the following:
          - What is the undesired behavior?
          - What are the steps to reproduce it?
          - What is the desired result?

        If the issue is more specific, consider answering the following questions if you think they may be relevant:
          - What database engine are you using? Are you using a specific cloud provider? Which one?
          - Do you think this bug pertains to a specific database driver? Which one?
          - Are you working in a monorepo?
          - If this is a bug related to types: What Typescript version are you using? What's the content of your tsconfig.json file?
          - If you're using a runtime that isn't Node.js: Which one? What version? Have you verified that this isn't an issue with the runtime itself?
    validations:
      required: true

