import { bigint, double, mysqlTable, varchar } from '~/mysql-core/index.ts';

mysqlTable('test', {
	col0: double('col1').primaryKey().autoincrement().default(0),
	col1: double('col1').primaryKey().autoincrement().default(0),
	col2: double('col1').primaryKey().autoincrement().default(0),
	col3: double('col1').primaryKey().autoincrement().default(0),
	col4: double('col1').primaryKey().autoincrement().default(0),
	col5: double('col1').primaryKey().autoincrement().default(0),
	col6: double('col1').primaryKey().autoincrement().default(0),
	col8: double('col1').primaryKey().autoincrement().default(0),
	col9: double('col1').primaryKey().autoincrement().default(0),
	col10: double('col1').primaryKey().autoincrement().default(0),
	col11: double('col1').primaryKey().autoincrement().default(0),
	col12: double('col1').primaryKey().autoincrement().default(0),
	col13: double('col1').primaryKey().autoincrement().default(0),
	col14: double('col1').primaryKey().autoincrement().default(0),
	col15: double('col1').primaryKey().autoincrement().default(0),
	col16: double('col1').primaryKey().autoincrement().default(0),
	col18: double('col1').primaryKey().autoincrement().default(0),
	col19: double('col1').primaryKey().autoincrement().default(0),
	col20: double('col1').primaryKey().autoincrement().default(0),
	col21: double('col1').primaryKey().autoincrement().default(0),
	col22: double('col1').primaryKey().autoincrement().default(0),
	col23: double('col1').primaryKey().autoincrement().default(0),
	col24: double('col1').primaryKey().autoincrement().default(0),
	col25: double('col1').primaryKey().autoincrement().default(0),
	col26: double('col1').primaryKey().autoincrement().default(0),
	col28: double('col1').primaryKey().autoincrement().default(0),
	col29: double('col1').primaryKey().autoincrement().default(0),
	col30: double('col1').primaryKey().autoincrement().default(0),
	col31: double('col1').primaryKey().autoincrement().default(0),
	col32: double('col1').primaryKey().autoincrement().default(0),
	col33: double('col1').primaryKey().autoincrement().default(0),
	col34: double('col1').primaryKey().autoincrement().default(0),
	col35: double('col1').primaryKey().autoincrement().default(0),
	col36: double('col1').primaryKey().autoincrement().default(0),
	col38: double('col1').primaryKey().autoincrement().default(0),
	col39: double('col1').primaryKey().autoincrement().default(0),
	col40: double('col1').primaryKey().autoincrement().default(0),
	col41: double('col1').primaryKey().autoincrement().default(0),
	col42: double('col1').primaryKey().autoincrement().default(0),
	col43: double('col1').primaryKey().autoincrement().default(0),
	col44: double('col1').primaryKey().autoincrement().default(0),
	col45: double('col1').primaryKey().autoincrement().default(0),
	col46: double('col1').primaryKey().autoincrement().default(0),
	col48: double('col1').primaryKey().autoincrement().default(0),
	col49: double('col1').primaryKey().autoincrement().default(0),
	col50: double('col1').primaryKey().autoincrement().default(0),
	col51: double('col1').primaryKey().autoincrement().default(0),
	col52: double('col1').primaryKey().autoincrement().default(0),
	col53: double('col1').primaryKey().autoincrement().default(0),
	col54: double('col1').primaryKey().autoincrement().default(0),
	col55: double('col1').primaryKey().autoincrement().default(0),
	col56: double('col1').primaryKey().autoincrement().default(0),
	col58: double('col1').primaryKey().autoincrement().default(0),
	col59: double('col1').primaryKey().autoincrement().default(0),
	col60: double('col1').primaryKey().autoincrement().default(0),
	col61: double('col1').primaryKey().autoincrement().default(0),
	col62: double('col1').primaryKey().autoincrement().default(0),
	col63: double('col1').primaryKey().autoincrement().default(0),
	col64: double('col1').primaryKey().autoincrement().default(0),
	col65: double('col1').primaryKey().autoincrement().default(0),
	col66: double('col1').primaryKey().autoincrement().default(0),
	col68: double('col1').primaryKey().autoincrement().default(0),
	col69: double('col1').primaryKey().autoincrement().default(0),
	col70: double('col1').primaryKey().autoincrement().default(0),
	col71: double('col1').primaryKey().autoincrement().default(0),
	col72: double('col1').primaryKey().autoincrement().default(0),
	col73: double('col1').primaryKey().autoincrement().default(0),
	col74: double('col1').primaryKey().autoincrement().default(0),
	col75: double('col1').primaryKey().autoincrement().default(0),
	col76: double('col1').primaryKey().autoincrement().default(0),
	col78: double('col1').primaryKey().autoincrement().default(0),
	col79: double('col1').primaryKey().autoincrement().default(0),
	col80: double('col1').primaryKey().autoincrement().default(0),
	col81: double('col1').primaryKey().autoincrement().default(0),
	col82: double('col1').primaryKey().autoincrement().default(0),
	col83: double('col1').primaryKey().autoincrement().default(0),
	col84: double('col1').primaryKey().autoincrement().default(0),
	col85: double('col1').primaryKey().autoincrement().default(0),
	col86: double('col1').primaryKey().autoincrement().default(0),
	col88: double('col1').primaryKey().autoincrement().default(0),
	col89: double('col1').primaryKey().autoincrement().default(0),
	col90: double('col1').primaryKey().autoincrement().default(0),
	col91: double('col1').primaryKey().autoincrement().default(0),
	col92: double('col1').primaryKey().autoincrement().default(0),
	col93: double('col1').primaryKey().autoincrement().default(0),
	col94: double('col1').primaryKey().autoincrement().default(0),
	col95: double('col1').primaryKey().autoincrement().default(0),
	col96: double('col1').primaryKey().autoincrement().default(0),
	col98: double('col1').primaryKey().autoincrement().default(0),
	col99: double('col1').primaryKey().autoincrement().default(0),
	col100: double('col1').primaryKey().autoincrement().default(0),
	col101: double('col1').primaryKey().autoincrement().default(0),
	col102: double('col1').primaryKey().autoincrement().default(0),
	col103: double('col1').primaryKey().autoincrement().default(0),
	col104: double('col1').primaryKey().autoincrement().default(0),
	col105: double('col1').primaryKey().autoincrement().default(0),
	col106: double('col1').primaryKey().autoincrement().default(0),
	col108: double('col1').primaryKey().autoincrement().default(0),
	col109: double('col1').primaryKey().autoincrement().default(0),
	col110: double('col11').primaryKey().autoincrement().default(0),
	col111: double('col11').primaryKey().autoincrement().default(0),
	col112: double('col11').primaryKey().autoincrement().default(0),
	col113: double('col11').primaryKey().autoincrement().default(0),
	col114: double('col11').primaryKey().autoincrement().default(0),
	col115: double('col11').primaryKey().autoincrement().default(0),
	col116: double('col11').primaryKey().autoincrement().default(0),
	col118: double('col11').primaryKey().autoincrement().default(0),
	col119: double('col11').primaryKey().autoincrement().default(0),
	col120: double('col11').primaryKey().autoincrement().default(0),
	col121: double('col11').primaryKey().autoincrement().default(0),
	col122: double('col11').primaryKey().autoincrement().default(0),
	col123: double('col11').primaryKey().autoincrement().default(0),
	col124: double('col11').primaryKey().autoincrement().default(0),
	col125: double('col11').primaryKey().autoincrement().default(0),
	col126: double('col11').primaryKey().autoincrement().default(0),
	col128: double('col11').primaryKey().autoincrement().default(0),
	col129: double('col11').primaryKey().autoincrement().default(0),
	col130: double('col11').primaryKey().autoincrement().default(0),
	col131: double('col11').primaryKey().autoincrement().default(0),
	col132: double('col11').primaryKey().autoincrement().default(0),
	col133: double('col11').primaryKey().autoincrement().default(0),
	col134: double('col11').primaryKey().autoincrement().default(0),
	col135: double('col11').primaryKey().autoincrement().default(0),
	col136: double('col11').primaryKey().autoincrement().default(0),
	col138: double('col11').primaryKey().autoincrement().default(0),
	col139: double('col11').primaryKey().autoincrement().default(0),
	col140: double('col11').primaryKey().autoincrement().default(0),
	col141: double('col11').primaryKey().autoincrement().default(0),
	col142: double('col11').primaryKey().autoincrement().default(0),
	col143: double('col11').primaryKey().autoincrement().default(0),
	col144: double('col11').primaryKey().autoincrement().default(0),
	col145: double('col11').primaryKey().autoincrement().default(0),
	col146: double('col11').primaryKey().autoincrement().default(0),
	col148: double('col11').primaryKey().autoincrement().default(0),
	col149: double('col11').primaryKey().autoincrement().default(0),
	col150: double('col11').primaryKey().autoincrement().default(0),
	col151: double('col11').primaryKey().autoincrement().default(0),
	col152: double('col11').primaryKey().autoincrement().default(0),
	col153: double('col11').primaryKey().autoincrement().default(0),
	col154: double('col11').primaryKey().autoincrement().default(0),
	col155: double('col11').primaryKey().autoincrement().default(0),
	col156: double('col11').primaryKey().autoincrement().default(0),
	col158: double('col11').primaryKey().autoincrement().default(0),
	col159: double('col11').primaryKey().autoincrement().default(0),
	col160: double('col11').primaryKey().autoincrement().default(0),
	col161: double('col11').primaryKey().autoincrement().default(0),
	col162: double('col11').primaryKey().autoincrement().default(0),
	col163: double('col11').primaryKey().autoincrement().default(0),
	col164: double('col11').primaryKey().autoincrement().default(0),
	col165: double('col11').primaryKey().autoincrement().default(0),
	col166: double('col11').primaryKey().autoincrement().default(0),
	col168: double('col11').primaryKey().autoincrement().default(0),
	col169: double('col11').primaryKey().autoincrement().default(0),
	col170: double('col11').primaryKey().autoincrement().default(0),
	col171: double('col11').primaryKey().autoincrement().default(0),
	col172: double('col11').primaryKey().autoincrement().default(0),
	col173: double('col11').primaryKey().autoincrement().default(0),
	col174: double('col11').primaryKey().autoincrement().default(0),
	col175: double('col11').primaryKey().autoincrement().default(0),
	col176: double('col11').primaryKey().autoincrement().default(0),
	col178: double('col11').primaryKey().autoincrement().default(0),
	col179: double('col11').primaryKey().autoincrement().default(0),
	col180: double('col11').primaryKey().autoincrement().default(0),
	col181: double('col11').primaryKey().autoincrement().default(0),
	col182: double('col11').primaryKey().autoincrement().default(0),
	col183: double('col11').primaryKey().autoincrement().default(0),
	col184: double('col11').primaryKey().autoincrement().default(0),
	col185: double('col11').primaryKey().autoincrement().default(0),
	col186: double('col11').primaryKey().autoincrement().default(0),
	col188: double('col11').primaryKey().autoincrement().default(0),
	col189: double('col11').primaryKey().autoincrement().default(0),
	col190: double('col11').primaryKey().autoincrement().default(0),
	col191: double('col11').primaryKey().autoincrement().default(0),
	col192: double('col11').primaryKey().autoincrement().default(0),
	col193: double('col11').primaryKey().autoincrement().default(0),
	col194: double('col11').primaryKey().autoincrement().default(0),
	col195: double('col11').primaryKey().autoincrement().default(0),
	col196: double('col11').primaryKey().autoincrement().default(0),
	col198: double('col11').primaryKey().autoincrement().default(0),
	col199: double('col11').primaryKey().autoincrement().default(0),
	col200: double('col2').primaryKey().autoincrement().default(0),
	col201: double('col2').primaryKey().autoincrement().default(0),
	col202: double('col2').primaryKey().autoincrement().default(0),
	col203: double('col2').primaryKey().autoincrement().default(0),
	col204: double('col2').primaryKey().autoincrement().default(0),
	col205: double('col2').primaryKey().autoincrement().default(0),
	col206: double('col2').primaryKey().autoincrement().default(0),
	col208: double('col2').primaryKey().autoincrement().default(0),
	col209: double('col2').primaryKey().autoincrement().default(0),
	col210: double('col21').primaryKey().autoincrement().default(0),
	col211: double('col21').primaryKey().autoincrement().default(0),
	col212: double('col21').primaryKey().autoincrement().default(0),
	col213: double('col21').primaryKey().autoincrement().default(0),
	col214: double('col21').primaryKey().autoincrement().default(0),
	col215: double('col21').primaryKey().autoincrement().default(0),
	col216: double('col21').primaryKey().autoincrement().default(0),
	col218: double('col21').primaryKey().autoincrement().default(0),
	col219: double('col21').primaryKey().autoincrement().default(0),
	col220: double('col21').primaryKey().autoincrement().default(0),
	col221: double('col21').primaryKey().autoincrement().default(0),
	col222: double('col21').primaryKey().autoincrement().default(0),
	col223: double('col21').primaryKey().autoincrement().default(0),
	col224: double('col21').primaryKey().autoincrement().default(0),
	col225: double('col21').primaryKey().autoincrement().default(0),
	col226: double('col21').primaryKey().autoincrement().default(0),
	col228: double('col21').primaryKey().autoincrement().default(0),
	col229: double('col21').primaryKey().autoincrement().default(0),
	col230: double('col21').primaryKey().autoincrement().default(0),
	col231: double('col21').primaryKey().autoincrement().default(0),
	col232: double('col21').primaryKey().autoincrement().default(0),
	col233: double('col21').primaryKey().autoincrement().default(0),
	col234: double('col21').primaryKey().autoincrement().default(0),
	col235: double('col21').primaryKey().autoincrement().default(0),
	col236: double('col21').primaryKey().autoincrement().default(0),
	col238: double('col21').primaryKey().autoincrement().default(0),
	col239: double('col21').primaryKey().autoincrement().default(0),
	col240: double('col21').primaryKey().autoincrement().default(0),
	col241: double('col21').primaryKey().autoincrement().default(0),
	col242: double('col21').primaryKey().autoincrement().default(0),
	col243: double('col21').primaryKey().autoincrement().default(0),
	col244: double('col21').primaryKey().autoincrement().default(0),
	col245: double('col21').primaryKey().autoincrement().default(0),
	col246: double('col21').primaryKey().autoincrement().default(0),
	col248: double('col21').primaryKey().autoincrement().default(0),
	col249: double('col21').primaryKey().autoincrement().default(0),
	col250: double('col21').primaryKey().autoincrement().default(0),
	col251: double('col21').primaryKey().autoincrement().default(0),
	col252: double('col21').primaryKey().autoincrement().default(0),
	col253: double('col21').primaryKey().autoincrement().default(0),
	col254: double('col21').primaryKey().autoincrement().default(0),
	col255: double('col21').primaryKey().autoincrement().default(0),
	col256: double('col21').primaryKey().autoincrement().default(0),
	col258: double('col21').primaryKey().autoincrement().default(0),
	col259: double('col21').primaryKey().autoincrement().default(0),
	col260: double('col21').primaryKey().autoincrement().default(0),
	col261: double('col21').primaryKey().autoincrement().default(0),
	col262: double('col21').primaryKey().autoincrement().default(0),
	col263: double('col21').primaryKey().autoincrement().default(0),
	col264: double('col21').primaryKey().autoincrement().default(0),
	col265: double('col21').primaryKey().autoincrement().default(0),
	col266: double('col21').primaryKey().autoincrement().default(0),
	col268: double('col21').primaryKey().autoincrement().default(0),
	col269: double('col21').primaryKey().autoincrement().default(0),
	col270: double('col21').primaryKey().autoincrement().default(0),
	col271: double('col21').primaryKey().autoincrement().default(0),
	col272: double('col21').primaryKey().autoincrement().default(0),
	col273: double('col21').primaryKey().autoincrement().default(0),
	col274: double('col21').primaryKey().autoincrement().default(0),
	col275: double('col21').primaryKey().autoincrement().default(0),
	col276: double('col21').primaryKey().autoincrement().default(0),
	col278: double('col21').primaryKey().autoincrement().default(0),
	col279: double('col21').primaryKey().autoincrement().default(0),
	col280: double('col21').primaryKey().autoincrement().default(0),
	col281: double('col21').primaryKey().autoincrement().default(0),
	col282: double('col21').primaryKey().autoincrement().default(0),
	col283: double('col21').primaryKey().autoincrement().default(0),
	col284: double('col21').primaryKey().autoincrement().default(0),
	col285: double('col21').primaryKey().autoincrement().default(0),
	col286: double('col21').primaryKey().autoincrement().default(0),
	col288: double('col21').primaryKey().autoincrement().default(0),
	col289: double('col21').primaryKey().autoincrement().default(0),
	col290: double('col21').primaryKey().autoincrement().default(0),
	col291: double('col21').primaryKey().autoincrement().default(0),
	col292: double('col21').primaryKey().autoincrement().default(0),
	col293: double('col21').primaryKey().autoincrement().default(0),
	col294: double('col21').primaryKey().autoincrement().default(0),
	col295: double('col21').primaryKey().autoincrement().default(0),
	col296: double('col21').primaryKey().autoincrement().default(0),
	col298: double('col21').primaryKey().autoincrement().default(0),
	col299: double('col21').primaryKey().autoincrement().default(0),
	col300: double('col3').primaryKey().autoincrement().default(0),
	col301: double('col3').primaryKey().autoincrement().default(0),
	col302: double('col3').primaryKey().autoincrement().default(0),
	col303: double('col3').primaryKey().autoincrement().default(0),
	col304: double('col3').primaryKey().autoincrement().default(0),
	col305: double('col3').primaryKey().autoincrement().default(0),
	col306: double('col3').primaryKey().autoincrement().default(0),
	col308: double('col3').primaryKey().autoincrement().default(0),
	col309: double('col3').primaryKey().autoincrement().default(0),
	col310: double('col31').primaryKey().autoincrement().default(0),
	col311: double('col31').primaryKey().autoincrement().default(0),
	col312: double('col31').primaryKey().autoincrement().default(0),
	col313: double('col31').primaryKey().autoincrement().default(0),
	col314: double('col31').primaryKey().autoincrement().default(0),
	col315: double('col31').primaryKey().autoincrement().default(0),
	col316: double('col31').primaryKey().autoincrement().default(0),
	col318: double('col31').primaryKey().autoincrement().default(0),
	col319: double('col31').primaryKey().autoincrement().default(0),
	col320: double('col31').primaryKey().autoincrement().default(0),
	col321: double('col31').primaryKey().autoincrement().default(0),
	col322: double('col31').primaryKey().autoincrement().default(0),
	col323: double('col31').primaryKey().autoincrement().default(0),
	col324: double('col31').primaryKey().autoincrement().default(0),
	col325: double('col31').primaryKey().autoincrement().default(0),
	col326: double('col31').primaryKey().autoincrement().default(0),
	col328: double('col31').primaryKey().autoincrement().default(0),
	col329: double('col31').primaryKey().autoincrement().default(0),
	col330: double('col31').primaryKey().autoincrement().default(0),
	col331: double('col31').primaryKey().autoincrement().default(0),
	col332: double('col31').primaryKey().autoincrement().default(0),
	col333: double('col31').primaryKey().autoincrement().default(0),
	col334: double('col31').primaryKey().autoincrement().default(0),
	col335: double('col31').primaryKey().autoincrement().default(0),
	col336: double('col31').primaryKey().autoincrement().default(0),
	col338: double('col31').primaryKey().autoincrement().default(0),
	col339: double('col31').primaryKey().autoincrement().default(0),
	col340: double('col31').primaryKey().autoincrement().default(0),
	col341: double('col31').primaryKey().autoincrement().default(0),
	col342: double('col31').primaryKey().autoincrement().default(0),
	col343: double('col31').primaryKey().autoincrement().default(0),
	col344: double('col31').primaryKey().autoincrement().default(0),
	col345: double('col31').primaryKey().autoincrement().default(0),
	col346: double('col31').primaryKey().autoincrement().default(0),
	col348: double('col31').primaryKey().autoincrement().default(0),
	col349: double('col31').primaryKey().autoincrement().default(0),
	col350: double('col31').primaryKey().autoincrement().default(0),
	col351: double('col31').primaryKey().autoincrement().default(0),
	col352: double('col31').primaryKey().autoincrement().default(0),
	col353: double('col31').primaryKey().autoincrement().default(0),
	col354: double('col31').primaryKey().autoincrement().default(0),
	col355: double('col31').primaryKey().autoincrement().default(0),
	col356: double('col31').primaryKey().autoincrement().default(0),
	col358: double('col31').primaryKey().autoincrement().default(0),
	col359: double('col31').primaryKey().autoincrement().default(0),
	col360: double('col31').primaryKey().autoincrement().default(0),
	col361: double('col31').primaryKey().autoincrement().default(0),
	col362: double('col31').primaryKey().autoincrement().default(0),
	col363: double('col31').primaryKey().autoincrement().default(0),
	col364: double('col31').primaryKey().autoincrement().default(0),
	col365: double('col31').primaryKey().autoincrement().default(0),
	col366: double('col31').primaryKey().autoincrement().default(0),
	col368: double('col31').primaryKey().autoincrement().default(0),
	col369: double('col31').primaryKey().autoincrement().default(0),
	col370: double('col31').primaryKey().autoincrement().default(0),
	col371: double('col31').primaryKey().autoincrement().default(0),
	col372: double('col31').primaryKey().autoincrement().default(0),
	col373: double('col31').primaryKey().autoincrement().default(0),
	col374: double('col31').primaryKey().autoincrement().default(0),
	col375: double('col31').primaryKey().autoincrement().default(0),
	col376: double('col31').primaryKey().autoincrement().default(0),
	col378: double('col31').primaryKey().autoincrement().default(0),
	col379: double('col31').primaryKey().autoincrement().default(0),
	col380: double('col31').primaryKey().autoincrement().default(0),
	col381: double('col31').primaryKey().autoincrement().default(0),
	col382: double('col31').primaryKey().autoincrement().default(0),
	col383: double('col31').primaryKey().autoincrement().default(0),
	col384: double('col31').primaryKey().autoincrement().default(0),
	col385: double('col31').primaryKey().autoincrement().default(0),
	col386: double('col31').primaryKey().autoincrement().default(0),
	col388: double('col31').primaryKey().autoincrement().default(0),
	col389: double('col31').primaryKey().autoincrement().default(0),
	col390: double('col31').primaryKey().autoincrement().default(0),
	col391: double('col31').primaryKey().autoincrement().default(0),
	col392: double('col31').primaryKey().autoincrement().default(0),
	col393: double('col31').primaryKey().autoincrement().default(0),
	col394: double('col31').primaryKey().autoincrement().default(0),
	col395: double('col31').primaryKey().autoincrement().default(0),
	col396: double('col31').primaryKey().autoincrement().default(0),
	col398: double('col31').primaryKey().autoincrement().default(0),
	col399: double('col31').primaryKey().autoincrement().default(0),
	col400: double('col4').primaryKey().autoincrement().default(0),
	col401: double('col4').primaryKey().autoincrement().default(0),
	col402: double('col4').primaryKey().autoincrement().default(0),
	col403: double('col4').primaryKey().autoincrement().default(0),
	col404: double('col4').primaryKey().autoincrement().default(0),
	col405: double('col4').primaryKey().autoincrement().default(0),
	col406: double('col4').primaryKey().autoincrement().default(0),
	col408: double('col4').primaryKey().autoincrement().default(0),
	col409: double('col4').primaryKey().autoincrement().default(0),
	col410: double('col41').primaryKey().autoincrement().default(0),
	col411: double('col41').primaryKey().autoincrement().default(0),
	col412: double('col41').primaryKey().autoincrement().default(0),
	col413: double('col41').primaryKey().autoincrement().default(0),
	col414: double('col41').primaryKey().autoincrement().default(0),
	col415: double('col41').primaryKey().autoincrement().default(0),
	col416: double('col41').primaryKey().autoincrement().default(0),
	col418: double('col41').primaryKey().autoincrement().default(0),
	col419: double('col41').primaryKey().autoincrement().default(0),
	col420: double('col41').primaryKey().autoincrement().default(0),
	col421: double('col41').primaryKey().autoincrement().default(0),
	col422: double('col41').primaryKey().autoincrement().default(0),
	col423: double('col41').primaryKey().autoincrement().default(0),
	col424: double('col41').primaryKey().autoincrement().default(0),
	col425: double('col41').primaryKey().autoincrement().default(0),
	col426: double('col41').primaryKey().autoincrement().default(0),
	col428: double('col41').primaryKey().autoincrement().default(0),
	col429: double('col41').primaryKey().autoincrement().default(0),
	col430: double('col41').primaryKey().autoincrement().default(0),
	col431: double('col41').primaryKey().autoincrement().default(0),
	col432: double('col41').primaryKey().autoincrement().default(0),
	col433: double('col41').primaryKey().autoincrement().default(0),
	col434: double('col41').primaryKey().autoincrement().default(0),
	col435: double('col41').primaryKey().autoincrement().default(0),
	col436: double('col41').primaryKey().autoincrement().default(0),
	col438: double('col41').primaryKey().autoincrement().default(0),
	col439: double('col41').primaryKey().autoincrement().default(0),
	col440: double('col41').primaryKey().autoincrement().default(0),
	col441: double('col41').primaryKey().autoincrement().default(0),
	col442: double('col41').primaryKey().autoincrement().default(0),
	col443: double('col41').primaryKey().autoincrement().default(0),
	col444: double('col41').primaryKey().autoincrement().default(0),
	col445: double('col41').primaryKey().autoincrement().default(0),
	col446: double('col41').primaryKey().autoincrement().default(0),
	col448: double('col41').primaryKey().autoincrement().default(0),
	col449: double('col41').primaryKey().autoincrement().default(0),
	col450: double('col41').primaryKey().autoincrement().default(0),
	col451: double('col41').primaryKey().autoincrement().default(0),
	col452: double('col41').primaryKey().autoincrement().default(0),
	col453: double('col41').primaryKey().autoincrement().default(0),
	col454: double('col41').primaryKey().autoincrement().default(0),
	col455: double('col41').primaryKey().autoincrement().default(0),
	col456: double('col41').primaryKey().autoincrement().default(0),
	col458: double('col41').primaryKey().autoincrement().default(0),
	col459: double('col41').primaryKey().autoincrement().default(0),
	col460: double('col41').primaryKey().autoincrement().default(0),
	col461: double('col41').primaryKey().autoincrement().default(0),
	col462: double('col41').primaryKey().autoincrement().default(0),
	col463: double('col41').primaryKey().autoincrement().default(0),
	col464: double('col41').primaryKey().autoincrement().default(0),
	col465: double('col41').primaryKey().autoincrement().default(0),
	col466: double('col41').primaryKey().autoincrement().default(0),
	col468: double('col41').primaryKey().autoincrement().default(0),
	col469: double('col41').primaryKey().autoincrement().default(0),
	col470: double('col41').primaryKey().autoincrement().default(0),
	col471: double('col41').primaryKey().autoincrement().default(0),
	col472: double('col41').primaryKey().autoincrement().default(0),
	col473: double('col41').primaryKey().autoincrement().default(0),
	col474: double('col41').primaryKey().autoincrement().default(0),
	col475: double('col41').primaryKey().autoincrement().default(0),
	col476: double('col41').primaryKey().autoincrement().default(0),
	col478: double('col41').primaryKey().autoincrement().default(0),
	col479: double('col41').primaryKey().autoincrement().default(0),
	col480: double('col41').primaryKey().autoincrement().default(0),
	col481: double('col41').primaryKey().autoincrement().default(0),
	col482: double('col41').primaryKey().autoincrement().default(0),
	col483: double('col41').primaryKey().autoincrement().default(0),
	col484: double('col41').primaryKey().autoincrement().default(0),
	col485: double('col41').primaryKey().autoincrement().default(0),
	col486: double('col41').primaryKey().autoincrement().default(0),
	col488: double('col41').primaryKey().autoincrement().default(0),
	col489: double('col41').primaryKey().autoincrement().default(0),
	col490: double('col41').primaryKey().autoincrement().default(0),
	col491: double('col41').primaryKey().autoincrement().default(0),
	col492: double('col41').primaryKey().autoincrement().default(0),
	col493: double('col41').primaryKey().autoincrement().default(0),
	col494: double('col41').primaryKey().autoincrement().default(0),
	col495: double('col41').primaryKey().autoincrement().default(0),
	col496: double('col41').primaryKey().autoincrement().default(0),
	col498: double('col41').primaryKey().autoincrement().default(0),
	col499: double('col41').primaryKey().autoincrement().default(0),
	col500: double('col5').primaryKey().autoincrement().default(0),
	col501: double('col5').primaryKey().autoincrement().default(0),
	col502: double('col5').primaryKey().autoincrement().default(0),
	col503: double('col5').primaryKey().autoincrement().default(0),
	col504: double('col5').primaryKey().autoincrement().default(0),
	col505: double('col5').primaryKey().autoincrement().default(0),
	col506: double('col5').primaryKey().autoincrement().default(0),
	col508: double('col5').primaryKey().autoincrement().default(0),
	col509: double('col5').primaryKey().autoincrement().default(0),
	col510: double('col51').primaryKey().autoincrement().default(0),
	col511: double('col51').primaryKey().autoincrement().default(0),
	col512: double('col51').primaryKey().autoincrement().default(0),
	col513: double('col51').primaryKey().autoincrement().default(0),
	col514: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col515: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col516: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col518: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col519: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col520: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col521: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col522: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col523: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col524: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col525: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col526: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col528: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col529: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col530: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col531: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col532: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col533: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col534: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col535: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col536: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col538: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col539: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col540: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col541: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col542: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col543: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col544: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col545: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col546: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col548: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col549: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col550: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col551: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col552: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col553: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col554: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col555: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col556: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col558: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col559: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col560: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col561: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col562: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col563: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col564: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col565: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col566: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col568: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col569: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col570: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col571: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col572: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col573: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col574: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col575: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col576: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col578: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col579: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col580: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col581: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col582: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col583: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col584: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col585: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col586: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col588: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col589: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col590: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col591: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col592: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col593: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col594: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col595: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col596: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col598: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col599: bigint('col51', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col600: bigint('col6', { mode: 'number' }).primaryKey().autoincrement().default(0),
	col601: double('col6').primaryKey().autoincrement().default(0),
	col602: double('col6').primaryKey().autoincrement().default(0),
	col603: double('col6').primaryKey().autoincrement().default(0),
	col604: double('col6').primaryKey().autoincrement().default(0),
	col605: double('col6').primaryKey().autoincrement().default(0),
	col606: double('col6').primaryKey().autoincrement().default(0),
	col608: double('col6').primaryKey().autoincrement().default(0),
	col609: double('col6').primaryKey().autoincrement().default(0),
	col610: double('col61').primaryKey().autoincrement().default(0),
	col611: double('col61').primaryKey().autoincrement().default(0),
	col612: double('col61').primaryKey().autoincrement().default(0),
	col613: double('col61').primaryKey().autoincrement().default(0),
	col614: double('col61').primaryKey().autoincrement().default(0),
	col615: double('col61').primaryKey().autoincrement().default(0),
	col616: double('col61').primaryKey().autoincrement().default(0),
	col618: double('col61').primaryKey().autoincrement().default(0),
	col619: double('col61').primaryKey().autoincrement().default(0),
	col620: double('col61').primaryKey().autoincrement().default(0),
	col621: double('col61').primaryKey().autoincrement().default(0),
	col622: double('col61').primaryKey().autoincrement().default(0),
	col623: double('col61').primaryKey().autoincrement().default(0),
	col624: double('col61').primaryKey().autoincrement().default(0),
	col625: double('col61').primaryKey().autoincrement().default(0),
	col626: double('col61').primaryKey().autoincrement().default(0),
	col628: double('col61').primaryKey().autoincrement().default(0),
	col629: double('col61').primaryKey().autoincrement().default(0),
	col630: double('col61').primaryKey().autoincrement().default(0),
	col631: double('col61').primaryKey().autoincrement().default(0),
	col632: double('col61').primaryKey().autoincrement().default(0),
	col633: double('col61').primaryKey().autoincrement().default(0),
	col634: double('col61').primaryKey().autoincrement().default(0),
	col635: double('col61').primaryKey().autoincrement().default(0),
	col636: double('col61').primaryKey().autoincrement().default(0),
	col638: double('col61').primaryKey().autoincrement().default(0),
	col639: double('col61').primaryKey().autoincrement().default(0),
	col640: double('col61').primaryKey().autoincrement().default(0),
	col641: double('col61').primaryKey().autoincrement().default(0),
	col642: double('col61').primaryKey().autoincrement().default(0),
	col643: double('col61').primaryKey().autoincrement().default(0),
	col644: double('col61').primaryKey().autoincrement().default(0),
	col645: double('col61').primaryKey().autoincrement().default(0),
	col646: double('col61').primaryKey().autoincrement().default(0),
	col648: double('col61').primaryKey().autoincrement().default(0),
	col649: double('col61').primaryKey().autoincrement().default(0),
	col650: double('col61').primaryKey().autoincrement().default(0),
	col651: double('col61').primaryKey().autoincrement().default(0),
	col652: double('col61').primaryKey().autoincrement().default(0),
	col653: double('col61').primaryKey().autoincrement().default(0),
	col654: double('col61').primaryKey().autoincrement().default(0),
	col655: double('col61').primaryKey().autoincrement().default(0),
	col656: double('col61').primaryKey().autoincrement().default(0),
	col658: double('col61').primaryKey().autoincrement().default(0),
	col659: double('col61').primaryKey().autoincrement().default(0),
	col660: double('col61').primaryKey().autoincrement().default(0),
	col661: double('col61').primaryKey().autoincrement().default(0),
	col662: double('col61').primaryKey().autoincrement().default(0),
	col663: double('col61').primaryKey().autoincrement().default(0),
	col664: double('col61').primaryKey().autoincrement().default(0),
	col665: double('col61').primaryKey().autoincrement().default(0),
	col666: double('col61').primaryKey().autoincrement().default(0),
	col668: double('col61').primaryKey().autoincrement().default(0),
	col669: double('col61').primaryKey().autoincrement().default(0),
	col670: double('col61').primaryKey().autoincrement().default(0),
	col671: double('col61').primaryKey().autoincrement().default(0),
	col672: double('col61').primaryKey().autoincrement().default(0),
	col673: double('col61').primaryKey().autoincrement().default(0),
	col674: double('col61').primaryKey().autoincrement().default(0),
	col675: double('col61').primaryKey().autoincrement().default(0),
	col676: double('col61').primaryKey().autoincrement().default(0),
	col678: double('col61').primaryKey().autoincrement().default(0),
	col679: double('col61').primaryKey().autoincrement().default(0),
	col680: double('col61').primaryKey().autoincrement().default(0),
	col681: double('col61').primaryKey().autoincrement().default(0),
	col682: double('col61').primaryKey().autoincrement().default(0),
	col683: double('col61').primaryKey().autoincrement().default(0),
	col684: double('col61').primaryKey().autoincrement().default(0),
	col685: double('col61').primaryKey().autoincrement().default(0),
	col686: double('col61').primaryKey().autoincrement().default(0),
	col688: double('col61').primaryKey().autoincrement().default(0),
	col689: double('col61').primaryKey().autoincrement().default(0),
	col690: double('col61').primaryKey().autoincrement().default(0),
	col691: double('col61').primaryKey().autoincrement().default(0),
	col692: double('col61').primaryKey().autoincrement().default(0),
	col693: double('col61').primaryKey().autoincrement().default(0),
	col694: double('col61').primaryKey().autoincrement().default(0),
	col695: double('col61').primaryKey().autoincrement().default(0),
	col696: double('col61').primaryKey().autoincrement().default(0),
	col698: double('col61').primaryKey().autoincrement().default(0),
	col699: double('col61').primaryKey().autoincrement().default(0),
	col700: double('col7').primaryKey().autoincrement().default(0),
	col701: double('col7').primaryKey().autoincrement().default(0),
	col702: double('col7').primaryKey().autoincrement().default(0),
	col703: double('col7').primaryKey().autoincrement().default(0),
	col704: double('col7').primaryKey().autoincrement().default(0),
	col705: double('col7').primaryKey().autoincrement().default(0),
	col706: double('col7').primaryKey().autoincrement().default(0),
	col708: double('col7').primaryKey().autoincrement().default(0),
	col709: double('col7').primaryKey().autoincrement().default(0),
	col710: double('col71').primaryKey().autoincrement().default(0),
	col711: double('col71').primaryKey().autoincrement().default(0),
	col712: double('col71').primaryKey().autoincrement().default(0),
	col713: double('col71').primaryKey().autoincrement().default(0),
	col714: double('col71').primaryKey().autoincrement().default(0),
	col715: double('col71').primaryKey().autoincrement().default(0),
	col716: double('col71').primaryKey().autoincrement().default(0),
	col718: double('col71').primaryKey().autoincrement().default(0),
	col719: double('col71').primaryKey().autoincrement().default(0),
	col720: double('col71').primaryKey().autoincrement().default(0),
	col721: double('col71').primaryKey().autoincrement().default(0),
	col722: double('col71').primaryKey().autoincrement().default(0),
	col723: double('col71').primaryKey().autoincrement().default(0),
	col724: double('col71').primaryKey().autoincrement().default(0),
	col725: double('col71').primaryKey().autoincrement().default(0),
	col726: double('col71').primaryKey().autoincrement().default(0),
	col728: double('col71').primaryKey().autoincrement().default(0),
	col729: double('col71').primaryKey().autoincrement().default(0),
	col730: double('col71').primaryKey().autoincrement().default(0),
	col731: double('col71').primaryKey().autoincrement().default(0),
	col732: double('col71').primaryKey().autoincrement().default(0),
	col733: double('col71').primaryKey().autoincrement().default(0),
	col734: double('col71').primaryKey().autoincrement().default(0),
	col735: double('col71').primaryKey().autoincrement().default(0),
	col736: double('col71').primaryKey().autoincrement().default(0),
	col738: double('col71').primaryKey().autoincrement().default(0),
	col739: double('col71').primaryKey().autoincrement().default(0),
	col740: double('col71').primaryKey().autoincrement().default(0),
	col741: double('col71').primaryKey().autoincrement().default(0),
	col742: double('col71').primaryKey().autoincrement().default(0),
	col743: double('col71').primaryKey().autoincrement().default(0),
	col744: double('col71').primaryKey().autoincrement().default(0),
	col745: double('col71').primaryKey().autoincrement().default(0),
	col746: double('col71').primaryKey().autoincrement().default(0),
	col748: double('col71').primaryKey().autoincrement().default(0),
	col749: double('col71').primaryKey().autoincrement().default(0),
	col750: double('col71').primaryKey().autoincrement().default(0),
	col751: double('col71').primaryKey().autoincrement().default(0),
	col752: double('col71').primaryKey().autoincrement().default(0),
	col753: double('col71').primaryKey().autoincrement().default(0),
	col754: double('col71').primaryKey().autoincrement().default(0),
	col755: double('col71').primaryKey().autoincrement().default(0),
	col756: double('col71').primaryKey().autoincrement().default(0),
	col758: double('col71').primaryKey().autoincrement().default(0),
	col759: double('col71').primaryKey().autoincrement().default(0),
	col760: double('col71').primaryKey().autoincrement().default(0),
	col761: double('col71').primaryKey().autoincrement().default(0),
	col762: double('col71').primaryKey().autoincrement().default(0),
	col763: double('col71').primaryKey().autoincrement().default(0),
	col764: double('col71').primaryKey().autoincrement().default(0),
	col765: double('col71').primaryKey().autoincrement().default(0),
	col766: double('col71').primaryKey().autoincrement().default(0),
	col768: double('col71').primaryKey().autoincrement().default(0),
	col769: double('col71').primaryKey().autoincrement().default(0),
	col770: double('col71').primaryKey().autoincrement().default(0),
	col771: double('col71').primaryKey().autoincrement().default(0),
	col772: double('col71').primaryKey().autoincrement().default(0),
	col773: double('col71').primaryKey().autoincrement().default(0),
	col774: double('col71').primaryKey().autoincrement().default(0),
	col775: double('col71').primaryKey().autoincrement().default(0),
	col776: double('col71').primaryKey().autoincrement().default(0),
	col778: double('col71').primaryKey().autoincrement().default(0),
	col779: double('col71').primaryKey().autoincrement().default(0),
	col780: double('col71').primaryKey().autoincrement().default(0),
	col781: double('col71').primaryKey().autoincrement().default(0),
	col782: double('col71').primaryKey().autoincrement().default(0),
	col783: double('col71').primaryKey().autoincrement().default(0),
	col784: double('col71').primaryKey().autoincrement().default(0),
	col785: double('col71').primaryKey().autoincrement().default(0),
	col786: double('col71').primaryKey().autoincrement().default(0),
	col788: double('col71').primaryKey().autoincrement().default(0),
	col789: double('col71').primaryKey().autoincrement().default(0),
	col790: double('col71').primaryKey().autoincrement().default(0),
	col791: double('col71').primaryKey().autoincrement().default(0),
	col792: double('col71').primaryKey().autoincrement().default(0),
	col793: double('col71').primaryKey().autoincrement().default(0),
	col794: double('col71').primaryKey().autoincrement().default(0),
	col795: double('col71').primaryKey().autoincrement().default(0),
	col796: double('col71').primaryKey().autoincrement().default(0),
	col798: double('col71').primaryKey().autoincrement().default(0),
	col799: double('col71').primaryKey().autoincrement().default(0),
	col800: double('col8').primaryKey().autoincrement().default(0),
	col801: double('col8').primaryKey().autoincrement().default(0),
	col802: double('col8').primaryKey().autoincrement().default(0),
	col803: double('col8').primaryKey().autoincrement().default(0),
	col804: double('col8').primaryKey().autoincrement().default(0),
	col805: double('col8').primaryKey().autoincrement().default(0),
	col806: double('col8').primaryKey().autoincrement().default(0),
	col808: double('col8').primaryKey().autoincrement().default(0),
	col809: double('col8').primaryKey().autoincrement().default(0),
	col810: double('col81').primaryKey().autoincrement().default(0),
	col811: double('col81').primaryKey().autoincrement().default(0),
	col812: double('col81').primaryKey().autoincrement().default(0),
	col813: double('col81').primaryKey().autoincrement().default(0),
	col814: double('col81').primaryKey().autoincrement().default(0),
	col815: double('col81').primaryKey().autoincrement().default(0),
	col816: double('col81').primaryKey().autoincrement().default(0),
	col818: double('col81').primaryKey().autoincrement().default(0),
	col819: double('col81').primaryKey().autoincrement().default(0),
	col820: double('col81').primaryKey().autoincrement().default(0),
	col821: double('col81').primaryKey().autoincrement().default(0),
	col822: double('col81').primaryKey().autoincrement().default(0),
	col823: double('col81').primaryKey().autoincrement().default(0),
	col824: double('col81').primaryKey().autoincrement().default(0),
	col825: double('col81').primaryKey().autoincrement().default(0),
	col826: double('col81').primaryKey().autoincrement().default(0),
	col828: double('col81').primaryKey().autoincrement().default(0),
	col829: double('col81').primaryKey().autoincrement().default(0),
	col830: double('col81').primaryKey().autoincrement().default(0),
	col831: double('col81').primaryKey().autoincrement().default(0),
	col832: double('col81').primaryKey().autoincrement().default(0),
	col833: double('col81').primaryKey().autoincrement().default(0),
	col834: double('col81').primaryKey().autoincrement().default(0),
	col835: double('col81').primaryKey().autoincrement().default(0),
	col836: double('col81').primaryKey().autoincrement().default(0),
	col838: double('col81').primaryKey().autoincrement().default(0),
	col839: double('col81').primaryKey().autoincrement().default(0),
	col840: double('col81').primaryKey().autoincrement().default(0),
	col841: double('col81').primaryKey().autoincrement().default(0),
	col842: double('col81').primaryKey().autoincrement().default(0),
	col843: double('col81').primaryKey().autoincrement().default(0),
	col844: double('col81').primaryKey().autoincrement().default(0),
	col845: double('col81').primaryKey().autoincrement().default(0),
	col846: double('col81').primaryKey().autoincrement().default(0),
	col848: double('col81').primaryKey().autoincrement().default(0),
	col849: double('col81').primaryKey().autoincrement().default(0),
	col850: double('col81').primaryKey().autoincrement().default(0),
	col851: double('col81').primaryKey().autoincrement().default(0),
	col852: double('col81').primaryKey().autoincrement().default(0),
	col853: double('col81').primaryKey().autoincrement().default(0),
	col854: double('col81').primaryKey().autoincrement().default(0),
	col855: double('col81').primaryKey().autoincrement().default(0),
	col856: double('col81').primaryKey().autoincrement().default(0),
	col858: double('col81').primaryKey().autoincrement().default(0),
	col859: double('col81').primaryKey().autoincrement().default(0),
	col860: double('col81').primaryKey().autoincrement().default(0),
	col861: double('col81').primaryKey().autoincrement().default(0),
	col862: double('col81').primaryKey().autoincrement().default(0),
	col863: double('col81').primaryKey().autoincrement().default(0),
	col864: double('col81').primaryKey().autoincrement().default(0),
	col865: double('col81').primaryKey().autoincrement().default(0),
	col866: double('col81').primaryKey().autoincrement().default(0),
	col868: double('col81').primaryKey().autoincrement().default(0),
	col869: double('col81').primaryKey().autoincrement().default(0),
	col870: double('col81').primaryKey().autoincrement().default(0),
	col871: double('col81').primaryKey().autoincrement().default(0),
	col872: double('col81').primaryKey().autoincrement().default(0),
	col873: double('col81').primaryKey().autoincrement().default(0),
	col874: double('col81').primaryKey().autoincrement().default(0),
	col875: double('col81').primaryKey().autoincrement().default(0),
	col876: double('col81').primaryKey().autoincrement().default(0),
	col878: double('col81').primaryKey().autoincrement().default(0),
	col879: double('col81').primaryKey().autoincrement().default(0),
	col880: double('col81').primaryKey().autoincrement().default(0),
	col881: double('col81').primaryKey().autoincrement().default(0),
	col882: double('col81').primaryKey().autoincrement().default(0),
	col883: double('col81').primaryKey().autoincrement().default(0),
	col884: double('col81').primaryKey().autoincrement().default(0),
	col885: double('col81').primaryKey().autoincrement().default(0),
	col886: double('col81').primaryKey().autoincrement().default(0),
	col888: double('col81').primaryKey().autoincrement().default(0),
	col889: double('col81').primaryKey().autoincrement().default(0),
	col890: double('col81').primaryKey().autoincrement().default(0),
	col891: double('col81').primaryKey().autoincrement().default(0),
	col892: double('col81').primaryKey().autoincrement().default(0),
	col893: double('col81').primaryKey().autoincrement().default(0),
	col894: double('col81').primaryKey().autoincrement().default(0),
	col895: double('col81').primaryKey().autoincrement().default(0),
	col896: double('col81').primaryKey().autoincrement().default(0),
	col898: double('col81').primaryKey().autoincrement().default(0),
	col899: double('col81').primaryKey().autoincrement().default(0),
	col900: double('col9').primaryKey().autoincrement().default(0),
	col901: double('col9').primaryKey().autoincrement().default(0),
	col902: double('col9').primaryKey().autoincrement().default(0),
	col903: double('col9').primaryKey().autoincrement().default(0),
	col904: double('col9').primaryKey().autoincrement().default(0),
	col905: double('col9').primaryKey().autoincrement().default(0),
	col906: double('col9').primaryKey().autoincrement().default(0),
	col908: double('col9').primaryKey().autoincrement().default(0),
	col909: double('col9').primaryKey().autoincrement().default(0),
	col910: double('col91').primaryKey().autoincrement().default(0),
	col911: double('col91').primaryKey().autoincrement().default(0),
	col912: double('col91').primaryKey().autoincrement().default(0),
	col913: double('col91').primaryKey().autoincrement().default(0),
	col914: double('col91').primaryKey().autoincrement().default(0),
	col915: double('col91').primaryKey().autoincrement().default(0),
	col916: double('col91').primaryKey().autoincrement().default(0),
	col918: double('col91').primaryKey().autoincrement().default(0),
	col919: double('col91').primaryKey().autoincrement().default(0),
	col920: double('col91').primaryKey().autoincrement().default(0),
	col921: double('col91').primaryKey().autoincrement().default(0),
	col922: double('col91').primaryKey().autoincrement().default(0),
	col923: double('col91').primaryKey().autoincrement().default(0),
	col924: double('col91').primaryKey().autoincrement().default(0),
	col925: double('col91').primaryKey().autoincrement().default(0),
	col926: double('col91').primaryKey().autoincrement().default(0),
	col928: double('col91').primaryKey().autoincrement().default(0),
	col929: double('col91').primaryKey().autoincrement().default(0),
	col930: double('col91').primaryKey().autoincrement().default(0),
	col931: double('col91').primaryKey().autoincrement().default(0),
	col932: double('col91').primaryKey().autoincrement().default(0),
	col933: double('col91').primaryKey().autoincrement().default(0),
	col934: double('col91').primaryKey().autoincrement().default(0),
	col935: double('col91').primaryKey().autoincrement().default(0),
	col936: double('col91').primaryKey().autoincrement().default(0),
	col938: double('col91').primaryKey().autoincrement().default(0),
	col939: double('col91').primaryKey().autoincrement().default(0),
	col940: double('col91').primaryKey().autoincrement().default(0),
	col941: double('col91').primaryKey().autoincrement().default(0),
	col942: double('col91').primaryKey().autoincrement().default(0),
	col943: double('col91').primaryKey().autoincrement().default(0),
	col944: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col945: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col946: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col948: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col949: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col950: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col951: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col952: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col953: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col954: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col955: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col956: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col958: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col959: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col960: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col961: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col962: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col963: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col964: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col965: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col966: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col968: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col969: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col970: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col971: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col972: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col973: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col974: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col975: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col976: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col978: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col979: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col980: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col981: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col982: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col983: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col984: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col985: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col986: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col988: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col989: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col990: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col991: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col992: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col993: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col994: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col995: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col996: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col998: varchar('col91', { length: 200 }).primaryKey().default('0'),
	col999: varchar('col91', { length: 200 }).primaryKey().default('0'),
});
