import { makePgArray, parsePgArray } from '~/pg-core/array.ts';
import {
	arrayCompatCast,
	arrayCompatNormalize,
	arrayCompatNormalizeInput,
	castToText,
	castToTextArr,
	makeBoxArray,
	makeGeometryArray,
	parseGeometryArrayAndNormalize,
	parseGeometryTuple,
	parseGeometryXY,
	parseLineABC,
	parseLineTuple,
	parsePgArrayAndNormalize,
	parsePgVector,
	parsePointTuple,
	parsePointXY,
	type PgCodecs,
	refineGenericPgCodecs,
	textToDate,
	textToDateWithTz,
} from '~/pg-core/codecs.ts';
import { sql } from '~/sql/sql.ts';

const stringifyBigint = (value: bigint) => value.toString();

// For arrays
const pgTextToBool = (value: string) => value === 't' || value === 'true';
const pgTextToBuffer = (value: string) => Buffer.from(value.slice(2), 'hex');
const bufferToPgHex = (value: any) => `\\x${Buffer.from(value).toString('hex')}`;

const jsonStringify = (value: any) => JSON.stringify(value);
const jsonParse = (value: string) => JSON.parse(value);

/** Unused by driver functional set of codecs provided for extension */
export const minipgCodecs = refineGenericPgCodecs({
	smallint: {
		normalizeArray: parsePgArrayAndNormalize(Number),
		normalizeParamArray: (v) => makePgArray(v),
	},
	int: {
		normalizeArray: parsePgArrayAndNormalize(Number),
		normalizeParamArray: (v) => makePgArray(v),
	},
	serial: {
		normalizeArray: parsePgArrayAndNormalize(Number),
		normalizeParamArray: (v) => makePgArray(v),
	},
	smallserial: {
		normalizeArray: parsePgArrayAndNormalize(Number),
		normalizeParamArray: (v) => makePgArray(v),
	},
	float4: {
		normalizeArray: parsePgArrayAndNormalize(Number),
		normalizeParamArray: (v) => makePgArray(v),
	},
	float8: {
		normalizeArray: parsePgArrayAndNormalize(Number),
		normalizeParamArray: (v) => makePgArray(v),
	},
	bigint: {
		normalize: BigInt,
		normalizeArray: parsePgArrayAndNormalize(BigInt),
		normalizeParam: stringifyBigint,
		normalizeParamArray: (v) => makePgArray(v),
	},
	'bigint:number': {
		normalize: Number,
		normalizeArray: parsePgArrayAndNormalize(Number),
		normalizeParamArray: (v) => makePgArray(v),
	},
	'bigint:string': {
		normalize: String,
		normalizeArray: (v) => parsePgArray(v),
		normalizeParamArray: (v) => makePgArray(v),
	},
	bigserial: {
		normalize: BigInt,
		normalizeArray: parsePgArrayAndNormalize(BigInt),
		normalizeParam: stringifyBigint,
		normalizeParamArray: (v) => makePgArray(v),
	},
	'bigserial:number': {
		normalize: Number,
		normalizeArray: parsePgArrayAndNormalize(Number),
		normalizeParamArray: (v) => makePgArray(v),
	},
	numeric: {
		normalizeArray: (v) => parsePgArray(v),
		normalizeParamArray: (v) => makePgArray(v),
	},
	'numeric:number': {
		normalize: Number,
		normalizeArray: parsePgArrayAndNormalize(Number),
		normalizeParamArray: (v) => makePgArray(v),
	},
	'numeric:bigint': {
		normalize: BigInt,
		normalizeArray: parsePgArrayAndNormalize(BigInt),
		normalizeParamArray: (v) => makePgArray(v),
	},
	money: {
		normalizeArray: (v) => parsePgArray(v),
		normalizeParamArray: (v) => makePgArray(v),
	},
	char: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	varchar: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	text: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	xml: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	bytea: {
		normalizeArray: parsePgArrayAndNormalize(pgTextToBuffer),
		normalizeParamArray: arrayCompatNormalizeInput(bufferToPgHex, true),
	},
	date: {
		normalize: textToDate,
		normalizeArray: parsePgArrayAndNormalize(textToDate),
		normalizeParamArray: (v) => makePgArray(v),
	},
	'date:string': {
		cast: castToText,
		castArray: castToTextArr,
		normalizeArray: (v) => parsePgArray(v),
		normalizeParamArray: (v) => makePgArray(v),
	},
	time: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	timetz: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	timestamp: {
		normalize: textToDateWithTz,
		normalizeArray: parsePgArrayAndNormalize(textToDateWithTz),
		normalizeParamArray: (v) => makePgArray(v),
	},
	timestamptz: {
		normalize: textToDate,
		normalizeArray: parsePgArrayAndNormalize(textToDate),
		normalizeParamArray: (v) => makePgArray(v),
	},
	'timestamp:string': {
		cast: castToText,
		castArray: castToTextArr,
		normalizeArray: (v) => parsePgArray(v),
		normalizeParamArray: (v) => makePgArray(v),
	},
	'timestamptz:string': {
		cast: castToText,
		castArray: castToTextArr,
		normalizeArray: (v) => parsePgArray(v),
		normalizeParamArray: (v) => makePgArray(v),
	},
	interval: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	bool: {
		normalizeArray: parsePgArrayAndNormalize(pgTextToBool),
		normalizeParamArray: (v) => makePgArray(v),
	},
	enum: {
		castArray: castToTextArr,
		normalizeArray: (v) => parsePgArray(v),
		normalizeParamArray: (v) => makePgArray(v),
	},
	point: {
		normalize: parsePointXY,
		normalizeArray: parsePgArrayAndNormalize(parsePointXY),
		normalizeParamArray: (v) => makePgArray(v),
	},
	'point:tuple': {
		normalize: parsePointTuple,
		normalizeArray: parsePgArrayAndNormalize(parsePointTuple),
		normalizeParamArray: (v) => makePgArray(v),
	},
	line: {
		normalize: parseLineABC,
		normalizeArray: parsePgArrayAndNormalize(parseLineABC),
		normalizeParamArray: (v) => makePgArray(v),
	},
	'line:tuple': {
		normalize: parseLineTuple,
		normalizeArray: parsePgArrayAndNormalize(parseLineTuple),
		normalizeParamArray: (v) => makePgArray(v),
	},
	lseg: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	box: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: makeBoxArray },
	path: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	polygon: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	circle: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	cidr: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	inet: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	macaddr: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	macaddr8: {
		castArray: castToTextArr,
		normalizeArray: (v) => parsePgArray(v),
		normalizeParamArray: (v) => makePgArray(v),
	},
	bit: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	varbit: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	tsvector: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	tsquery: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	uuid: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	json: {
		normalizeArray: parsePgArrayAndNormalize(jsonParse),
		normalizeParam: jsonStringify,
		normalizeParamArray: arrayCompatNormalizeInput(jsonStringify, true),
	},
	jsonb: {
		normalizeArray: parsePgArrayAndNormalize(jsonParse),
		normalizeParam: jsonStringify,
		normalizeParamArray: arrayCompatNormalizeInput(jsonStringify, true),
	},
	int4range: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	int8range: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	numrange: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	tsrange: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	tstzrange: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	daterange: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	int4multirange: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	int8multirange: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	nummultirange: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	tsmultirange: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	tstzmultirange: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	datemultirange: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	oid: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	regproc: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	regprocedure: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	regoper: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	regoperator: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	regclass: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	regtype: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	regrole: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	regnamespace: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	regconfig: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	regdictionary: { normalizeArray: (v) => parsePgArray(v), normalizeParamArray: (v) => makePgArray(v) },
	'geometry(point)': {
		normalize: parseGeometryXY,
		normalizeArray: parseGeometryArrayAndNormalize(parseGeometryXY),
		normalizeParamArray: makeGeometryArray,
	},
	'geometry(point):tuple': {
		normalize: parseGeometryTuple,
		normalizeArray: parseGeometryArrayAndNormalize(parseGeometryTuple),
		normalizeParamArray: makeGeometryArray,
	},
	'geography(point)': { normalizeParamArray: makeGeometryArray },
	'geography(point):tuple': { normalizeParamArray: makeGeometryArray },
	box2d: { normalizeParamArray: (v) => makePgArray(v) },
	box3d: { normalizeParamArray: (v) => makePgArray(v) },
	raster: { normalizeParamArray: (v) => makePgArray(v) },
	halfvec: {
		normalize: parsePgVector,
		normalizeArray: parsePgArrayAndNormalize(parsePgVector),
		normalizeParamArray: (v) => makePgArray(v),
	},
	sparsevec: {
		normalizeArray: (v) => parsePgArray(v),
		normalizeParamArray: (v) => makePgArray(v),
	},
	vector: {
		normalize: parsePgVector,
		normalizeArray: parsePgArrayAndNormalize(parsePgVector),
		normalizeParamArray: (v) => makePgArray(v),
	},
});

/** Set of codecs statically linked to driver-side mapper shape generator intended to cover shape generator's gaps
 *
 * Useless for overrides or on their own
 */
export const minipgShapeCodecs: PgCodecs = {
	smallint: { normalizeParamArray: (v) => makePgArray(v) },
	int: { normalizeParamArray: (v) => makePgArray(v) },
	serial: { normalizeParamArray: (v) => makePgArray(v) },
	smallserial: { normalizeParamArray: (v) => makePgArray(v) },
	float4: { normalizeParamArray: (v) => makePgArray(v) },
	float8: { normalizeParamArray: (v) => makePgArray(v) },
	bigint: { normalizeParam: stringifyBigint, normalizeParamArray: (v) => makePgArray(v) },
	'bigint:number': { normalizeParamArray: (v) => makePgArray(v) },
	'bigint:string': { normalizeParamArray: (v) => makePgArray(v) },
	bigserial: { normalizeParam: stringifyBigint, normalizeParamArray: (v) => makePgArray(v) },
	'bigserial:number': { normalizeParamArray: (v) => makePgArray(v) },
	numeric: { normalizeParamArray: (v) => makePgArray(v) },
	'numeric:number': { normalizeParamArray: (v) => makePgArray(v) },
	'numeric:bigint': { normalizeParamArray: (v) => makePgArray(v) },
	money: { normalizeParamArray: (v) => makePgArray(v) },
	char: { normalizeParamArray: (v) => makePgArray(v) },
	varchar: { normalizeParamArray: (v) => makePgArray(v) },
	text: { normalizeParamArray: (v) => makePgArray(v) },
	xml: { normalizeParamArray: (v) => makePgArray(v) },
	bytea: {
		normalizeParamArray: arrayCompatNormalizeInput(bufferToPgHex, true),
		castInJson: (name) => sql`encode(${name}, 'base64')`,
		castArrayInJson: arrayCompatCast((name) => sql`encode(${name}, 'base64')`),
		normalizeInJson: (v: string) => Buffer.from(v, 'base64'),
		normalizeArrayInJson: arrayCompatNormalize((v: string) => Buffer.from(v, 'base64')),
	},
	date: { normalizeParamArray: (v) => makePgArray(v) },
	'date:string': { normalizeParamArray: (v) => makePgArray(v) },
	time: { normalizeParamArray: (v) => makePgArray(v) },
	timetz: { normalizeParamArray: (v) => makePgArray(v) },
	timestamp: { normalizeParamArray: (v) => makePgArray(v) },
	timestamptz: { normalizeParamArray: (v) => makePgArray(v) },
	'timestamp:string': {
		normalizeParamArray: (v) => makePgArray(v),
		castInJson: castToText,
		castArrayInJson: castToTextArr,
	},
	'timestamptz:string': {
		normalizeParamArray: (v) => makePgArray(v),
		castInJson: castToText,
		castArrayInJson: castToTextArr,
	},
	interval: { normalizeParamArray: (v) => makePgArray(v) },
	bool: { normalizeParamArray: (v) => makePgArray(v) },
	enum: { normalizeParamArray: (v) => makePgArray(v) },
	point: {
		normalizeParamArray: (v) => makePgArray(v),
		castInJson: castToText,
		castArrayInJson: castToTextArr,
		normalizeInJson: parsePointXY,
		normalizeArrayInJson: arrayCompatNormalize(parsePointXY),
	},
	'point:tuple': {
		normalizeParamArray: (v) => makePgArray(v),
		castInJson: castToText,
		castArrayInJson: castToTextArr,
		normalizeInJson: parsePointTuple,
		normalizeArrayInJson: arrayCompatNormalize(parsePointTuple),
	},
	line: {
		normalizeParamArray: (v) => makePgArray(v),
		castInJson: castToText,
		castArrayInJson: castToTextArr,
		normalizeInJson: parseLineABC,
		normalizeArrayInJson: arrayCompatNormalize(parseLineABC),
	},
	'line:tuple': {
		normalizeParamArray: (v) => makePgArray(v),
		castInJson: castToText,
		castArrayInJson: castToTextArr,
		normalizeInJson: parseLineTuple,
		normalizeArrayInJson: arrayCompatNormalize(parseLineTuple),
	},
	lseg: { normalizeParamArray: (v) => makePgArray(v) },
	box: { normalizeParamArray: makeBoxArray },
	path: { normalizeParamArray: (v) => makePgArray(v) },
	polygon: { normalizeParamArray: (v) => makePgArray(v) },
	circle: { normalizeParamArray: (v) => makePgArray(v) },
	cidr: { normalizeParamArray: (v) => makePgArray(v) },
	inet: { normalizeParamArray: (v) => makePgArray(v) },
	macaddr: { normalizeParamArray: (v) => makePgArray(v) },
	macaddr8: { normalizeParamArray: (v) => makePgArray(v) },
	bit: { normalizeParamArray: (v) => makePgArray(v) },
	varbit: { normalizeParamArray: (v) => makePgArray(v) },
	tsvector: { normalizeParamArray: (v) => makePgArray(v) },
	tsquery: { normalizeParamArray: (v) => makePgArray(v) },
	uuid: { normalizeParamArray: (v) => makePgArray(v) },
	json: { normalizeParam: jsonStringify, normalizeParamArray: arrayCompatNormalizeInput(jsonStringify, true) },
	jsonb: { normalizeParam: jsonStringify, normalizeParamArray: arrayCompatNormalizeInput(jsonStringify, true) },
	int4range: { normalizeParamArray: (v) => makePgArray(v) },
	int8range: { normalizeParamArray: (v) => makePgArray(v) },
	numrange: { normalizeParamArray: (v) => makePgArray(v) },
	tsrange: { normalizeParamArray: (v) => makePgArray(v) },
	tstzrange: { normalizeParamArray: (v) => makePgArray(v) },
	daterange: { normalizeParamArray: (v) => makePgArray(v) },
	int4multirange: { normalizeParamArray: (v) => makePgArray(v) },
	int8multirange: { normalizeParamArray: (v) => makePgArray(v) },
	nummultirange: { normalizeParamArray: (v) => makePgArray(v) },
	tsmultirange: { normalizeParamArray: (v) => makePgArray(v) },
	tstzmultirange: { normalizeParamArray: (v) => makePgArray(v) },
	datemultirange: { normalizeParamArray: (v) => makePgArray(v) },
	oid: { normalizeParamArray: (v) => makePgArray(v) },
	regproc: { normalizeParamArray: (v) => makePgArray(v) },
	regprocedure: { normalizeParamArray: (v) => makePgArray(v) },
	regoper: { normalizeParamArray: (v) => makePgArray(v) },
	regoperator: { normalizeParamArray: (v) => makePgArray(v) },
	regclass: { normalizeParamArray: (v) => makePgArray(v) },
	regtype: { normalizeParamArray: (v) => makePgArray(v) },
	regrole: { normalizeParamArray: (v) => makePgArray(v) },
	regnamespace: { normalizeParamArray: (v) => makePgArray(v) },
	regconfig: { normalizeParamArray: (v) => makePgArray(v) },
	regdictionary: { normalizeParamArray: (v) => makePgArray(v) },
	'geometry(point)': {
		normalizeParamArray: makeGeometryArray,
		castInJson: castToText,
		castArrayInJson: castToTextArr,
		normalizeInJson: parseGeometryXY,
		normalizeArrayInJson: arrayCompatNormalize(parseGeometryXY),
	},
	'geometry(point):tuple': {
		normalizeParamArray: makeGeometryArray,
		castInJson: castToText,
		castArrayInJson: castToTextArr,
		normalizeInJson: parseGeometryTuple,
		normalizeArrayInJson: arrayCompatNormalize(parseGeometryTuple),
	},
	'geography(point)': { normalizeParamArray: makeGeometryArray },
	'geography(point):tuple': { normalizeParamArray: makeGeometryArray },
	box2d: { normalizeParamArray: (v) => makePgArray(v) },
	box3d: { normalizeParamArray: (v) => makePgArray(v) },
	raster: { normalizeParamArray: (v) => makePgArray(v) },
	halfvec: {
		normalizeParamArray: (v) => makePgArray(v),
		castInJson: castToText,
		castArrayInJson: castToTextArr,
		normalizeInJson: parsePgVector,
		normalizeArrayInJson: arrayCompatNormalize(parsePgVector),
	},
	sparsevec: { normalizeParamArray: (v) => makePgArray(v) },
	vector: {
		normalizeParamArray: (v) => makePgArray(v),
		castInJson: castToText,
		castArrayInJson: castToTextArr,
		normalizeInJson: parsePgVector,
		normalizeArrayInJson: arrayCompatNormalize(parsePgVector),
	},
};
