services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drizzle
      TZ: UTC
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "33306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -proot --silent"]
      interval: 2s
      timeout: 3s
      retries: 40
