import {
	bigint,
	binary,
	bit,
	char,
	date,
	datetime,
	datetime2,
	datetimeoffset,
	decimal,
	float,
	int,
	mssqlTable,
	numeric,
	real,
	smallint,
	text,
	time,
	tinyint,
	varbinary,
	varchar,
} from 'drizzle-orm/mssql-core';

export const allDataTypes = mssqlTable('all_data_types', {
	int: int('integer'),
	tinyint: tinyint('tinyint'),
	smallint: smallint('smallint'),
	biginteger: bigint('bigint', { mode: 'bigint' }),
	bigintNumber: bigint('bigint_number', { mode: 'number' }),
	real: real('real'),
	decimal: decimal('decimal'),
	numeric: numeric('numeric'),
	float: float('float'),
	binary: binary('binary', { length: 5 }),
	varbinary: varbinary('varbinary', { length: 5 }),
	char: char('char', { length: 5 }),
	varchar: varchar('varchar', { length: 5 }),
	text: text('text'),
	bit: bit('bit'),
	dateString: date('date_string', { mode: 'string' }),
	date: date('date', { mode: 'date' }),
	datetime: datetime('datetime', { mode: 'date' }),
	datetimeString: datetime('datetime_string', { mode: 'string' }),
	datetime2: datetime2('datetime2', { mode: 'date' }),
	datetime2String: datetime2('datetime2_string', { mode: 'string' }),
	datetimeOffset: datetimeoffset('datetime_offset', { mode: 'date' }),
	datetimeOffsetString: datetimeoffset('datetime_offset_string', { mode: 'string' }),
	time: time('time'),
	// json: json('json'),
});
