CREATE TABLE "FB_MIGRATED_USERS" (
	"ID" integer PRIMARY KEY NOT NULL,
	"NAME" varchar(80) NOT NULL
);
--> statement-breakpoint
CREATE VIEW "FB_MIGRATED_USER_NAMES" AS
SELECT "ID", "NAME" FROM "FB_MIGRATED_USERS";
