import type { BatchItem } from '~/batch.ts';
import { DrizzleError } from '~/errors.ts';
import type { MigrationConfig, MigratorInitFailResponse } from '~/migrator.ts';
import { readMigrationFiles } from '~/migrator.ts';
import { getMigrationsToRun } from '~/migrator.utils.ts';
import type { AnyRelations } from '~/relations.ts';
import { sql } from '~/sql/sql.ts';
import { upgradeIfNeeded } from '~/up-migrations/pg.ts';
import type { PostgresHttpDatabase } from './driver-core.ts';

/**
 * This function reads migrationFolder and execute each unapplied migration and mark it as executed in database
 *
 * @param db - drizzle db instance
 * @param config - path to migration folder generated by drizzle-kit
 */
export async function migrate<TRelations extends AnyRelations>(
	db: PostgresHttpDatabase<TRelations>,
	config: MigrationConfig,
): Promise<void | MigratorInitFailResponse> {
	const migrations = readMigrationFiles(config);
	const migrationsTable = config.migrationsTable ?? '__drizzle_migrations';
	const migrationsSchema = config.migrationsSchema ?? 'drizzle';

	await db.session.execute(sql`CREATE SCHEMA IF NOT EXISTS ${sql.identifier(migrationsSchema)}`);

	const { newDb } = await upgradeIfNeeded(migrationsSchema, migrationsTable, db, migrations, 'batch');

	if (newDb) {
		const migrationTableCreate = sql`
			CREATE TABLE IF NOT EXISTS ${sql.identifier(migrationsSchema)}.${sql.identifier(migrationsTable)} (
				id SERIAL PRIMARY KEY,
				hash text NOT NULL,
				created_at bigint,
				name text,
				applied_at timestamp with time zone DEFAULT now()
			)
		`;

		await db.session.execute(migrationTableCreate);
	}

	const dbMigrations = await db.session.objects<{ id: number; hash: string; created_at: string; name: string | null }>(
		sql`select id, hash, created_at, name from ${sql.identifier(migrationsSchema)}.${sql.identifier(migrationsTable)}`,
	);

	if (typeof config === 'object' && config.init) {
		if (dbMigrations.length) {
			return { exitCode: 'databaseMigrations' as const };
		}

		if (migrations.length > 1) {
			return { exitCode: 'localMigrations' as const };
		}

		const [migration] = migrations;

		if (!migration) return;

		await db.session.execute(
			sql`insert into ${sql.identifier(migrationsSchema)}.${
				sql.identifier(migrationsTable)
			} ("hash", "created_at", "name") values(${migration.hash}, ${migration.folderMillis}, ${migration.name})`,
		);

		return;
	}

	const migrationsToRun = getMigrationsToRun({ localMigrations: migrations, dbMigrations });

	const statements: BatchItem<'pg'>[] = [];
	for (const migration of migrationsToRun) {
		for (const stmt of migration.sql) {
			statements.push(db.execute(sql.raw(stmt)));
		}

		statements.push(
			db.execute(
				sql`insert into ${sql.identifier(migrationsSchema)}.${
					sql.identifier(migrationsTable)
				} ("hash", "created_at", "name") values(${migration.hash}, ${migration.folderMillis}, ${migration.name})`,
			),
		);
	}

	if (statements.length) {
		await db.batch(statements as [BatchItem<'pg'>, ...BatchItem<'pg'>[]]);
	}
}

/**
 * Down statements and their journal deletions are sent as a single batch: the driver has no interactive
 * transactions, so a batch is the only way to keep a failed rollback from leaving partial state behind.
 */
export async function rollback<TRelations extends AnyRelations>(
	db: PostgresHttpDatabase<TRelations>,
	config: MigrationConfig,
	steps: number = 1,
) {
	const migrations = readMigrationFiles(config);
	const migrationsTable = config.migrationsTable ?? '__drizzle_migrations';
	const migrationsSchema = config.migrationsSchema ?? 'drizzle';

	const dbMigrations = await db.session.objects<{ id: number; hash: string; created_at: string; name: string | null }>(
		sql`select id, hash, name from ${sql.identifier(migrationsSchema)}.${
			sql.identifier(migrationsTable)
		} order by id desc limit ${sql.raw(String(steps))}`,
	);

	if (dbMigrations.length === 0) {
		return;
	}

	const statements: BatchItem<'pg'>[] = [];
	for (const dbMigration of dbMigrations) {
		const meta = migrations.find((m) =>
			m.hash === dbMigration.hash && (!dbMigration.name || m.name === dbMigration.name)
		);
		if (!meta) {
			throw new DrizzleError({
				message: `Cannot rollback migration with hash ${dbMigration.hash}: migration file not found`,
			});
		}
		if (!meta.downSql || meta.downSql.length === 0) {
			throw new DrizzleError({
				message:
					`Cannot rollback migration ${dbMigration.hash}: no down SQL available. Add a down.sql file alongside the migration.`,
			});
		}
		for (const stmt of meta.downSql) {
			statements.push(db.execute(sql.raw(stmt)));
		}
		statements.push(
			db.execute(
				sql`delete from ${sql.identifier(migrationsSchema)}.${
					sql.identifier(migrationsTable)
				} where id = ${dbMigration.id}`,
			),
		);
	}

	if (statements.length) {
		await db.batch(statements as [BatchItem<'pg'>, ...BatchItem<'pg'>[]]);
	}
}
