import { makePgArray, parsePgArray } from '~/pg-core/array.ts';
import {
	arrayCompatNormalize,
	arrayCompatNormalizeInput,
	castToText,
	castToTextArr,
	parseGeometryTuple,
	parseGeometryXY,
	parsePgArrayAndNormalize,
	refineGenericPgCodecs,
	textToDate,
	textToDateWithTz,
} from '~/pg-core/codecs.ts';

const byteaFromBlob = (v: Uint8Array | Buffer): Buffer => Buffer.from(v);
const byteaFromPgHex = (v: string): Buffer => Buffer.from(v.slice(2), 'hex');

export const awsDataApiPgCodecs = refineGenericPgCodecs({
	json: {
		castArray: castToTextArr,
		castParam: (name) => `${name}::json`,
		castArrayParam: (name, _column, dim) => `${name}::json${'[]'.repeat(dim)}`,
		normalize: (v) => JSON.parse(v),
		normalizeArray: arrayCompatNormalize((v: string) => JSON.parse(v)),
		normalizeParam: (v) => JSON.stringify(v),
		normalizeParamArray: arrayCompatNormalizeInput((v) => JSON.stringify(v), true),
	},
	jsonb: {
		castArray: castToTextArr,
		castParam: (name) => `${name}::jsonb`,
		castArrayParam: (name, _column, dim) => `${name}::jsonb${'[]'.repeat(dim)}`,
		normalize: (v) => JSON.parse(v),
		normalizeArray: arrayCompatNormalize((v: string) => JSON.parse(v)),
		normalizeParam: (v) => JSON.stringify(v),
		normalizeParamArray: arrayCompatNormalizeInput((v) => JSON.stringify(v), true),
	},
	bytea: {
		castArray: castToTextArr,
		castParam: (name) => `${name}::bytea`,
		castArrayParam: (name, _column, dim) => `${name}::bytea${'[]'.repeat(dim)}`,
		normalize: byteaFromBlob,
		normalizeArray: arrayCompatNormalize(byteaFromPgHex),
		normalizeParamArray: makePgArray,
	},
	bit: {
		cast: castToText,
		castArray: castToTextArr,
		castParam: (name, column) => `${name}::bit(${column.length})`,
		castArrayParam: (name, column, dim) => `${name}::bit(${column.length})${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	'geometry(point)': {
		castParam: (name) => `${name}::geometry`,
		castArrayParam: (name, _column, dim) => `${name}::geometry${'[]'.repeat(dim)}`,
		normalizeArray: parsePgArrayAndNormalize(parseGeometryXY),
		normalizeParamArray: makePgArray,
	},
	'geometry(point):tuple': {
		castParam: (name) => `${name}::geometry`,
		castArrayParam: (name, _column, dim) => `${name}::geometry${'[]'.repeat(dim)}`,
		normalizeArray: parsePgArrayAndNormalize(parseGeometryTuple),
		normalizeParamArray: makePgArray,
	},
	interval: {
		cast: castToText,
		castArray: castToTextArr,
		castParam: (name) => `${name}::interval`,
		castArrayParam: (name, _column, dim) => `${name}::interval${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	line: {
		cast: castToText,
		castArray: castToTextArr,
		castParam: (name) => `${name}::line`,
		castArrayParam: (name, _column, dim) => `${name}::line${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	'line:tuple': {
		cast: castToText,
		castArray: castToTextArr,
		castParam: (name) => `${name}::line`,
		castArrayParam: (name, _column, dim) => `${name}::line${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	macaddr: {
		cast: castToText,
		castArray: castToTextArr,
		castParam: (name) => `${name}::macaddr`,
		castArrayParam: (name, _column, dim) => `${name}::macaddr${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	macaddr8: {
		cast: castToText,
		castArrayInJson: castToTextArr,
		castArray: castToTextArr,
		castParam: (name) => `${name}::macaddr8`,
		castArrayParam: (name, _column, dim) => `${name}::macaddr8${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	cidr: {
		cast: castToText,
		castArray: castToTextArr,
		castParam: (name) => `${name}::cidr`,
		castArrayParam: (name, _column, dim) => `${name}::cidr${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	inet: {
		cast: castToText,
		castArray: castToTextArr,
		castParam: (name) => `${name}::inet`,
		castArrayParam: (name, _column, dim) => `${name}::inet${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	point: {
		cast: castToText,
		castArray: castToTextArr,
		castParam: (name) => `${name}::point`,
		castArrayParam: (name, _column, dim) => `${name}::point${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	'point:tuple': {
		cast: castToText,
		castArray: castToTextArr,
		castParam: (name) => `${name}::point`,
		castArrayParam: (name, _column, dim) => `${name}::point${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	halfvec: {
		castParam: (name) => `${name}::halfvec`,
		castArrayParam: (name, _column, dim) => `${name}::halfvec${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	sparsevec: {
		castParam: (name) => `${name}::sparsevec`,
		castArrayParam: (name, _column, dim) => `${name}::sparsevec${'[]'.repeat(dim)}`,
		normalizeArray: parsePgArray,
		normalizeParamArray: makePgArray,
	},
	vector: {
		castParam: (name) => `${name}::vector`,
		castArrayParam: (name, _column, dim) => `${name}::vector${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},

	bool: {
		castParam: (name) => `${name}::boolean`,
		castArrayParam: (name, _column, dim) => `${name}::boolean${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	box: {
		castParam: (name) => `${name}::box`,
		castArrayParam: (name, _column, dim) => `${name}::box${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	box2d: {
		castParam: (name) => `${name}::box2d`,
		castArrayParam: (name, _column, dim) => `${name}::box2d${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	box3d: {
		castParam: (name) => `${name}::box3d`,
		castArrayParam: (name, _column, dim) => `${name}::box3d${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	char: {
		castParam: (name) => `${name}::char`,
		castArrayParam: (name, _column, dim) => `${name}::char${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	circle: {
		castParam: (name) => `${name}::circle`,
		castArrayParam: (name, _column, dim) => `${name}::circle${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	datemultirange: {
		castParam: (name) => `${name}::datemultirange`,
		castArrayParam: (name, _column, dim) => `${name}::datemultirange${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	daterange: {
		castParam: (name) => `${name}::daterange`,
		castArrayParam: (name, _column, dim) => `${name}::daterange${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	float8: {
		castParam: (name) => `${name}::double precision`,
		castArrayParam: (name, _column, dim) => `${name}::double precision${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	'geography(point)': {
		castParam: (name) => `${name}::geography`,
		castArrayParam: (name, _column, dim) => `${name}::geography${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	'geography(point):tuple': {
		castParam: (name) => `${name}::geography`,
		castArrayParam: (name, _column, dim) => `${name}::geography${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	int4multirange: {
		castParam: (name) => `${name}::int4multirange`,
		castArrayParam: (name, _column, dim) => `${name}::int4multirange${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	int4range: {
		castParam: (name) => `${name}::int4range`,
		castArrayParam: (name, _column, dim) => `${name}::int4range${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	int8multirange: {
		castParam: (name) => `${name}::int8multirange`,
		castArrayParam: (name, _column, dim) => `${name}::int8multirange${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	int8range: {
		castParam: (name) => `${name}::int8range`,
		castArrayParam: (name, _column, dim) => `${name}::int8range${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	lseg: {
		castParam: (name) => `${name}::lseg`,
		castArrayParam: (name, _column, dim) => `${name}::lseg${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	money: {
		castParam: (name) => `${name}::money`,
		castArrayParam: (name, _column, dim) => `${name}::money${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	nummultirange: {
		castParam: (name) => `${name}::nummultirange`,
		castArrayParam: (name, _column, dim) => `${name}::nummultirange${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	numrange: {
		castParam: (name) => `${name}::numrange`,
		castArrayParam: (name, _column, dim) => `${name}::numrange${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	oid: {
		castParam: (name) => `${name}::oid`,
		castArrayParam: (name, _column, dim) => `${name}::oid${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	path: {
		castParam: (name) => `${name}::path`,
		castArrayParam: (name, _column, dim) => `${name}::path${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	polygon: {
		castParam: (name) => `${name}::polygon`,
		castArrayParam: (name, _column, dim) => `${name}::polygon${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	raster: {
		castParam: (name) => `${name}::raster`,
		castArrayParam: (name, _column, dim) => `${name}::raster${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	regclass: {
		castParam: (name) => `${name}::regclass`,
		castArrayParam: (name, _column, dim) => `${name}::regclass${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	regconfig: {
		castParam: (name) => `${name}::regconfig`,
		castArrayParam: (name, _column, dim) => `${name}::regconfig${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	regdictionary: {
		castParam: (name) => `${name}::regdictionary`,
		castArrayParam: (name, _column, dim) => `${name}::regdictionary${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	regnamespace: {
		castParam: (name) => `${name}::regnamespace`,
		castArrayParam: (name, _column, dim) => `${name}::regnamespace${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	regoper: {
		castParam: (name) => `${name}::regoper`,
		castArrayParam: (name, _column, dim) => `${name}::regoper${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	regoperator: {
		castParam: (name) => `${name}::regoperator`,
		castArrayParam: (name, _column, dim) => `${name}::regoperator${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	regproc: {
		castParam: (name) => `${name}::regproc`,
		castArrayParam: (name, _column, dim) => `${name}::regproc${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	regprocedure: {
		castParam: (name) => `${name}::regprocedure`,
		castArrayParam: (name, _column, dim) => `${name}::regprocedure${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	regrole: {
		castParam: (name) => `${name}::regrole`,
		castArrayParam: (name, _column, dim) => `${name}::regrole${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	regtype: {
		castParam: (name) => `${name}::regtype`,
		castArrayParam: (name, _column, dim) => `${name}::regtype${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	serial: {
		castParam: (name) => `${name}::integer`,
		castArrayParam: (name, _column, dim) => `${name}::integer${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	smallint: {
		castParam: (name) => `${name}::smallint`,
		castArrayParam: (name, _column, dim) => `${name}::smallint${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	smallserial: {
		castParam: (name) => `${name}::smallint`,
		castArrayParam: (name, _column, dim) => `${name}::smallint${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	text: {
		castParam: (name) => `${name}::text`,
		castArrayParam: (name, _column, dim) => `${name}::text${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	time: {
		castParam: (name) => `${name}::time`,
		castArrayParam: (name, _column, dim) => `${name}::time${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	timetz: {
		castParam: (name) => `${name}::timetz`,
		castArrayParam: (name, _column, dim) => `${name}::timetz${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	tsmultirange: {
		castParam: (name) => `${name}::tsmultirange`,
		castArrayParam: (name, _column, dim) => `${name}::tsmultirange${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	tsquery: {
		castParam: (name) => `${name}::tsquery`,
		castArrayParam: (name, _column, dim) => `${name}::tsquery${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	tsrange: {
		castParam: (name) => `${name}::tsrange`,
		castArrayParam: (name, _column, dim) => `${name}::tsrange${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	tstzmultirange: {
		castParam: (name) => `${name}::tstzmultirange`,
		castArrayParam: (name, _column, dim) => `${name}::tstzmultirange${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	tstzrange: {
		castParam: (name) => `${name}::tstzrange`,
		castArrayParam: (name, _column, dim) => `${name}::tstzrange${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	tsvector: {
		castParam: (name) => `${name}::tsvector`,
		castArrayParam: (name, _column, dim) => `${name}::tsvector${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	varbit: {
		castParam: (name) => `${name}::varbit`,
		castArrayParam: (name, _column, dim) => `${name}::varbit${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	varchar: {
		castParam: (name) => `${name}::varchar`,
		castArrayParam: (name, _column, dim) => `${name}::varchar${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	xml: {
		castParam: (name) => `${name}::xml`,
		castArrayParam: (name, _column, dim) => `${name}::xml${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	enum: {
		cast: castToText,
		castArray: castToTextArr,
		castParam: (name, column) => `${name}::${column.getSQLType()}`,
		castArrayParam: (name, column, dimensions) => `${name}::${column.getSQLType()}${'[]'.repeat(dimensions)}`,
		normalizeParamArray: makePgArray,
	},
	numeric: {
		cast: castToText,
		castArray: castToTextArr,
		castParam: (name) => `${name}::numeric`,
		castArrayParam: (name, _column, dim) => `${name}::numeric${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	'numeric:number': {
		cast: castToText,
		castArray: castToTextArr,
		castParam: (name) => `${name}::numeric`,
		castArrayParam: (name, _column, dim) => `${name}::numeric${'[]'.repeat(dim)}`,
		normalize: Number,
		normalizeArray: arrayCompatNormalize(Number),
		normalizeParamArray: makePgArray,
	},
	'numeric:bigint': {
		cast: castToText,
		castArray: castToTextArr,
		castParam: (name) => `${name}::numeric`,
		castArrayParam: (name, _column, dim) => `${name}::numeric${'[]'.repeat(dim)}`,
		normalize: BigInt,
		normalizeArray: arrayCompatNormalize(BigInt),
		normalizeParamArray: makePgArray,
	},
	bigint: {
		cast: castToText,
		castArray: castToTextArr,
		castParam: (name) => `${name}::bigint`,
		castArrayParam: (name, _column, dim) => `${name}::bigint${'[]'.repeat(dim)}`,
		normalize: BigInt,
		normalizeArray: arrayCompatNormalize(BigInt),
		normalizeParamArray: makePgArray,
	},
	'bigint:number': {
		cast: castToText,
		castArray: castToTextArr,
		castParam: (name) => `${name}::bigint`,
		castArrayParam: (name, _column, dim) => `${name}::bigint${'[]'.repeat(dim)}`,
		normalize: Number,
		normalizeArray: arrayCompatNormalize(Number),
		normalizeParamArray: makePgArray,
	},
	'bigint:string': {
		cast: castToText,
		castArray: castToTextArr,
		castParam: (name) => `${name}::bigint`,
		castArrayParam: (name, _column, dim) => `${name}::bigint${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	bigserial: {
		cast: castToText,
		castArray: castToTextArr,
		castParam: (name) => `${name}::bigint`,
		castArrayParam: (name, _column, dim) => `${name}::bigint${'[]'.repeat(dim)}`,
		normalize: BigInt,
		normalizeArray: arrayCompatNormalize(BigInt),
		normalizeParamArray: makePgArray,
	},
	'bigserial:number': {
		cast: castToText,
		castArray: castToTextArr,
		castParam: (name) => `${name}::bigint`,
		castArrayParam: (name, _column, dim) => `${name}::bigint${'[]'.repeat(dim)}`,
		normalize: Number,
		normalizeArray: arrayCompatNormalize(Number),
		normalizeParamArray: makePgArray,
	},
	date: {
		castArray: castToTextArr,
		castParam: (name) => `${name}::date`,
		castArrayParam: (name, _column, dim) => `${name}::date${'[]'.repeat(dim)}`,
		normalize: textToDate,
		normalizeArray: arrayCompatNormalize(textToDate),
		normalizeParamArray: makePgArray,
	},
	'date:string': {
		castArray: castToTextArr,
		castParam: (name) => `${name}::date`,
		castArrayParam: (name, _column, dim) => `${name}::date${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	float4: {
		castParam: (name) => `${name}::real`,
		castArrayParam: (name, _column, dim) => `${name}::real${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	int: {
		castParam: (name) => `${name}::integer`,
		castArrayParam: (name, _column, dim) => `${name}::integer${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	timestamp: {
		castArray: castToTextArr,
		castParam: (name) => `${name}::timestamp`,
		castArrayParam: (name, _column, dim) => `${name}::timestamp${'[]'.repeat(dim)}`,
		normalize: textToDateWithTz,
		normalizeArray: arrayCompatNormalize(textToDateWithTz),
		normalizeParam: (value) => value.replace('T', ' ').replace('Z', ''),
		normalizeParamArray: makePgArray,
	},
	timestamptz: {
		cast: castToText,
		castArray: castToTextArr,
		castParam: (name) => `${name}::timestamptz`,
		castArrayParam: (name, _column, dim) => `${name}::timestamptz${'[]'.repeat(dim)}`,
		normalize: textToDate,
		normalizeArray: arrayCompatNormalize(textToDate),
		normalizeParamArray: makePgArray,
	},
	'timestamp:string': {
		castArray: castToTextArr,
		castParam: (name) => `${name}::timestamp`,
		castArrayParam: (name, _column, dim) => `${name}::timestamp${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	'timestamptz:string': {
		cast: castToText,
		castArray: castToTextArr,
		castParam: (name) => `${name}::timestamptz`,
		castArrayParam: (name, _column, dim) => `${name}::timestamptz${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
	uuid: {
		castParam: (name) => `${name}::uuid`,
		castArrayParam: (name, _column, dim) => `${name}::uuid${'[]'.repeat(dim)}`,
		normalizeParamArray: makePgArray,
	},
});
