/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import 'sst';
declare module 'sst' {
	export interface Resource {
		MyVpc: {
			type: 'sst.aws.Vpc';
		};
		Postgres: {
			clusterArn: string;
			database: string;
			host: string;
			password: string;
			port: number;
			reader: string;
			secretArn: string;
			type: 'sst.aws.Aurora';
			username: string;
		};
	}
}

import 'sst';
export {};
