import { firebirdTable, integer, varchar } from 'drizzle-orm/firebird-core';
import { drizzle } from 'drizzle-orm/node-firebird';
import { migrate as migrateFirebird } from 'drizzle-orm/node-firebird/migrator';
import { existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { introspectFirebird } from 'src/cli/commands/introspect';
import { prepareAndMigrateFirebird } from 'src/cli/commands/migrate';
import { firebirdPush } from 'src/cli/commands/push';
import { drizzleForFirebird } from 'src/serializer/studio';
import { afterAll, beforeAll, beforeEach, describe, expect, test, vi } from 'vitest';
import { cleanupFirebirdKitObjects, createFirebirdTestDatabase, type FirebirdTestDatabase } from './common';

const studioUsers = firebirdTable('KIT_STUDIO_USERS', {
	id: integer('ID').primaryKey(),
	name: varchar('NAME', { length: 80 }).notNull(),
});

let firebird: FirebirdTestDatabase;
let tempRoot: string;

beforeAll(async () => {
	tempRoot = mkdtempSync(join(process.cwd(), 'tests/.tmp-firebird-'));
	firebird = await createFirebirdTestDatabase();
});

beforeEach(async () => {
	await cleanupFirebirdKitObjects(firebird);
});

afterAll(async () => {
	await cleanupFirebirdKitObjects(firebird);
	await firebird?.stop();
	if (tempRoot && existsSync(tempRoot)) {
		rmSync(tempRoot, { recursive: true, force: true });
	}
});

describe('drizzle-kit firebird', () => {
	test('generates and applies Firebird migrations', async () => {
		const workspace = createWorkspace('generate');
		const schemaPath = writeSchema(workspace, 'schema.ts', generateSchemaSource());
		const out = join(workspace, 'drizzle');

		await prepareAndMigrateFirebird({
			schema: schemaPath,
			out,
			name: 'firebird_generate',
			breakpoints: true,
			custom: false,
			prefix: 'index',
			dialect: 'firebird',
			bundle: false,
		});

		const migration = readOnlyMigration(out);
		expect(migration).toContain('CREATE TABLE "KIT_GENERATE_USERS"');
		expect(migration).toContain('GENERATED BY DEFAULT AS IDENTITY');
		expect(migration).toContain('ALTER TABLE "KIT_GENERATE_POSTS" ADD CONSTRAINT "KIT_GENERATE_POSTS_USER_FK"');
		expect(migration).toContain('CREATE UNIQUE INDEX "KIT_GENERATE_USERS_NAME_UNQ"');
		expect(migration).toContain('CREATE VIEW "KIT_GENERATE_USER_NAMES"');

		await migrateFirebird(drizzle(firebird.client), { migrationsFolder: out });

		expect(await relationExists('KIT_GENERATE_USERS')).toBe(true);
		expect(await relationExists('KIT_GENERATE_POSTS')).toBe(true);
		expect(await relationExists('KIT_GENERATE_USER_NAMES')).toBe(true);
	});

	test('pulls Firebird tables, relations, indexes, checks and views', async () => {
		await createPullFixture();

		const out = createWorkspace('pull');
		const exitSpy = vi.spyOn(process, 'exit').mockImplementation(
			((code?: number | string | null | undefined) => {
				throw new Error(`process.exit:${code}`);
			}) as never,
		);
		try {
			await expect(introspectFirebird(
				'preserve',
				out,
				true,
				firebird.credentials,
				['KIT_PULL_*'],
				'index',
			)).rejects.toThrow('process.exit:0');
		} finally {
			exitSpy.mockRestore();
		}

		const schema = readFileSync(join(out, 'schema.ts'), 'utf8');
		const relations = readFileSync(join(out, 'relations.ts'), 'utf8');
		const migration = readOnlyMigration(out);

		expect(schema).toContain('firebirdTable("KIT_PULL_USERS"');
		expect(schema).toContain('generatedByDefaultAsIdentity');
		expect(schema).toContain('uniqueIndex("KIT_PULL_USERS_NAME_UNQ"');
		expect(schema).toContain('check("KIT_PULL_USERS_ACTIVE_CHECK"');
		expect(schema).toContain('firebirdView("KIT_PULL_USER_NAMES"');
		expect(relations).toContain('KIT_PULL_USER: one(KIT_PULL_USERS');
		expect(relations).toContain('KIT_PULL_POSTS: many(KIT_PULL_POSTS)');
		expect(migration).toContain('CREATE TABLE "KIT_PULL_USERS"');
		expect(migration).toContain('CREATE VIEW "KIT_PULL_USER_NAMES"');
	});

	test('pushes Firebird schema changes', async () => {
		const workspace = createWorkspace('push');
		const schemaPath = writeSchema(workspace, 'schema.ts', pushSchemaSource());

		await firebirdPush(
			schemaPath,
			false,
			false,
			firebird.credentials,
			['KIT_PUSH_*'],
			true,
			undefined,
		);

		expect(await relationExists('KIT_PUSH_USERS')).toBe(true);
		expect(await relationExists('KIT_PUSH_POSTS')).toBe(true);

		await firebird.query(
			'insert into "KIT_PUSH_USERS" ("ID", "NAME") values (?, ?)',
			[1, 'Pushed'],
		);
		await firebird.query(
			'insert into "KIT_PUSH_POSTS" ("ID", "USER_ID", "TITLE") values (?, ?, ?)',
			[10, 1, 'Post'],
		);

		const rows = await firebird.query<{ NAME: string; TITLE: string }>(`
			select u."NAME", p."TITLE"
			from "KIT_PUSH_USERS" u
			join "KIT_PUSH_POSTS" p on p."USER_ID" = u."ID"
		`);
		expect(rows).toEqual([{ NAME: 'Pushed', TITLE: 'Post' }]);
	});

	test('serves Firebird through the Studio proxy', async () => {
		await firebird.query('create table "KIT_STUDIO_USERS" ("ID" integer primary key, "NAME" varchar(80) not null)');
		await firebird.query('create view "KIT_STUDIO_USER_NAMES" as select "ID", "NAME" from "KIT_STUDIO_USERS"');
		await firebird.query('insert into "KIT_STUDIO_USERS" ("ID", "NAME") values (?, ?)', [1, 'Studio']);

		const setup = await drizzleForFirebird(
			firebird.credentials,
			{ public: { studioUsers } },
			{},
		);

		expect(setup.dialect).toBe('sqlite');
		expect(setup.packageName).toBe('node-firebird');

		const tables = await setup.proxy({
			sql: "select m.name, m.tbl_name, m.sql from sqlite_master as m where m.type = 'table'",
			mode: 'object',
			method: 'all',
		});
		expect(tables.some((row) => row.name === 'KIT_STUDIO_USERS')).toBe(true);

		const rows = await setup.proxy({
			sql: 'select "ID", "NAME" from "KIT_STUDIO_USERS" limit 1 offset 0',
			mode: 'object',
			method: 'all',
		});
		expect(rows).toEqual([{ ID: 1, NAME: 'Studio' }]);

		const txResult = await setup.transactionProxy([
			{ sql: 'select count(*) as TOTAL from "KIT_STUDIO_USERS"', method: 'all' },
		]);
		expect(txResult[0]).toEqual([{ TOTAL: 1 }]);
	});
});

function createWorkspace(name: string) {
	const path = join(tempRoot, name);
	mkdirSync(path, { recursive: true });
	return path;
}

function writeSchema(workspace: string, filename: string, source: string) {
	const schemaPath = join(workspace, filename);
	writeFileSync(schemaPath, source);
	return schemaPath;
}

function readOnlyMigration(out: string) {
	const migration = readdirSync(out).find((entry) => entry.endsWith('.sql'));
	if (!migration) {
		throw new Error(`No migration file found in ${out}`);
	}
	return readFileSync(join(out, migration), 'utf8');
}

async function relationExists(name: string) {
	const rows = await firebird.query<{ EXISTS: number }>(
		`
			select 1 as "EXISTS"
			from rdb$relations
			where rdb$relation_name = ?
		`,
		[name],
	);
	return rows.length > 0;
}

async function createPullFixture() {
	await firebird.query(`
		create table "KIT_PULL_USERS" (
			"ID" integer generated by default as identity primary key,
			"NAME" varchar(80) not null,
			"ACTIVE" boolean default true not null,
			constraint "KIT_PULL_USERS_NAME_UNQ" unique ("NAME"),
			constraint "KIT_PULL_USERS_ACTIVE_CHECK" check("ACTIVE" in (true, false))
		)
	`);
	await firebird.query(`
		create table "KIT_PULL_POSTS" (
			"ID" integer primary key,
			"USER_ID" integer not null,
			"TITLE" varchar(120) not null,
			constraint "KIT_PULL_POSTS_USER_FK" foreign key ("USER_ID") references "KIT_PULL_USERS"("ID") on delete cascade
		)
	`);
	await firebird.query('create index "KIT_PULL_POSTS_TITLE_IDX" on "KIT_PULL_POSTS" ("TITLE")');
	await firebird.query('create view "KIT_PULL_USER_NAMES" as select "ID", "NAME" from "KIT_PULL_USERS"');
}

function generateSchemaSource() {
	return `
		import { sql } from 'drizzle-orm';
		import { boolean, check, firebirdTable, firebirdView, foreignKey, index, integer, uniqueIndex, varchar } from 'drizzle-orm/firebird-core';

		export const users = firebirdTable('KIT_GENERATE_USERS', {
			id: integer('ID').primaryKey().generatedByDefaultAsIdentity(),
			name: varchar('NAME', { length: 80 }).notNull(),
			active: boolean('ACTIVE').default(true).notNull(),
		}, (table) => ({
			nameUnq: uniqueIndex('KIT_GENERATE_USERS_NAME_UNQ').on(table.name),
			activeCheck: check('KIT_GENERATE_USERS_ACTIVE_CHECK', sql.raw('"ACTIVE" in (true, false)')),
		}));

		export const posts = firebirdTable('KIT_GENERATE_POSTS', {
			id: integer('ID').primaryKey(),
			userId: integer('USER_ID').notNull(),
			title: varchar('TITLE', { length: 120 }).notNull(),
		}, (table) => ({
			titleIdx: index('KIT_GENERATE_POSTS_TITLE_IDX').on(table.title),
			userFk: foreignKey({
				name: 'KIT_GENERATE_POSTS_USER_FK',
				columns: [table.userId],
				foreignColumns: [users.id],
			}).onDelete('cascade'),
		}));

		export const userNames = firebirdView('KIT_GENERATE_USER_NAMES', {
			id: integer('ID'),
			name: varchar('NAME', { length: 80 }),
		}).as(sql\`select \${users.id} as ID, \${users.name} as NAME from \${users}\`);
	`;
}

function pushSchemaSource() {
	return `
		import { firebirdTable, foreignKey, index, integer, uniqueIndex, varchar } from 'drizzle-orm/firebird-core';

		export const users = firebirdTable('KIT_PUSH_USERS', {
			id: integer('ID').primaryKey(),
			name: varchar('NAME', { length: 80 }).notNull(),
		}, (table) => ({
			nameUnq: uniqueIndex('KIT_PUSH_USERS_NAME_UNQ').on(table.name),
		}));

		export const posts = firebirdTable('KIT_PUSH_POSTS', {
			id: integer('ID').primaryKey(),
			userId: integer('USER_ID').notNull(),
			title: varchar('TITLE', { length: 120 }).notNull(),
		}, (table) => ({
			titleIdx: index('KIT_PUSH_POSTS_TITLE_IDX').on(table.title),
			userFk: foreignKey({
				name: 'KIT_PUSH_POSTS_USER_FK',
				columns: [table.userId],
				foreignColumns: [users.id],
			}).onDelete('cascade'),
		}));
	`;
}
