import { bigint, integer, pgSchema, pgSequence, pgTable, serial, smallint, text } from 'drizzle-orm/pg-core';
import { afterAll, beforeAll, beforeEach, expect, test } from 'vitest';
import { diff, prepareTestDatabase, push, TestDatabase } from './mocks';

// same table - no diff
// 2. identity always/by default - no params +
// 3. identity always/by default - with a few params +
// 4. identity always/by default - with all params +

// diff table with create statement
// 2. identity always/by default - no params +
// 3. identity always/by default - with a few params +
// 4. identity always/by default - with all params +

// diff for drop statement
// 2. identity always/by default - no params, with params +

// diff for alters
// 2. identity always/by default - no params -> add param +
// 3. identity always/by default - with a few params - remove/add/change params +
// 4. identity always/by default - with all params - remove/add/change params +

// @vitest-environment-options {"max-concurrency":1}
let _: TestDatabase;
let db: TestDatabase['db'];

beforeAll(async () => {
	_ = await prepareTestDatabase();
	db = _.db;
});

afterAll(async () => {
	await _.close();
});

beforeEach(async () => {
	await _.clear();
});

test('create table: identity always/by default - no params', async () => {
	const from = {};

	const to = {
		users: pgTable('users', {
			id: integer('id').generatedByDefaultAsIdentity(),
			id1: bigint('id1', { mode: 'number' }).generatedByDefaultAsIdentity(),
			id2: smallint('id2').generatedByDefaultAsIdentity(),
		}),
	};

	const { sqlStatements: st } = await diff(from, to, []);

	const { sqlStatements: pst } = await push({
		db,
		to,
	});

	const st0 = [
		'CREATE TABLE "users" (\n\t"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),\n\t"id1" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id1_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),\n\t"id2" smallint GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id2_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1)\n);\n',
	];
	expect(st).toStrictEqual(st0);
	expect(pst).toStrictEqual(st0);
});

test('create table: identity always/by default - few params', async () => {
	// TODO revise: added id1, id2 columns to users table, like in same test from push.test.ts
	const from = {};

	const to = {
		users: pgTable('users', {
			id: integer('id').generatedByDefaultAsIdentity({
				name: 'custom_seq',
				increment: 4,
			}),
			id1: bigint('id1', { mode: 'number' }).generatedByDefaultAsIdentity({
				startWith: 120,
				maxValue: 17000,
			}),
			id2: smallint('id2').generatedByDefaultAsIdentity({ cycle: true }),
		}),
	};

	const { sqlStatements: st } = await diff(from, to, []);

	const { sqlStatements: pst } = await push({
		db,
		to,
	});

	const st0 = [
		'CREATE TABLE "users" (\n\t"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "custom_seq" INCREMENT BY 4 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),\n\t"id1" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id1_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 17000 START WITH 120 CACHE 1),\n\t"id2" smallint GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id2_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1 CYCLE)\n);\n',
	];
	expect(st).toStrictEqual(st0);
	expect(pst).toStrictEqual(st0);
});

test('create table: identity always/by default - all params', async () => {
	// TODO revise: added id1, id2 columns to users table, like in same test from push.test.ts
	const from = {};

	const to = {
		users: pgTable('users', {
			id: integer('id').generatedByDefaultAsIdentity({
				name: 'custom_seq',
				increment: 4,
				minValue: 3,
				maxValue: 1000,
				cache: 200,
				cycle: false,
			}),
			id1: bigint('id1', { mode: 'number' }).generatedByDefaultAsIdentity({
				startWith: 120,
				maxValue: 17000,
				increment: 3,
				cycle: true,
				cache: 100,
			}),
			id2: smallint('id2').generatedByDefaultAsIdentity({ cycle: true }),
		}),
	};

	const { sqlStatements: st } = await diff(from, to, []);

	const { sqlStatements: pst } = await push({
		db,
		to,
	});

	const st0 = [
		'CREATE TABLE "users" (\n\t"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "custom_seq" INCREMENT BY 4 MINVALUE 3 MAXVALUE 1000 START WITH 3 CACHE 200),\n\t"id1" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id1_seq" INCREMENT BY 3 MINVALUE 1 MAXVALUE 17000 START WITH 120 CACHE 100 CYCLE),\n\t"id2" smallint GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id2_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1 CYCLE)\n);\n',
	];
	expect(st).toStrictEqual(st0);
	expect(pst).toStrictEqual(st0);
});

test('no diff: identity always/by default - no params', async () => {
	const from = {
		users: pgTable('users', {
			id: integer('id').generatedByDefaultAsIdentity(),
			id2: integer('id2').generatedAlwaysAsIdentity(),
		}),
	};

	const to = {
		users: pgTable('users', {
			id: integer('id').generatedByDefaultAsIdentity(),
			id2: integer('id2').generatedAlwaysAsIdentity(),
		}),
	};

	const { sqlStatements: st } = await diff(from, to, []);

	await push({ db, to: from });
	const { sqlStatements: pst } = await push({
		db,
		to,
	});

	const st0: string[] = [];
	expect(st).toStrictEqual(st0);
	expect(pst).toStrictEqual(st0);
});

test('no diff: identity always/by default - few params', async () => {
	const from = {
		users: pgTable('users', {
			id: integer('id').generatedByDefaultAsIdentity({
				name: 'custom_seq',
				increment: 4,
			}),
			id2: integer('id2').generatedAlwaysAsIdentity({
				increment: 1,
				startWith: 3,
			}),
		}),
	};

	const to = {
		users: pgTable('users', {
			id: integer('id').generatedByDefaultAsIdentity({
				name: 'custom_seq',
				increment: 4,
			}),
			id2: integer('id2').generatedAlwaysAsIdentity({
				increment: 1,
				startWith: 3,
			}),
		}),
	};

	const { sqlStatements: st } = await diff(from, to, []);

	await push({ db, to: from });
	const { sqlStatements: pst } = await push({
		db,
		to,
	});

	const st0: string[] = [];
	expect(st).toStrictEqual(st0);
	expect(pst).toStrictEqual(st0);
});

test('no diff: identity always/by default - all params', async () => {
	const from = {
		users: pgTable('users', {
			id: integer('id').generatedByDefaultAsIdentity({
				name: 'custom_seq',
				increment: 4,
				minValue: 3,
				maxValue: 1000,
				cache: 200,
				cycle: false,
			}),
			id2: integer('id2').generatedAlwaysAsIdentity({
				startWith: 10,
				minValue: 10,
				maxValue: 1000,
				cycle: true,
				cache: 10,
				increment: 2,
			}),
		}),
	};

	const to = {
		users: pgTable('users', {
			id: integer('id').generatedByDefaultAsIdentity({
				name: 'custom_seq',
				increment: 4,
				minValue: 3,
				maxValue: 1000,
				cache: 200,
				cycle: false,
			}),
			id2: integer('id2').generatedAlwaysAsIdentity({
				startWith: 10,
				minValue: 10,
				maxValue: 1000,
				cycle: true,
				cache: 10,
				increment: 2,
			}),
		}),
	};

	const { sqlStatements: st } = await diff(from, to, []);

	await push({ db, to: from });
	const { sqlStatements: pst } = await push({
		db,
		to,
	});

	const st0: string[] = [];
	expect(st).toStrictEqual(st0);
	expect(pst).toStrictEqual(st0);
});

test('drop identity from a column - no params', async () => {
	const from = {
		users: pgTable('users', {
			id: integer('id').generatedByDefaultAsIdentity(),
		}),
	};

	const to = {
		users: pgTable('users', {
			id: integer('id'),
		}),
	};

	const { sqlStatements: st } = await diff(from, to, []);

	await push({ db, to: from });
	const { sqlStatements: pst } = await push({
		db,
		to,
	});

	const st0 = [
		`ALTER TABLE \"users\" ALTER COLUMN \"id\" DROP IDENTITY;`,
		'ALTER TABLE "users" ALTER COLUMN "id" DROP NOT NULL;',
	];
	expect(st).toStrictEqual(st0);
	expect(pst).toStrictEqual(st0);
});

test('drop identity from a column - few params', async () => {
	// TODO revise: added id1, id2 columns to users table, like in the same test from push.test.ts
	const from = {
		users: pgTable('users', {
			id: integer('id').generatedByDefaultAsIdentity({
				startWith: 100,
				increment: 3,
			}),
			id1: integer('id1').generatedByDefaultAsIdentity({
				name: 'custom_name1',
				increment: 4,
			}),
			id2: integer('id2').generatedAlwaysAsIdentity({
				name: 'custom_name2',
				increment: 4,
			}),
		}),
	};

	const to = {
		users: pgTable('users', {
			id: integer('id'),
			id1: integer('id1'),
			id2: integer('id2'),
		}),
	};

	const { sqlStatements: st } = await diff(from, to, []);

	await push({ db, to: from });
	const { sqlStatements: pst } = await push({
		db,
		to,
	});

	const st0 = [
		`ALTER TABLE \"users\" ALTER COLUMN \"id\" DROP IDENTITY;`,
		'ALTER TABLE "users" ALTER COLUMN "id" DROP NOT NULL;',
		'ALTER TABLE "users" ALTER COLUMN "id1" DROP IDENTITY;',
		'ALTER TABLE "users" ALTER COLUMN "id1" DROP NOT NULL;',
		'ALTER TABLE "users" ALTER COLUMN "id2" DROP IDENTITY;',
		'ALTER TABLE "users" ALTER COLUMN "id2" DROP NOT NULL;',
	];
	expect(st).toStrictEqual(st0);
	expect(pst).toStrictEqual(st0);
});

test('drop identity from a column - all params', async () => {
	// TODO revise: added id1, id2 columns to users table, like in the same test from push.test.ts
	const from = {
		users: pgTable('users', {
			id: integer('id').generatedByDefaultAsIdentity({
				startWith: 100,
				increment: 3,
				cache: 100,
				cycle: true,
			}),
			id1: integer('id1').generatedByDefaultAsIdentity({
				name: 'custom_name1',
				startWith: 10,
				minValue: 10,
				maxValue: 1000,
				cycle: true,
				cache: 10,
				increment: 2,
			}),
			id2: integer('id2').generatedAlwaysAsIdentity({
				name: 'custom_name2',
				startWith: 10,
				minValue: 10,
				maxValue: 1000,
				cycle: true,
				cache: 10,
				increment: 2,
			}),
		}),
	};

	const to = {
		users: pgTable('users', {
			id: integer('id'),
			id1: integer('id1'),
			id2: integer('id2'),
		}),
	};

	const { sqlStatements: st } = await diff(from, to, []);

	await push({ db, to: from });
	const { sqlStatements: pst } = await push({
		db,
		to,
	});

	const st0 = [
		`ALTER TABLE \"users\" ALTER COLUMN \"id\" DROP IDENTITY;`,
		'ALTER TABLE "users" ALTER COLUMN "id" DROP NOT NULL;',
		`ALTER TABLE \"users\" ALTER COLUMN \"id1\" DROP IDENTITY;`,
		'ALTER TABLE "users" ALTER COLUMN "id1" DROP NOT NULL;',
		`ALTER TABLE \"users\" ALTER COLUMN \"id2\" DROP IDENTITY;`,
		'ALTER TABLE "users" ALTER COLUMN "id2" DROP NOT NULL;',
	];
	expect(st).toStrictEqual(st0);
	expect(pst).toStrictEqual(st0);
});

test('alter identity from a column - no params', async () => {
	const from = {
		users: pgTable('users', {
			id: integer('id').generatedByDefaultAsIdentity(),
		}),
	};

	const to = {
		users: pgTable('users', {
			id: integer('id').generatedByDefaultAsIdentity({ startWith: 100 }),
		}),
	};

	const { sqlStatements: st } = await diff(from, to, []);

	await push({ db, to: from });
	const { sqlStatements: pst } = await push({
		db,
		to,
	});

	const st0 = [
		'ALTER TABLE "users" ALTER COLUMN "id" SET START WITH 100;',
	];
	expect(st).toStrictEqual(st0);
	expect(pst).toStrictEqual(st0);
});

test('alter identity from a column - few params', async () => {
	const from = {
		users: pgTable('users', {
			id: integer('id').generatedByDefaultAsIdentity({ startWith: 100 }),
		}),
	};

	// TODO revise: added more params, like in same test from push.test.ts
	const to = {
		users: pgTable('users', {
			id: integer('id').generatedByDefaultAsIdentity({
				startWith: 100,
				cache: 10,
				increment: 4,
				maxValue: 10000,
			}),
		}),
	};

	const { sqlStatements: st } = await diff(from, to, []);

	await push({ db, to: from });
	const { sqlStatements: pst } = await push({
		db,
		to,
	});

	const st0 = [
		'ALTER TABLE "users" ALTER COLUMN "id" SET MAXVALUE 10000;',
		'ALTER TABLE "users" ALTER COLUMN "id" SET INCREMENT BY 4;',
		'ALTER TABLE "users" ALTER COLUMN "id" SET CACHE 10;',
	];

	expect(st).toStrictEqual(st0);
	expect(pst).toStrictEqual(st0);
});

test('alter identity from a column - by default to always', async () => {
	const from = {
		users: pgTable('users', {
			id: integer('id').generatedByDefaultAsIdentity(),
		}),
	};

	const to = {
		users: pgTable('users', {
			id: integer('id').generatedAlwaysAsIdentity({
				startWith: 100,
				cache: 10,
			}),
		}),
	};

	const { sqlStatements: st } = await diff(from, to, []);

	await push({ db, to: from });
	const { sqlStatements: pst } = await push({
		db,
		to,
	});

	const st0 = [
		'ALTER TABLE "users" ALTER COLUMN "id" SET GENERATED ALWAYS;',
		'ALTER TABLE "users" ALTER COLUMN "id" SET START WITH 100;',
		'ALTER TABLE "users" ALTER COLUMN "id" SET CACHE 10;',
	];
	expect(st).toStrictEqual(st0);
	expect(pst).toStrictEqual(st0);
});

test('alter identity from a column - always to by default', async () => {
	const from = {
		users: pgTable('users', {
			id: integer('id').generatedAlwaysAsIdentity(),
		}),
	};

	const to = {
		users: pgTable('users', {
			id: integer('id').generatedByDefaultAsIdentity({
				startWith: 100,
				cache: 10,
			}),
		}),
	};

	const { sqlStatements: st } = await diff(from, to, []);

	await push({ db, to: from });
	const { sqlStatements: pst } = await push({
		db,
		to,
	});

	const st0 = [
		'ALTER TABLE "users" ALTER COLUMN "id" SET GENERATED BY DEFAULT;',
		'ALTER TABLE "users" ALTER COLUMN "id" SET START WITH 100;',
		'ALTER TABLE "users" ALTER COLUMN "id" SET CACHE 10;',
	];
	expect(st).toStrictEqual(st0);
	expect(pst).toStrictEqual(st0);
});

test('add column with identity - few params', async () => {
	const schema1 = {
		users: pgTable('users', {
			email: text('email'),
		}),
	};

	const schema2 = {
		users: pgTable('users', {
			email: text('email'),
			id: integer('id').generatedByDefaultAsIdentity({ name: 'custom_name' }),
			id1: integer('id1').generatedAlwaysAsIdentity({
				name: 'custom_name1',
				increment: 4,
			}),
		}),
	};

	const { sqlStatements: st } = await diff(schema1, schema2, []);

	await push({ db, to: schema1 });
	const { sqlStatements: pst } = await push({ db, to: schema2 });

	const st0: string[] = [
		'ALTER TABLE "users" ADD COLUMN "id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "custom_name" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);',
		'ALTER TABLE "users" ADD COLUMN "id1" integer GENERATED ALWAYS AS IDENTITY (sequence name "custom_name1" INCREMENT BY 4 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);',
	];
	expect(st).toStrictEqual(st0);
	expect(pst).toStrictEqual(st0);
});

test('add identity to column - few params', async () => {
	const schema1 = {
		users: pgTable('users', {
			id: integer('id').notNull(),
			id1: integer('id1').notNull(),
		}),
	};

	const schema2 = {
		users: pgTable('users', {
			id: integer('id').generatedByDefaultAsIdentity({ name: 'custom_name' }),
			id1: integer('id1').generatedAlwaysAsIdentity({
				name: 'custom_name1',
				increment: 4,
			}),
		}),
	};

	const { sqlStatements: st } = await diff(schema1, schema2, []);

	await push({ db, to: schema1 });
	const { sqlStatements: pst } = await push({ db, to: schema2 });

	const st0: string[] = [
		'ALTER TABLE "users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "custom_name" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);',
		'ALTER TABLE "users" ALTER COLUMN "id1" ADD GENERATED ALWAYS AS IDENTITY (sequence name "custom_name1" INCREMENT BY 4 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);',
	];
	expect(st).toStrictEqual(st0);
	expect(pst).toStrictEqual(st0);
});

// https://github.com/drizzle-team/drizzle-orm/issues/2630
test('alter sequence to identity', async () => {
	const from = {
		users: pgTable('users', {
			id: serial().primaryKey(),
		}),
	};

	const to = {
		users: pgTable('users', {
			id: integer().primaryKey().generatedAlwaysAsIdentity(),
		}),
	};
	await push({ db, to: from });
	await db.query(`insert into users (id) values (default),(default),(default);`);

	const res = await push({ db, to, log: 'statements' });

	expect(res.sqlStatements).toStrictEqual([
		'ALTER TABLE "users" ALTER COLUMN "id" DROP DEFAULT;',
		'DROP SEQUENCE "users_id_seq";',
		'ALTER TABLE "users" ALTER COLUMN "id" SET DATA TYPE integer USING "id"::integer;',
		'ALTER TABLE "users" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);',
		'SELECT setval(\'users_id_seq\'::regclass, (SELECT COALESCE(MAX(id), 1) FROM "users"), false);',
	]);
});

// https://github.com/drizzle-team/drizzle-orm/issues/4969
test('mySchema; identity column', async () => {
	const schema = pgSchema('my-schema');
	const to = {
		schema,
		todo: schema.table('todo', {
			id: integer('id').primaryKey().generatedAlwaysAsIdentity(),
			title: text('title').notNull(),
			description: text('description'),
		}),
	};

	const { next: n1 } = await diff({}, to, []);
	await push({ db, to, schemas: ['public', 'my-schema'] });

	const { sqlStatements: st2 } = await diff(n1, to, []);
	const { sqlStatements: pst2 } = await push({ db, to, schemas: ['public', 'my-schema'] });

	expect(st2).toStrictEqual([]);
	expect(pst2).toStrictEqual([]);
});
